Repository fossasia/open-event-frontend, pull requests merged in 2019-07, with the labels that each got.

#3221 Test: Adding Tests for `Admin System Forms`
  tests/integration/components/forms/admin/settings/system/mail-settings-test.js
  tests/integration/components/forms/admin/settings/system/social-media-token-test.js
  tests/integration/components/forms/admin/settings/system/storage-option-test.js
Labels: tests

#3220 fix: Adding Speaker Image in Session Accordion
  app/templates/components/public/session-item.hbs
Labels: fix

#3224 fix: Avoid using external links for license images
  app/utils/dictionary/licenses.js
  public/images/copyright/attribution-logo.png
  public/images/copyright/attribution-nc-logo.png
  public/images/copyright/attribution-nc-nd-logo.png
  public/images/copyright/attribution-nc-sa-logo.png
  public/images/copyright/attribution-nd-logo.png
  public/images/copyright/attribution-sa-logo.png
  public/images/copyright/pdd-logo.png
  public/images/copyright/pdw-logo.png
Labels: fix

#3182 feat: Addition of Fields for reCAPTCHA
  app/components/forms/admin/settings/system-form.js
  app/components/forms/admin/settings/system/captcha-form.js
  app/models/custom-form.js
  app/models/setting.js
  app/templates/components/forms/admin/settings/system-form.hbs
  app/templates/components/forms/admin/settings/system/captcha-form.hbs
  tests/integration/components/forms/admin/settings/system/captcha-form-test.js
Labels: feature

#3013 feat: transfer ownership of event to another user
  app/components/modals/confirm-event-transfer-modal.js
  app/components/modals/event-transfer-modal.js
  app/controllers/events/view/settings.js
  app/router.js
  app/routes/events/view/settings.js
  app/templates/components/modals/confirm-event-transfer-modal.hbs
  app/templates/components/modals/event-transfer-modal.hbs
  app/templates/events/view.hbs
  app/templates/events/view/settings.hbs
Labels: feature

#3229 feat: introduce event owner role to the system
  app/models/admin-statistics-user.js
  app/models/event.js
  app/models/user.js
  app/routes/admin/events/list.js
  app/routes/admin/permissions/event-roles.js
  app/routes/events/list.js
  app/templates/admin/index.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/orders/event-info.hbs
  app/templates/components/orders/organizer-info.hbs
  app/templates/components/public/side-menu.hbs
  app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs
  app/templates/components/ui-table/cell/cell-roles.hbs
  app/templates/orders/new.hbs
  app/templates/public/index.hbs
Labels: feature

#3239 fix: Making Ticket List compatible with mobile view
  app/templates/components/public/ticket-list.hbs
Labels: fix

#3237 enh: Making company details optional in tax modal
  app/components/modals/tax-info-modal.js
  app/templates/components/modals/tax-info-modal.hbs
Labels: enhancement

#3235 enh: rearranges tabs in order and attendee view
  app/routes/events/view/tickets/attendees/index.js
  app/routes/events/view/tickets/orders/index.js
  app/templates/events/view/tickets/attendees.hbs
  app/templates/events/view/tickets/orders.hbs
Labels: enhancement

#3243 fix: Date sort support + avoid null sorts comparison
  app/components/tables/headers/sort.js
  app/controllers/events/list.js
Labels: fix

#3144 feat: Add CFS filter to sidebar filters in explore route.
  app/components/explore/side-bar.js
  app/controllers/explore.js
  app/routes/explore.js
  app/templates/components/explore/side-bar.hbs
  app/templates/explore.hbs
Labels: feature

#3211 feat: Rename Fees to Revenue and add Event Date in Admin Sales Fees.
  app/controllers/admin/sales/revenue.js
  app/models/admin-sales-fee.js
  app/router.js
  app/routes/admin/sales/revenue.js
  app/templates/admin/sales.hbs
  app/templates/admin/sales/revenue.hbs
Labels: feature

#3241 fix: Fixing Overlapping Components in `Manage Events`
  app/controllers/events/list.js
  app/extensions/ember-table/template.hbs
Labels: fix

#3180 enh: Gender as Dropdown in Attendee Form
  app/components/forms/orders/order-form.js
  app/mixins/custom-form.js
  app/templates/components/forms/orders/order-form.hbs
Labels: enhancement

#3171 feat: Add link "Show more calls for speakers" below section on start page.
  app/templates/index.hbs
Labels: feature

#3250 fix: `Show More Call For Speaker` button fixed
  app/templates/index.hbs
Labels: fix

#3209 fix: Added quantity, min/max price validations & fixed donations bugs
  app/components/forms/wizard/basic-details-step.js
  app/components/public/ticket-list.js
  app/components/widgets/forms/ticket-input.js
  app/models/ticket.js
  app/templates/components/public/ticket-list.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: fix

#3260 fix: Fix tax on donation tickets
  app/models/ticket.js
Labels: fix

#3264 feat: make billing fields mandatory for paid orders
  app/templates/components/forms/orders/order-form.hbs
Labels: feature

#3253 enh: Removal of Order Form from `Event Dashboard`
  app/components/forms/events/view/order-form.js
  app/routes/events/view/tickets/order-form.js
  app/templates/components/forms/events/view/order-form.hbs
  app/templates/events/view/tickets.hbs
  app/templates/events/view/tickets/order-form.hbs
  tests/integration/components/forms/events/view/order-form-test.js
Labels: enhancement

#3215 feat: Create user payment information form
  app/components/forms/user-payment-info-form.js
  app/models/user.js
  app/router.js
  app/routes/account/billing-info/invoices.js
  app/routes/account/billing-info/payment-info.js
  app/routes/account/billing.js
  app/routes/account/billing/index.js
  app/routes/account/billing/invoices.js
  app/routes/account/billing/payment-info.js
  app/templates/account.hbs
  app/templates/account/billing-info/payment-info.hbs
  app/templates/account/billing.hbs
  app/templates/account/billing/invoices.hbs
  app/templates/account/billing/payment-info.hbs
  app/templates/components/forms/user-payment-info-form.hbs
  tests/acceptance/billing-info-test.js
  tests/acceptance/invoices-test.js
  tests/acceptance/payment-info-test.js
Labels: feature

#3272 chore: Gettext fix
  package.json
  yarn.lock
Labels: chore

#3275 fix: wrap promises in try-catch
  app/services/auth-manager.js
Labels: fix

#3281 fix: Showing `Payment Options` for `Donations`
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#3286 test: Add integration tests for multiple forms
  tests/integration/components/forms/login-form-test.js
  tests/integration/components/forms/register-form-test.js
  tests/integration/components/forms/reset-password-form-test.js
  tests/integration/components/forms/user-payment-info-form-test.js
  tests/integration/components/forms/user-profile-form-test.js
Labels: tests

#3288 docs: Get-Text linking error
  docs/installation/local.md
Labels: documentation

#3296 enh: add billing info header to avoid confusion
  app/templates/components/forms/orders/order-form.hbs
Labels: enhancement

#3301 fix: Refactor login-form according to flask jwt extended changes
  app/components/forms/login-form.js
  tests/acceptance/login-test.js
Labels: fix

#3152 feat: add intial mechanism for billing options(admin)
  app/components/forms/admin/settings/billing.js
  app/controllers/admin/settings/billing.js
  app/models/setting.js
  app/router.js
  app/routes/admin/settings/billing.js
  app/templates/admin/settings.hbs
  app/templates/admin/settings/billing.hbs
  app/templates/components/forms/admin/settings/billing.hbs
Labels: feature

#3302 feat: Use ember tables for event speakers table
  app/controllers/events/view/speakers/list.js
  app/routes/events/view/speakers/list.js
  app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs
  app/templates/components/ui-table/cell/events/view/speakers/cell-is-featured.hbs
  app/templates/components/ui-table/cell/events/view/speakers/cell-simple-sessions.hbs
  app/templates/components/ui-table/cell/events/view/speakers/speaker-logo.hbs
  app/templates/components/ui-table/cell/events/view/speakers/speaker-mobile.hbs
  app/templates/events/view/speakers/list.hbs
Labels: feature

#3321 fix: Resolve broken discount codes for tax inclusive tickets
  app/components/public/ticket-list.js
  app/templates/components/public/ticket-list.hbs
Labels: fix

#3304 feat: optimize code for manage events table
  app/controllers/events/list.js
  app/routes/events/list.js
  app/templates/components/ui-table/cell/cell-event-general.hbs
  app/templates/events/list.hbs
  tests/integration/components/ui-table/cell/cell-event-general-test.js
Labels: feature

#3311 feat: Add adapter for discount codes to fetch them by event ID
  app/adapters/discount-code.js
Labels: feature

#3316 enh: Minor bugs and enhancements in admin area
  app/components/forms/admin/settings/billing.js
  app/controllers/admin/events/list.js
  app/controllers/admin/users/list.js
  app/controllers/admin/users/view/events/list.js
  app/templates/admin/users/view/events.hbs
  app/templates/components/forms/admin/settings/billing.hbs
Labels: enhancement

#3294 fix: Fix export events module(URL fetch logic)
  app/components/events/view/export/download-zip.js
  app/templates/components/events/view/export/download-zip.hbs
Labels: fix

#3297 fix: add billing information in order view page
  app/components/forms/orders/attendee-list.js
  app/templates/components/forms/orders/attendee-list.hbs
Labels: fix

#3308 fix: rendering of gender field
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#3327 fix: Pass event object to ticket list correctly
  app/templates/public/index.hbs
Labels: fix

#3325 feat: Add adapter for access codes to fetch them by event ID
  app/adapters/access-code.js
  app/components/public/ticket-list.js
Labels: feature

#3326 fix: Update GitHub URL Validator
  app/utils/validators.js
Labels: fix

#3271 fix: Fixed maps on events & explore page
  app/templates/components/explore/side-bar.hbs
  app/templates/components/public/event-map.hbs
Labels: fix

#3263 feat: Add checkbox to sidebar filters in explore route.
  app/templates/components/explore/side-bar.hbs
Labels: feature

#3331 fix: Remove not-ready-to-use relationship calls in admin users
  app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs
Labels: fix

#3333 fix: Revamp session-speaker custom forms, fix URLs
  app/components/forms/session-speaker-form.js
  app/models/custom-form.js
  app/models/session.js
  app/models/speaker.js
  app/templates/components/forms/session-speaker-form.hbs
Labels: fix

#3336 fix: use correct URL to download translations
  app/controllers/admin/content/translations.js
Labels: fix

#3338 fix: infinite loader on sessions page
  app/controllers/public/cfs/new-session.js
  app/routes/public/cfs/new-session.js
  app/templates/components/forms/session-speaker-form.hbs
Labels: fix
