Repository fossasia/open-event-frontend, pull requests merged in 2019-12, with the labels that each got.

#3552 fix: event sort by name to actually sort by name
  app/controllers/admin/events/list.js
  app/controllers/events/list.js
  app/templates/components/ui-table/cell/cell-event-general.hbs
  app/templates/components/ui-table/cell/cell-event.hbs
  tests/integration/components/ui-table/cell/cell-event-general-test.js
Labels: fix

#3694 fix: Displaying more informative error on Stripe Failure
  app/controllers/orders/pending.js
Labels: fix

#3700 fix: Removing Billing Info if not filled from the Order Dashboard
  app/components/forms/orders/attendee-list.js
  app/templates/orders/view.hbs
Labels: fix

#3705 fix: Past sessions rendering multiple times
  app/routes/my-sessions/list.js
Labels: fix

#3709 chore: reveal the custom widget form
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: chore

#3698 fix: footer copyright credits
  app/templates/components/footer-main.hbs
Labels: fix

#3713 chore: Lazy load paypal button
  app/components/paypal-button.js
  ember-cli-build.js
  package.json
  yarn.lock
Labels: chore

#3665 fix: side menu icon should not be visible in mobile when there is no menu
  app/controllers/public.js
  app/templates/public.hbs
Labels: fix

#3645 fix: fixing weird vertical shift
  app/templates/events/view.hbs
Labels: fix

#3701 fix: Email Override possible for all users
  app/components/forms/session-speaker-form.js
  app/routes/public.js
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/public/cfs/edit-speaker.hbs
  app/templates/public/cfs/new-speaker.hbs
Labels: fix

#3715 fix: appname for mobile screen
  app/templates/components/nav-bar.hbs
Labels: fix

#3716 chore: Migrate admin,account to ES6 in app/controllers
  app/controllers/account/password.js
  app/controllers/account/profile.js
  app/controllers/admin/content/events.js
  app/controllers/admin/content/index.js
  app/controllers/admin/content/pages.js
  app/controllers/admin/content/system-images/list.js
  app/controllers/admin/messages.js
  app/controllers/admin/modules.js
  app/controllers/admin/permissions/event-roles.js
  app/controllers/admin/permissions/system-roles.js
  app/controllers/admin/settings/analytics.js
  app/controllers/admin/settings/billing.js
  app/controllers/admin/settings/images.js
  app/controllers/admin/settings/index.js
  app/controllers/admin/settings/microservices.js
  app/controllers/admin/settings/payment-gateway.js
  app/controllers/admin/settings/ticket-fees.js
  app/controllers/admin/users/view/account/contact-info.js
Labels: chore

#3680 fix: improve quality of image before sending to server
  app/components/modals/cropper-modal.js
Labels: fix

#3721 chore: Migrating event,speakers,session in controllers to ES6
  app/controllers/create.js
  app/controllers/events/import.js
  app/controllers/events/view.js
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/edit/basic-details.js
  app/controllers/events/view/edit/sessions-speakers.js
  app/controllers/events/view/edit/sponsors.js
  app/controllers/events/view/export.js
  app/controllers/events/view/scheduler.js
  app/controllers/events/view/sessions.js
  app/controllers/events/view/sessions/create.js
  app/controllers/events/view/sessions/edit.js
  app/controllers/events/view/settings.js
  app/controllers/events/view/speakers.js
  app/controllers/events/view/speakers/create.js
  app/controllers/events/view/speakers/edit.js
Labels: chore

#3682 chore: migrating cropper-modal to ES6
  app/components/modals/cropper-modal.js
Labels: chore

#3722 feat: Defining cancelled orders in order view template
  app/templates/components/orders/order-summary.hbs
Labels: feature

#3515 feat: Removing session names from modal
  app/templates/components/modals/cfs-proposal-modal.hbs
  app/templates/components/public/call-for-speakers.hbs
Labels: feature

#3728 chore: update consistent netlify badge
  README.md
Labels: chore

#3720 fix: hide cancel button when order state is cancelled
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
Labels: fix

#3732 fix: Track field not rendering due to page size limit
  app/routes/public/cfs/new-session.js
Labels: Priority: Urgent, fix

#3737 hotfix: Reverting forms controller to ES5
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/edit/basic-details.js
  app/controllers/events/view/edit/sessions-speakers.js
  app/controllers/events/view/edit/sponsors.js
Labels: Priority: High, fix

#3736 feat: Replace config at runtime
  Dockerfile
  scripts/fastboot-server.js
  scripts/replace-config.js
Labels: feature

#3741 fix: Remove email-override condition model hook for organiser
  app/templates/components/forms/session-speaker-form.hbs
Labels: Priority: High, fix

#3742 chore: Hiding custom widget until it is complete
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: chore

#3743 fix: Speaker & Sessions can be added from dashboard
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/events/view/sessions/create.hbs
  app/templates/events/view/speakers/create.hbs
Labels: Priority: Urgent, fix

#3734 chore: Release v1.7.0
  Dockerfile
  README.md
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/edit/basic-details.js
  app/controllers/events/view/edit/sessions-speakers.js
  app/controllers/events/view/edit/sponsors.js
  app/routes/public/cfs/new-session.js
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/modals/cfs-proposal-modal.hbs
  app/templates/components/public/call-for-speakers.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/events/view/sessions/create.hbs
  app/templates/events/view/speakers/create.hbs
  scripts/fastboot-server.js
  scripts/replace-config.js
Labels: chore

#3745 chore: Replace cachedshoe with data-storefront
  app/adapters/application.js
  package.json
  yarn.lock
Labels: chore

#3749 refactor: fix hasOwnProperty and format code
  app/adapters/application.js
  app/components/forms/reset-password-form.js
  app/controllers/oauth/callback.js
  app/controllers/public/index.js
  app/controllers/register.js
  app/services/device.js
  app/services/loader.js
  config/environment.js
  scripts/replace-config.js
Labels: chore, refactor
