Repository fossasia/open-event-frontend, pull requests merged in 2019-10, with the labels that each got.

#3539 fix:add sort options to Speakers Table
  app/controllers/events/view/speakers/list.js
Labels: fix

#3554 fix: CodeCov for the repository
  .travis.yml
Labels: fix

#3557 fix: Hotfix for non-rendering paymentCurrencies
  app/templates/components/public/ticket-list.hbs
Labels: fix

#3488 fix: Enable sorting in admin users table
  app/controllers/admin/users/list.js
  app/templates/components/ui-table/cell/admin/users/cell-first-name.hbs
Labels: fix

#3561 docs: Update Docs to Reflect Change to .env.example
  docs/installation/local.md
Labels: documentation

#3535 fix: Nav Bar - Profile Tab works in Mobile View
  app/templates/components/side-bar.hbs
Labels: fix

#3553 fix: Improve RegExp for URLs in Admin settings
  app/utils/validators.js
Labels: fix

#3501 feat: add custom form widget
  app/components/forms/wizard/sessions-speakers-step.js
  app/models/custom-form.js
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: feature
