Repository fossasia/open-event-frontend, pull requests merged in 2019-06, with the labels that each got.

#3041 fix: update beforeModel transitions
  app/routes/verify.js
Labels: fix

#3063 fix: use global jquery for form validation
  app/components/forms/events/view/create-access-code.js
  app/components/forms/events/view/create-discount-code.js
Labels: fix

#3059 fix: tracks and sessionTypes loads on editing session
  app/routes/public/cfs/edit-session.js
Labels: fix

#3019 feat: Addition of Event End Date on Public Event Page
  app/controllers/public.js
  app/styles/pages/public-event.scss
  app/templates/public.hbs
Labels: feature

#2930 feat: Improving Tax Modal and Including company in Cards
  app/components/modals/tax-info-modal.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/tax-info-modal.hbs
Labels: feature

#3066 fix: pre-fetch event currency to render on edit discount code route
  app/routes/events/view/tickets/discount-codes/edit.js
  app/templates/events/view/tickets/discount-codes/edit.hbs
Labels: fix

#3068 fix: Show speaker image in session card.
  app/templates/components/public/session-item.hbs
Labels: fix

#3080 fix: Fix wrong submit time in sessions.
  app/models/session.js
Labels: fix

#3060 fix: Required Fields in Session-Speaker Form
  app/templates/components/forms/session-speaker-form.hbs
Labels: fix

#3089 fix: Fixed environment switch bug
  app/templates/components/forms/admin/settings/system-form.hbs
Labels: fix

#3081 feat: Implement pagination on notifications route
  app/routes/notifications/all.js
  app/templates/notifications/all.hbs
Labels: feature

#3044 fix: Fixing Scheduler View in Small Screens
  app/templates/events/view/scheduler.hbs
Labels: fix

#3073 feat: add initial mechanism for omise
  app/controllers/orders/pending.js
  app/templates/orders/pending.hbs
Labels: feature

#3093 fix: ensures sessions are listed in public/speakers by handling errors
  app/templates/components/public/speaker-item.hbs
Labels: fix

#3028 fix: Refactor buyer name fields in order-form
  app/components/forms/orders/order-form.js
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#3101 fix: redirect to event cfs page if clicked on event-card in cfs section
  app/templates/components/event-card.hbs
  app/templates/index.hbs
Labels: fix

#3097 feat: Infinity Lazy Loading on My Sessions Page
  app/routes/my-sessions/list.js
  app/templates/my-sessions/list.hbs
Labels: feature

#3103 fix: Make storage location names compatible with server
  app/templates/components/forms/admin/settings/system/storage-option.hbs
Labels: fix

#2926 fix: hides 'use ticketing system' to prevent spam
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#3046 feat: Mark checked in ticket as 'Checked In' on my-ticket page
  app/components/order-card.js
  app/templates/components/order-card.hbs
  tests/integration/components/order-card-test.js
Labels: feature

#3107 fix: Admin wizard: Persist smtp encryption settings
  app/templates/components/forms/admin/settings/system/mail-settings.hbs
Labels: fix

#3024 feat: AliPay frontend implementation(API Keys and Buttons)
  app/components/forms/admin/settings/payment-gateway-form.js
  app/components/forms/wizard/basic-details-step.js
  app/controllers/orders/pending.js
  app/models/event.js
  app/models/setting.js
  app/templates/components/forms/admin/settings/payment-gateway-form.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/orders/pending.hbs
  app/utils/dictionary/payment.js
  public/images/payment-logos/alipay.png
Labels: feature

#3120 fix: update text if user's account is not deletable
  app/templates/components/settings/danger-zone.hbs
Labels: fix

#3116 enh: Moved profile module to settings
  app/controllers/settings/profile.js
  app/router.js
  app/routes/settings/profile.js
  app/templates/components/nav-bar.hbs
  app/templates/components/side-bar.hbs
  app/templates/settings.hbs
  app/templates/settings/profile.hbs
  tests/acceptance/profile-test.js
Labels: enhancement

#3134 enh: rename non-admin settings routes to account
  app/components/account/application-section.js
  app/components/account/contact-info-section.js
  app/components/account/danger-zone.js
  app/components/account/email-preferences-section.js
  app/components/account/password-section.js
  app/controllers/account/contact-info.js
  app/controllers/account/password.js
  app/controllers/account/profile.js
  app/controllers/admin/users.js
  app/controllers/admin/users/view/account/contact-info.js
  app/router.js
  app/routes/account.js
  app/routes/account/applications.js
  app/routes/account/contact-info.js
  app/routes/account/danger-zone.js
  app/routes/account/email-preferences.js
  app/routes/account/index.js
  app/routes/account/password.js
  app/routes/account/profile.js
  app/routes/admin/users/view/account/applications.js
  app/routes/admin/users/view/account/contact-info.js
  app/routes/admin/users/view/account/email-preferences.js
  app/templates/account.hbs
  app/templates/account/applications.hbs
  app/templates/account/contact-info.hbs
  app/templates/account/danger-zone.hbs
  app/templates/account/email-preferences.hbs
  app/templates/account/password.hbs
  app/templates/account/profile.hbs
  app/templates/admin/users/view/account.hbs
  app/templates/admin/users/view/account/applications.hbs
  app/templates/admin/users/view/account/contact-info.hbs
  app/templates/admin/users/view/account/email-preferences.hbs
  app/templates/admin/users/view/settings/applications.hbs
  app/templates/admin/users/view/settings/contact-info.hbs
  app/templates/admin/users/view/settings/email-preferences.hbs
  app/templates/components/account/application-section.hbs
  app/templates/components/account/contact-info-section.hbs
  app/templates/components/account/danger-zone.hbs
  app/templates/components/account/email-preferences-section.hbs
  app/templates/components/account/password-section.hbs
  app/templates/components/nav-bar.hbs
  app/templates/components/side-bar.hbs
  app/templates/components/ui-table/cell/admin/users/cell-user-links.hbs
  app/templates/settings/applications.hbs
  app/templates/settings/contact-info.hbs
  app/templates/settings/danger-zone.hbs
  app/templates/settings/email-preferences.hbs
  app/templates/settings/password.hbs
  tests/acceptance/profile-test.js
  tests/acceptance/settings-test.js
  tests/integration/components/account/application-page-test.js
  tests/integration/components/account/contact-info-test.js
  tests/integration/components/account/email-preferences-test.js
  tests/integration/components/account/password-page-test.js
Labels: enhancement

#3121 feat: company data possible to be added without ticking 'Send tax invoice'
  app/templates/components/modals/tax-info-modal.hbs
Labels: feature

#3109 feat: URL Trimming for Twitter URL
  app/components/forms/session-speaker-form.js
  app/models/speaker.js
  app/templates/components/forms/session-speaker-form.hbs
Labels: feature

#3123 feat: Pagination and redirection to `Explore` in mobile view
  app/routes/explore.js
  app/templates/components/side-bar.hbs
  app/templates/explore.hbs
Labels: feature

#3104 fix: Resolve Attendee Checkin/Checkout 422 error.
  app/controllers/events/view/tickets/attendees/list.js
  app/routes/events/view/tickets/attendees/list.js
Labels: fix

#3111 feat: add placed orders in sold ticket stats
  app/controllers/events/view/tickets/index.js
  app/routes/events/view/tickets/index.js
  app/templates/components/ui-table/cell/cell-tickets.hbs
  app/templates/events/view/tickets/index.hbs
Labels: feature

#3042 fix: Less Table Space Consumption and Fixing Loose Tables on Small Screen
  app/templates/components/events/view/overview/event-tickets.hbs
  app/templates/components/events/view/overview/manage-roles.hbs
  app/templates/events.hbs
  app/templates/events/view/tickets/index.hbs
  app/themes/semantic.js
Labels: fix

#3137 feat: toggle filters in mobile devices
  app/components/explore/side-bar.js
  app/templates/components/explore/side-bar.hbs
Labels: feature

#3091 fix: Restructure and update role-invite flow
  app/routes/public/role-invites.js
Labels: Priority: Urgent, fix

#3148 fix: Wait for the app to settle after login and logout.
  tests/helpers/custom-helpers.js
Labels: fix

#3150 feat: Populate searchableLocationName with event location:
  app/components/widgets/forms/location-input.js
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: feature

#3151 fix: add placed orders in tickets overview
  app/components/events/view/overview/event-tickets.js
  app/templates/components/events/view/overview/event-tickets.hbs
  tests/integration/components/events/view/overview/event-tickets-test.js
Labels: fix

#3146 feat: Merged contact module with profile
  app/components/forms/user-profile-form.js
  app/controllers/account/contact-info.js
  app/controllers/account/profile.js
  app/router.js
  app/routes/account/contact-info.js
  app/routes/account/index.js
  app/templates/account.hbs
  app/templates/account/contact-info.hbs
  app/templates/account/profile.hbs
  app/templates/admin/users/view/account.hbs
  app/templates/components/forms/user-profile-form.hbs
  app/templates/components/side-bar.hbs
  tests/acceptance/settings-test.js
Labels: feature

#3069 feat: Added support for donation tickets
  app/models/ticket.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: feature

#3167 fix: Title Token & Implemented mixin for billing route
  app/routes/account/billing-info.js
  tests/acceptance/billing-info-test.js
  tests/acceptance/invoices-test.js
  tests/acceptance/payment-info-test.js
Labels: fix

#2961 feat: Add new wizard step - attendee form
  app/components/forms/wizard/attendee-step.js
  app/controllers/create.js
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/edit/basic-details.js
  app/controllers/events/view/edit/sponsors.js
  app/mixins/event-wizard.js
  app/models/event.js
  app/router.js
  app/routes/events/view/edit/attendee.js
  app/templates/components/forms/wizard/attendee-step.hbs
  app/templates/events/view/edit/attendee.hbs
Labels: feature

#3047 feat: Alipay backend connect using loader & icon resize.
  app/controllers/orders/pending.js
  app/models/setting.js
  public/images/payment-logos/alipay.png
Labels: feature

#3017 feat: adds star rating to events/view/sessions
  app/components/ui-table/cell/events/view/sessions/cell-rating.js
  app/controllers/events/view/sessions/list.js
  app/models/feedback.js
  app/models/session.js
  app/routes/events/view/sessions/list.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-rating.hbs
  app/templates/events/view/sessions/list.hbs
Labels: feature

#3102 feat: Filter Side Bar Enhancements
  app/components/explore/side-bar.js
  app/components/side-bar.js
  app/templates/components/explore/side-bar.hbs
Labels: feature

#3178 fix: Increasing Column Width of Price Section
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: fix

#3078 feat: show tax information on public ticket page
  app/components/public/ticket-list.js
  app/controllers/public/index.js
  app/models/ticket.js
  app/routes/public/index.js
  app/templates/components/public/ticket-list.hbs
  app/templates/public/index.hbs
  tests/integration/components/public/ticket-list-test.js
Labels: feature

#3191 feat: Add attendee form step in event checklist
  app/templates/components/events/view/overview/event-setup-checklist.hbs
Labels: feature

#3185 fix: Making Ticket Buttons Inline
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#3190 feat: Adding general description of attendee form
  app/templates/components/forms/wizard/attendee-step.hbs
Labels: feature

#3205 fix: Orientation of Ticket Input
  app/templates/components/public/ticket-list.hbs
Labels: fix

#3217 fix: Preventing Overflow
  app/templates/components/modals/tax-info-modal.hbs
Labels: fix

#3193 fix: Wrong route defined in user accounts for admin
  app/controllers/admin/users.js
  app/templates/admin/users/view/account.hbs
  app/templates/components/ui-table/cell/admin/users/cell-user-links.hbs
Labels: fix

#3218 fix: Unmute order details text
  app/templates/components/forms/orders/attendee-list.hbs
Labels: fix

#3213 enh: changing status route to invoice
  app/controllers/admin/sales/invoices.js
  app/router.js
  app/routes/admin/sales/invoices.js
  app/templates/admin/sales.hbs
  app/templates/admin/sales/invoices.hbs
Labels: enhancement
