Repository fossasia/open-event-frontend, pull requests merged in 2019-11, with the labels that each got.

#3586 fix: Increase page[size] to render all form fields.
  app/routes/public/cfs/new-speaker.js
Labels: fix

#3545 fix: changed variable "name" to "event_name"
  app/controllers/index.js
Labels: fix

#3551 fix: Dropdown in Add Order section Fixed
  app/templates/components/ui-table.hbs
Labels: fix

#3591 chore(deps): Updating caniuse and related dependecnies
  yarn.lock
Labels: chore, dependencies

#3600 chore: comment out custom form widget
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: chore

#3593 fix: Ticket dashboard table css overflow on small screens
  app/templates/components/tables/utilities/search-box.hbs
  app/templates/events/view/tickets/index.hbs
Labels: fix

#3606 fix: Correcting the routes for my-session
  app/templates/my-sessions/view.hbs
Labels: fix

#3619 chore: Migrate my-session, ticket and billing forms to ES6
  app/components/forms/admin/settings/billing.js
  app/components/forms/user-payment-info-form.js
  app/controllers/my-sessions/view.js
  app/controllers/my-tickets/past.js
  app/controllers/my-tickets/upcoming.js
Labels: chore

#3610 fix: show "more call for speaker" button when appropriate
  app/templates/index.hbs
Labels: fix

#3624 fix: front-end deployment link
  README.md
Labels: fix

#3614 fix: ticketing system buttons alignment
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#3601 fix: fixing weird vertical shift in event dashboard
  app/templates/events/view.hbs
Labels: fix

#3536 fix: adding id to all notify objects in the webapp
  app/controllers/account/password.js
  app/controllers/account/profile.js
  app/controllers/admin/content/events.js
  app/controllers/admin/content/index.js
  app/controllers/admin/content/pages.js
  app/controllers/admin/content/translations.js
  app/controllers/admin/events/list.js
  app/controllers/admin/messages.js
  app/controllers/admin/modules.js
  app/controllers/admin/permissions/event-roles.js
  app/controllers/admin/permissions/system-roles.js
  app/controllers/admin/sessions/list.js
  app/controllers/admin/settings/analytics.js
  app/controllers/admin/settings/billing.js
  app/controllers/admin/settings/images.js
  app/controllers/admin/settings/index.js
  app/controllers/admin/settings/microservices.js
  app/controllers/admin/settings/payment-gateway.js
  app/controllers/admin/settings/ticket-fees.js
  app/controllers/admin/users/list.js
  app/controllers/event-invoice/paid.js
  app/controllers/events/list.js
  app/controllers/events/view.js
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/export.js
  app/controllers/events/view/index.js
  app/controllers/events/view/scheduler.js
  app/controllers/events/view/sessions.js
  app/controllers/events/view/sessions/create.js
  app/controllers/events/view/sessions/edit.js
  app/controllers/events/view/sessions/list.js
  app/controllers/my-sessions/view.js
  app/controllers/notifications.js
  app/controllers/orders/new.js
  app/controllers/orders/pending.js
  app/controllers/orders/view.js
  app/controllers/public/cfs/edit-session.js
  app/controllers/public/cfs/edit-speaker.js
  app/controllers/public/cfs/new-session.js
  app/controllers/public/cfs/new-speaker.js
Labels: fix

#3633 fix: Send event startsAt and endsAt time in event timezone
  app/utils/computed-helpers.js
Labels: fix

#3646 feat: Add debounce on search field and remove included resources
  app/components/tables/utilities/search-box.js
  app/controllers/admin/events/list.js
  app/controllers/events/list.js
  app/routes/admin/events/list.js
  app/routes/events/list.js
  app/templates/components/tables/utilities/search-box.hbs
Labels: feature

#3649 fix: Removing unnecessary include and queries
  app/controllers/admin/users/view/events/list.js
  app/routes/admin/users/view/events/list.js
Labels: fix

#3629 fix: remove blue background from export drop-down
  app/templates/events/view/tickets/orders.hbs
Labels: fix

#3567 fix: added check for required-fields and rendering gender
  app/helpers/is-input-field.js
Labels: fix

#3660 fix: Changing tab order and routes
  app/routes/admin/events/index.js
  app/templates/admin/events.hbs
Labels: fix

#3670 fix: Removing isTicketingEnabled from events
  app/models/event.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/public/index.hbs
Labels: fix

#3654 feat: Billing Information Enhancements and Updations
  app/components/forms/orders/order-form.js
  app/models/event.js
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/widgets/forms/billing-info.hbs
  app/templates/orders/new.hbs
Labels: feature

#3672 fix: Remove date and time validations
  app/components/forms/events/view/create-discount-code.js
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/sessions-speakers-step.js
Labels: fix
