Repository fossasia/open-event-frontend, pull requests merged in 2019-08, with the labels that each got.

#3341 fix: allow decimal values for ticket prices
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#3344 fix: change button positions and take out repeating buttons
  app/templates/orders/pending.hbs
Labels: fix

#3317 feat: Implementation of review route for event invoice payment
  app/router.js
  app/routes/event-invoice/review.js
  app/templates/event-invoice/review.hbs
Labels: feature

#3352 feat: Implement a tick box for organizers/admin to override Email
  app/controllers/events/view/sessions/create.js
  app/controllers/events/view/sessions/edit.js
  app/controllers/events/view/speakers/create.js
  app/controllers/events/view/speakers/edit.js
  app/models/speaker.js
  app/templates/components/forms/session-speaker-form.hbs
Labels: feature

#3361 fix: profile picture link to null when removed
  app/components/widgets/forms/image-upload.js
  app/templates/components/forms/user-profile-form.hbs
Labels: fix

#3198 feat: introduce new columns for session ratings & switch to ember table
  app/controllers/events/view/sessions/list.js
  app/models/user.js
  app/routes/events/view/sessions/list.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-is-mail-sent.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-lock-session.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-rating.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs
  app/templates/events/view/sessions/list.hbs
Labels: feature

#3369 fix: Added missing validation for country
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#3373 fix: fix broken google analytics in fastboot
  package.json
  yarn.lock
Labels: fix

#3371 feat: add paytm credentials and setup in admin/settings
  app/components/forms/admin/settings/payment-gateway-form.js
  app/models/setting.js
  app/templates/components/forms/admin/settings/payment-gateway-form.hbs
Labels: feature

#3350 feat: implementation of paid route for event invoices
  app/router.js
  app/routes/event-invoice/paid.js
  app/templates/components/event-invoice/billing-info.hbs
  app/templates/components/event-invoice/event-info.hbs
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/components/event-invoice/payee-info.hbs
  app/templates/event-invoice/paid.hbs
Labels: feature

#3340 feat: Introducing Ember Tables in Admin/Messages
  app/controllers/admin/messages/list.js
  app/routes/admin/messages/list.js
  app/templates/admin/messages/list.hbs
  app/templates/components/ui-table/cell/admin/messages/cell-options.hbs
  app/templates/components/ui-table/cell/cell-title-message.hbs
Labels: feature

#3381 feat: add paytm accepted currencies
  app/utils/dictionary/payment.js
Labels: feature

#3378 fix: phone number compulsory field remove
  app/components/forms/user-profile-form.js
Labels: fix

#3385 fix: fix isPaytmActivated attribute save
  app/templates/components/forms/admin/settings/payment-gateway-form.hbs
Labels: fix

#3305 fix: Restrict event save when information is insufficient
  app/mixins/event-wizard.js
Labels: fix

#3230 feat: Implemented event invoice table for organizers
  app/controllers/account/billing/invoices.js
  app/controllers/account/billing/invoices/list.js
  app/models/event-invoice.js
  app/router.js
  app/routes/account/billing/invoices/list.js
  app/templates/account/billing/invoices.hbs
  app/templates/account/billing/invoices/list.hbs
  app/templates/components/ui-table/cell/events/cell-event-invoice.hbs
  tests/acceptance/billing-info-test.js
Labels: feature

#3387 fix: add google re-captcha keys in setting model
  app/models/setting.js
  app/templates/components/forms/admin/settings/system/captcha-form.hbs
Labels: fix

#3266 fix: Showing Draft Button for Step-3 & 4
  app/templates/components/forms/wizard/attendee-step.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/forms/wizard/sponsors-step.hbs
Labels: fix

#3280 feat: Order Summary making similar to EventBrite
  app/templates/components/orders/order-summary.hbs
Labels: feature

#3251 feat: implement resend email confirmation button
  app/controllers/events/view/tickets/orders/list.js
  app/services/loader.js
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/events/view/tickets/orders/list.hbs
  tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-order-test.js
Labels: feature

#3392 feat: Addition of stripe test client id
  app/components/forms/admin/settings/payment-gateway-form.js
  app/models/setting.js
  app/templates/components/forms/admin/settings/payment-gateway-form.hbs
Labels: DO-NOT-MERGE, blocked-by-server, feature

#3403 feat: implement a method for reloading model for tables
  app/initializers/blanket.js
  app/mixins/ember-table-controller.js
Labels: feature

#3404 feat: implement ember table for tickets/orders table
  app/controllers/events/view/tickets/orders/list.js
  app/routes/events/view/tickets/orders/list.js
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/events/view/tickets/orders/list.hbs
  tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-amount-test.js
  tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-order-test.js
Labels: feature

#3396 fix: event invoice table 'all' filter displays invoices
  app/controllers/account/billing/invoices/list.js
  app/routes/account/billing/invoices/index.js
  app/templates/components/ui-table/cell/events/cell-amount.hbs
Labels: fix

#3402 feat: link invoices to respective pages
  app/controllers/account/billing/invoices/list.js
  app/templates/components/ui-table/cell/events/cell-action.hbs
Labels: feature

#3412 feat: add try catch block to await in application route
  app/routes/application.js
Labels: feature

#3416 feat: use ember table for tickets/attendees
  app/controllers/events/view/tickets/attendees/list.js
  app/routes/events/view/tickets/attendees/list.js
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-action.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-price.hbs
  app/templates/events/view/tickets/attendees/list.hbs
  tests/integration/components/ui-table/cell/events/view/tickets/attendees/cell-order-test.js
  tests/integration/components/ui-table/cell/events/view/tickets/attendees/cell-price-test.js
Labels: feature

#3422 feat: access-code & discount-code ember tables
  app/controllers/events/view/tickets/access-codes/list.js
  app/controllers/events/view/tickets/discount-codes/list.js
  app/routes/events/view/tickets/access-codes/list.js
  app/routes/events/view/tickets/discount-codes/list.js
  app/templates/components/ui-table/cell/cell-label.hbs
  app/templates/components/ui-table/cell/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-actions.hbs
  app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-url.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-status.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-url.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-value.hbs
  app/templates/events/view/tickets/access-codes/list.hbs
  app/templates/events/view/tickets/discount-codes/list.hbs
  tests/integration/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions-test.js
Labels: feature

#3423 fix: avoid multiple success message in accounts
  app/components/forms/user-payment-info-form.js
Labels: fix

#3424 feat: add invoice download action
  app/controllers/event-invoice/paid.js
Labels: feature

#3414 fix: event invoice fetched correctly in review route
  app/routes/event-invoice/paid.js
  app/routes/event-invoice/review.js
  app/templates/event-invoice/review.hbs
Labels: fix

#3410 fix: tickets fetched at each step of wizard
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/edit/sessions-speakers.js
  app/controllers/events/view/edit/sponsors.js
  app/mixins/event-wizard.js
Labels: fix

#3351 feat: integrated payment component for event invoice
  app/components/paypal-button.js
  app/templates/event-invoice/review.hbs
  app/templates/orders/pending.hbs
Labels: feature

#3363 feat: Introducing Ember Tables in Event Dashboard
  app/controllers/events/view/index.js
  app/routes/events/view/index.js
  app/templates/components/events/view/overview/event-sponsors.hbs
  app/templates/components/ui-table/cell/cell-sponsor-image.hbs
  app/templates/components/ui-table/cell/cell-sponsor-options.hbs
  app/templates/components/ui-table/cell/cell-sponsor-sanitize.hbs
  app/templates/events/view/index.hbs
  tests/integration/components/ui-table/cell/cell-sponsor-options-test.js
Labels: feature

#3443 fix: pagination, searching, sorting in events/session table
  app/controllers/events/view/sessions/list.js
  app/routes/events/view/sessions/list.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-rating.hbs
  app/templates/events/view/sessions/list.hbs
Labels: fix

#3448 fix: uses refreshModel to refresh session table after an action
  app/controllers/events/view/sessions/list.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs
Labels: fix

#3400 feat: add paytm to create event and order-form page
  app/components/forms/wizard/basic-details-step.js
  app/controllers/orders/pending.js
  app/models/event.js
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  public/images/payment-logos/paytm.png
Labels: feature

#3455 fix: Saving stripe client test id
  app/models/setting.js
Labels: fix

#3458 fix: add sort options to admin sessions
  app/controllers/admin/sessions/list.js
Labels: fix

#3463 feat: add static domain fields to admin settings
  app/components/forms/admin/settings/system-form.js
  app/models/setting.js
  app/templates/components/forms/admin/settings/system-form.hbs
Labels: feature

#3447 feat: Design PayTM gateway modals
  app/components/modals/paytm-otp.js
  app/components/modals/paytm-payment-options.js
  app/controllers/orders/pending.js
  app/templates/components/modals/paytm-otp.hbs
  app/templates/components/modals/paytm-payment-options.hbs
  app/templates/orders/pending.hbs
Labels: feature

#3465 fix: Fixed alipay workflow & naming
  app/components/forms/wizard/basic-details-step.js
  app/controllers/orders/pending.js
  app/models/event.js
  app/models/setting.js
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/orders/pending.hbs
Labels: fix

#3474 fix: Solving Ticket Sales ambiguity
  app/templates/events/view/tickets/index.hbs
Labels: fix

#3491 fix: omise image optimisation
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#3490 fix: Problem with time selector after TimeZone
  app/components/forms/wizard/basic-details-step.js
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#3473 fix: pagination/searching/sorting in billing invoice table
  app/controllers/account/billing/invoices/list.js
  app/routes/account/billing/invoices/list.js
  app/templates/account/billing/invoices/list.hbs
Labels: fix

#3469 test: add integration tests for paytm modals
  tests/integration/components/modals/paytm-otp-test.js
  tests/integration/components/modals/paytm-payment-options-test.js
Labels: tests

#3429 fix: Using ember tables for Admin/Sales/Invoices
  app/controllers/admin/sales/invoices.js
  app/routes/admin/sales/invoices.js
  app/templates/admin/sales/invoices.hbs
  app/templates/components/ui-table/cell/admin/sales/status/cell-amount.hbs
  app/templates/components/ui-table/cell/admin/sales/status/cell-dated.hbs
  tests/integration/components/ui-table/cell/admin/sales/status/cell-dated-test.js
Labels: fix
