Repository fossasia/open-event-frontend, pull requests merged in 2019-05, with the labels that each got.

#2924 feat: ability to delete user's account by himself/herself
  app/components/modals/confirm-user-delete-modal.js
  app/components/modals/user-delete-modal.js
  app/components/settings/danger-zone.js
  app/router.js
  app/routes/settings/danger-zone.js
  app/templates/components/modals/confirm-user-delete-modal.hbs
  app/templates/components/modals/user-delete-modal.hbs
  app/templates/components/settings/danger-zone.hbs
  app/templates/settings.hbs
  app/templates/settings/danger-zone.hbs
Labels: feature

#2941 feat: Add delay to printing of invoice
  app/controllers/orders/view.js
Labels: feature

#2942 feat: Set up automated docker deploy
  Dockerfile
  hooks/build
Labels: feature

#2943 fix: adds date and time column to organizer dashboard ticket section
  app/components/ui-table/cell/events/view/tickets/orders/cell-date.js
  app/controllers/events/view/tickets/orders/list.js
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-date.hbs
Labels: fix

#2948 fix: Save user details in order confirmation step
  app/controllers/orders/new.js
Labels: fix

#2962 Refactor: Update model hooks and parse event currency where required.
  app/components/forms/events/view/create-discount-code.js
  app/routes/events/view/tickets/discount-codes/create.js
  app/templates/components/events/view/overview/event-tickets.hbs
  app/templates/components/forms/events/view/create-discount-code.hbs
  app/templates/events/view/tickets/discount-codes/create.hbs
  tests/integration/components/events/view/overview/event-tickets-test.js
Labels: WIP

#2950 feat: Reorder action buttons in Event/Orders
  app/controllers/events/view/tickets/orders/list.js
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-actions.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-actions-test.js
  tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-order-test.js
Labels: feature

#2969 fix: Event location display on landing page
  app/models/event.js
Labels: fix

#2982 feat: Add instagram & address fields to speaker custom-forms
  app/mixins/custom-form.js
  app/models/custom-form.js
Labels: feature

#2916 feat: Added tax to order checkout page
  app/controllers/public/index.js
  app/routes/orders/new.js
  app/routes/orders/view.js
  app/routes/public.js
  app/templates/components/orders/order-summary.hbs
  app/templates/orders/new.hbs
  app/templates/orders/placed.hbs
  app/templates/orders/view.hbs
Labels: feature

#2984 fix: amend broken order tax flow
  app/controllers/public/index.js
  app/models/event.js
  app/routes/orders/new.js
  app/routes/orders/placed.js
  app/routes/orders/view.js
  app/templates/components/orders/order-summary.hbs
Labels: fix

#2986 fix: display of pre-existing event tax details in edit wizard
  app/components/forms/wizard/basic-details-step.js
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#2979 feat: Addition of landing page for Mobile Application
  app/router.js
  app/templates/attendee-app.hbs
  app/templates/components/footer-main.hbs
  app/templates/organizer-app.hbs
  public/images/android-img.jpg
  public/images/attendee-app.jpg
  public/images/fdroid.png
  public/images/google-play.png
  public/images/organizer-android.jpg
  public/images/organizer-app.jpg
  tests/acceptance/attendee-app-test.js
  tests/acceptance/organizer-app-test.js
Labels: feature

#2990 fix: Disabling Save Draft on basis of event state
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/forms/wizard/sponsors-step.hbs
Labels: fix

#2983 fix: Linking Order Invoice Download to server route
  app/controllers/orders/view.js
  app/templates/orders/view.hbs
Labels: fix

#2964 feat: redesigns sessions page and add lock/unlock column
  app/components/ui-table/cell/events/view/sessions/cell-lock-session.js
  app/components/ui-table/cell/events/view/sessions/cell-session-title.js
  app/controllers/events/view/sessions/list.js
  app/models/session.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-lock-session.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs
  app/templates/events/view/sessions/list.hbs
  app/templates/my-sessions/view.hbs
Labels: feature

#2955 fix: updates the status for orders
  app/components/paypal-button.js
  app/controllers/orders/new.js
  app/controllers/orders/pending.js
  app/models/order.js
  app/router.js
  app/routes/orders/expired.js
  app/routes/orders/new.js
  app/routes/orders/pending.js
  app/routes/orders/view.js
  app/templates/components/orders/order-summary.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/orders/pending.hbs
Labels: DO-NOT-MERGE, fix

#3002 fix: Show pending orders in my tickets section
  app/routes/my-tickets/upcoming/list.js
Labels: fix

#3007 chore: Restore livereload in app
  package.json
  yarn.lock
Labels: chore

#3021 fix: Disabling the addition of one extra day in EndAtDate
  app/utils/computed-helpers.js
Labels: fix

#3032 fix: broken scheduler
  app/controllers/events/view/scheduler.js
Labels: fix

#3029 fix: Speakers Call Page fix
  app/routes/public/cfs/index.js
Labels: fix

#2980 fix: add a popup for new cfs speakers as a message
  app/components/create-session-message.js
  app/templates/components/create-session-message.hbs
  app/templates/components/public/call-for-speakers.hbs
  tests/integration/components/create-session-message-test.js
Labels: fix

#3038 feat: Show appropriate currency in stripe checkout
  app/templates/orders/pending.hbs
Labels: feature

#3031 fix: Replaced a static Google Map component with a dynamic one
  app/components/explore/side-bar.js
  app/templates/components/explore/side-bar.hbs
Labels: fix

#3040 fix: fixed rejected promise for cfs(unauthenticated users)
  app/components/create-session-message.js
Labels: fix
