Repository fossasia/open-event-frontend, pull requests merged in 2020-11, with the labels that each got.

#5369 fix: Show "Free" instead of $0.00 in ticket price
  app/templates/components/orders/order-summary.hbs
  app/templates/components/orders/ticket-price.hbs
  app/templates/components/public/ticket-list.hbs
  tests/integration/components/orders/ticket-price-test.ts
Labels: fix

#5415 fix: call for speaker page messages
  app/templates/components/public/call-for-speakers.hbs
Labels: fix

#5454 fix: simply nav bar on public page
  app/components/nav-bar.js
  app/templates/components/nav-bar.hbs
Labels: fix

#5467 fix: Show Social Links only on Event Pages that are listed on the left side bar
  app/templates/public.hbs
Labels: fix

#5464 fix: Remove Empty Spaces between Boxes in Event Dashboard Page
  app/templates/events/view/index.hbs
Labels: fix

#5139 fix: Partially enhance event dashboard
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/components/public/social-links.hbs
Labels: fix

#5471 fix: Reorder and rename event dashboard boxes
  app/templates/components/events/view/overview/event-setup-checklist.hbs
  app/templates/components/events/view/overview/event-sponsors.hbs
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/events/view/index.hbs
Labels: fix

#5480 fix: Removed unneccesary line breaks in event title
  app/templates/events/view.hbs
Labels: fix

#5440 feat: Add to Calendar - iCal
  app/components/public/add-to-calender.hbs
  app/components/public/add-to-calender.ts
  app/services/loader.js
  app/styles/partials/utils.scss
Labels: feature

#5487 chore: Update translations and l10n commands
  .travis.yml
  Dockerfile
  README.md
  docs/installation/local.md
  package.json
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#5488 chore: Fix l10n:generate command
  package.json
Labels: chore

#5489 chore: Translated using Weblate (German)
  translations/de.po
Labels: chore

#5447 fix: Hide currency when amount is 0
  app/templates/components/currency-amount.hbs
  app/templates/components/events/view/overview/event-tickets.hbs
  app/templates/components/orders/ticket-price.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-price.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-value.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs
  app/templates/events/view/tickets/index.hbs
  tests/integration/components/currency-amount-test.js
Labels: fix

#5498 chore: Translated using Weblate (French)
  translations/fr.po
Labels: chore

#5500 chore: Translations update from Weblate (French)
  translations/fr.po
Labels: chore

#5502 chore: console log more errors
  app/controllers/events/view.js
  app/controllers/events/view/index.js
  app/controllers/events/view/scheduler.js
  app/controllers/events/view/sessions.js
  app/controllers/events/view/sessions/create.js
  app/controllers/events/view/sessions/edit.js
  app/controllers/events/view/settings.js
  app/controllers/events/view/speakers.js
  app/controllers/events/view/speakers/create.js
  app/controllers/events/view/speakers/edit.js
  app/controllers/events/view/speakers/list.js
  app/controllers/events/view/tickets/access-codes/list.js
  app/controllers/events/view/tickets/attendees.js
  app/controllers/events/view/tickets/attendees/list.js
  app/controllers/events/view/tickets/discount-codes/list.js
  app/controllers/events/view/tickets/order-form.js
  app/controllers/events/view/tickets/orders.js
  app/controllers/events/view/tickets/orders/list.js
Labels: chore

#5504 fix: remove intermidiate step of login while registering
  app/controllers/register.js
Labels: fix

#5508 fix: Brackets and commas spacing
  app/templates/attendee-app.hbs
  app/templates/components/events/view/overview/manage-roles.hbs
  app/templates/components/forms/admin/settings/images-form.hbs
  app/templates/components/forms/admin/settings/payment-gateway-form.hbs
  app/templates/components/forms/events/view/create-access-code.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/organizer-app.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: fix

#5429 feat: adding ember leaflet
  app/components/public/event-map.js
  app/styles/components/extras.scss
  app/templates/components/public/event-map.hbs
  ember-cli-build.js
  package.json
  yarn.lock
Labels: feature

#5330 chore: Add Video Stream models
  .eslintrc.js
  app/models/microlocation.ts
  app/models/video-stream.ts
  app/serializers/video-stream.ts
  package.json
  tests/unit/models/video-stream-test.ts
  yarn.lock
Labels: chore

#5486 fix: Refresh model after speaker deletion
  app/controllers/events/view/speakers/list.js
Labels: fix

#5514 fix: Standardize width of footer
  app/templates/components/footer-main.hbs
Labels: fix

#5387 fix: cfs speaker edit properly after cfs is closed
  app/routes/public/cfs/index.js
Labels: fix

#5524 chore: Translations update from Weblate
  translations/id.po
Labels: chore

#5528 chore: Upgrade to node 14.x
  .travis.yml
  Dockerfile
  netlify.toml
  package.json
Labels: chore

#5532 fix: Display sponsor size according to their level
  app/components/public/sponsor-item.hbs
  app/components/public/sponsor-item.js
  app/components/public/sponsor-list.hbs
  app/components/public/sponsor-list.js
  app/components/public/sponsor-list.ts
  app/controllers/register.js
  app/templates/components/public/sponsor-list.hbs
Labels: fix

#5535 fix: Correctly load detected moment locales
  app/services/l10n.js
Labels: fix

#5545 chore: Approve dependabot PRs
  .github/workflows/dependabot-approve.yml
Labels: chore

#5373 feat: Implement new link field
  app/components/forms/wizard/other-details-step.js
  app/components/widgets/forms/link-field.hbs
  app/components/widgets/forms/link-field.ts
  app/components/widgets/forms/link-input.js
  app/components/widgets/forms/social-link-field.hbs
  app/components/widgets/forms/social-link-field.ts
  app/models/social-link.js
  app/styles/partials/utils.scss
  app/templates/components/forms/wizard/other-details-step.hbs
  app/utils/computed-helpers.js
  app/utils/dictionary/social-media.ts
  tests/integration/components/widgets/forms/link-field-test.ts
  tests/integration/components/widgets/forms/social-link-field-test.ts
Labels: feature

#5529 feat: Integrate web app generator with event dashboard
  app/components/events/view/overview/event-apps.js
  app/templates/components/events/view/overview/event-apps.hbs
  app/templates/events/view/index.hbs
  config/environment.js
  docs/installation/local.md
  tests/integration/components/events/view/overview/event-apps-test.js
Labels: feature

#5554 fix: Show social media names properly
  app/models/social-link.js
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/components/public/social-links.hbs
Labels: fix

#5552 chore: Upgrade yarn.lock for shelljs
  yarn.lock
Labels: chore

#5517 fix: Update notification messages for verifying account
  app/components/unverified-user-message.hbs
  app/templates/verify.hbs
  tests/integration/components/unverified-user-message-test.js
Labels: fix

#5557 fix: attendee page search
  app/routes/events/view/tickets/attendees/list.js
Labels: fix

#5556 fix: Improper Alignment of Order Now alert box
  app/templates/components/forms/orders/guest-order-form.hbs
  app/templates/components/modals/login-signup-modal.hbs
Labels: fix

#5561 fix: Order Page: Remove empty spaces
  app/styles/partials/overrides.scss
  app/templates/components/orders/order-summary.hbs
  app/templates/orders/view.hbs
Labels: fix

#5569 fix: Mobile: Substitute Create Event with Login
  app/templates/components/nav-bar.hbs
Labels: fix

#5541 feat: Added options for Outlook, Yahoo to add to calendar
  app/components/public/add-to-calender.ts
Labels: feature

#5568 fix: Footer use same width as above tiles in mobile view
  app/templates/components/footer-main.hbs
Labels: fix

#5576 fix: move custom fields in attendee form in the end
  app/components/forms/wizard/attendee-step.js
Labels: fix

#5582 chore: Disable CSS sourcemaps in prod
  ember-cli-build.js
Labels: chore

#5562 fix: Admin panel member since changed to date
  app/controllers/admin/users/list.js
Labels: fix

#5586 fix: Keep number of sponsor columns constant
  app/components/public/sponsor-list.hbs
Labels: fix

#5583 fix: don't cfs filter when cfs is disabled
  app/components/forms/wizard/sessions-speakers-step.js
  app/routes/index.js
Labels: fix

#5595 fix: No error shown when image upload fails
  app/components/widgets/forms/image-upload.js
Labels: fix

#5597 fix: Handle www and value changes in link-field
  app/components/widgets/forms/link-field.hbs
  app/components/widgets/forms/link-field.ts
  app/models/social-link.js
  app/templates/components/forms/wizard/other-details-step.hbs
  app/utils/dictionary/social-media.ts
Labels: fix

#5605 fix: Show correct type for custom social link
  app/templates/components/forms/wizard/other-details-step.hbs
Labels: fix

#5613 chore: Preload fonts in HTML
  app/index.html
Labels: chore

#5606 fix: Get rid of unsed spaces between boxes in templates of the order page
  app/templates/orders/new.hbs
Labels: fix

#5591 feat: Ticket pre-selected for 1 type of tickets
  app/components/public/ticket-list.js
  app/templates/components/public/ticket-list.hbs
Labels: feature

#5621 fix: Change position of Paypal/Pay Now Button
  app/templates/orders/pending.hbs
Labels: fix

#5630 fix: change the icon of the Acknowledgement
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#5617 fix: Order Page and Completed Order Page: Change "Go to event"
  app/templates/components/orders/event-info.hbs
Labels: fix

#5620 fix: Show Location, Online Event, Mixed Event or To be Announced info correctly
  app/templates/components/orders/event-info.hbs
Labels: fix

#5646 fix: change the billing information icon
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#5651 fix: Move and simplify "Event Types"
  app/styles/vars.scss
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#5671 fix: Add status "Withdrawn" and "canceled" into sessions and speakers column
  app/models/event-statistics-general.js
  app/serializers/event-statistics-general.js
  app/templates/components/ui-table/cell/cell-sessions-dashboard.hbs
  app/templates/components/ui-table/cell/cell-speakers-dashboard.hbs
Labels: fix

#5672 fix: Adjust table in Organizers Attendees Overview Page
  app/controllers/events/view/tickets/attendees/list.js
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
Labels: fix

#5673 fix: Show full name and remove date and time in Organizer Orders Overview Page
  app/controllers/events/view/tickets/orders/list.js
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
Labels: fix

#5679 fix: up to 12 events should be listed in cfs
  app/routes/index.js
Labels: fix

#5681 fix: Match color of activated "Event Types" boxes to other boxes
  app/styles/vars.scss
Labels: fix

#5685 chore: remove deprecated sendAction()
  app/components/account/contact-info-section.js
  app/components/account/password-section.js
  app/components/forms/admin/content/pages-form.js
  app/components/forms/admin/content/social-links-form.js
  app/components/forms/admin/settings/analytics-form.js
  app/components/forms/admin/settings/images-form.js
  app/components/forms/admin/settings/microservices-form.js
  app/components/forms/admin/settings/payment-gateway-form.js
  app/components/forms/admin/settings/system-form.js
  app/components/forms/events/view/create-access-code.js
  app/components/forms/events/view/create-discount-code.js
  app/components/forms/events/view/edit-session.js
  app/components/forms/orders/order-form.js
  app/components/forms/register-form.js
  app/components/forms/session-speaker-form.js
  app/components/modals/add-system-role-modal.js
  app/components/modals/add-user-role-modal.js
  app/components/modals/admin/content/new-event-sub-topic-modal.js
  app/components/modals/admin/content/new-event-topic-modal.js
  app/components/modals/admin/content/new-event-type-modal.js
  app/components/modals/confirm-event-transfer-modal.js
Labels: chore

#5270 feat: Virtual room creation
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/modals/add-room-modal.hbs
  app/components/modals/add-room-modal.js
  app/components/modals/modal-base.js
  app/components/modals/room-info-modal.js
  app/components/ui-table/cell/events/view/videoroom/cell-additional-info.js
  app/components/ui-table/cell/events/view/videoroom/cell-video-url.js
  app/controllers/events/view/videoroom.js
  app/controllers/events/view/videoroom/create.js
  app/controllers/events/view/videoroom/edit.js
  app/controllers/events/view/videoroom/list.js
  app/router.js
  app/routes/events/view/videoroom.js
  app/routes/events/view/videoroom/create.js
  app/routes/events/view/videoroom/edit.js
  app/routes/events/view/videoroom/index.js
  app/routes/events/view/videoroom/list.js
  app/templates/components/modals/room-info-modal.hbs
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-title.hbs
  app/templates/events/view.hbs
  app/templates/events/view/videoroom.hbs
  app/templates/events/view/videoroom/create.hbs
  app/templates/events/view/videoroom/edit.hbs
  app/templates/events/view/videoroom/list.hbs
  tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-title-test.ts
Labels: feature

#5598 fix: list front page restriction in frontpage tab
  app/router.js
  app/templates/admin/settings.hbs
  app/templates/admin/settings/frontpage.hbs
Labels: fix

#5658 fix: don't trigger submit action twice
  app/components/forms/admin/settings/billing.js
  app/components/forms/login-form.js
  app/components/forms/orders/order-form.js
  app/components/forms/user-payment-info-form.js
  app/templates/components/forms/admin/settings/billing.hbs
  app/templates/components/forms/login-form.hbs
  app/templates/components/forms/user-payment-info-form.hbs
Labels: fix

#5612 fix: Remove historic countries that do not exist today from country list
  app/utils/dictionary/demography.ts
Labels: fix

#5686 fix: ticket sales value
  app/templates/events/view/tickets/index.hbs
Labels: fix

#5501 fix: Public page destortion on different resolution
  app/styles/components/speaker-list.scss
  app/templates/components/public/speaker-item.hbs
Labels: fix

#5466 fix: simplify sponsor box
  app/controllers/events/view/index.js
  app/templates/components/events/view/overview/event-sponsors.hbs
  app/templates/components/tables/default.hbs
Labels: fix

#4412 feat: Add local caching
  app/components/footer-main.js
  app/controllers/application.js
  app/controllers/events/view/tickets/orders/list.js
  app/routes/application.js
  app/services/auth-manager.js
  app/services/cache.ts
  app/services/settings.js
  app/templates/application.hbs
  app/utils/dictionary/demography.ts
  tests/integration/components/footer-main-test.js
  tests/unit/services/cache-test.ts
Labels: feature

#5581 chore: Link server docker installation steps
  docs/installation/docker.md
Labels: chore

#5657 fix: Wizard Step 1: Standardize spacing between sections
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#5661 feat: Implement deleting custom form field
  app/components/forms/wizard/attendee-step.js
  app/components/forms/wizard/custom-forms/table.hbs
  app/components/forms/wizard/custom-forms/table.ts
  app/templates/components/forms/wizard/attendee-step.hbs
Labels: feature

#5690 fix: Ticket Order: User able to add invalid email
  app/components/forms/orders/order-form.js
  app/utils/validators.js
Labels: fix

#5652 fix: Only show country dropdown without autocomplete
  app/components/country-dropdown.ts
  app/templates/components/country-dropdown.hbs
  app/templates/components/forms/admin/settings/billing.hbs
  app/templates/components/forms/admin/settings/ticket-fees-form.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/user-payment-info-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/tax-info-modal.hbs
  app/templates/components/widgets/forms/billing-info.hbs
  app/utils/dictionary/demography.ts
Labels: fix

#5662 fix: table with ticket details is not responsive in phone
  app/templates/components/public/ticket-list.hbs
Labels: fix

#5697 fix: Organizer Menu Item does not go to the section
  app/templates/components/public/side-menu.hbs
  app/templates/public/index.hbs
Labels: fix

#5656 feat: Add icon and option for Weblate in footer
  app/components/icons/weblate.hbs
  app/models/setting.js
  app/templates/components/footer-main.hbs
  app/templates/components/forms/admin/content/social-links-form.hbs
Labels: feature

#5694 fix: Payment method icons need to change
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#5701 fix: make listed areas translatable
  app/components/forms/wizard/custom-forms/table.hbs
  app/components/forms/wizard/wizard-footer.hbs
  app/controllers/admin/events/list.js
  app/controllers/admin/messages/list.js
  app/controllers/admin/reports/system-logs/activity-logs.js
  app/controllers/admin/reports/system-logs/mail-logs.js
  app/controllers/admin/reports/system-logs/notification-logs.js
  app/controllers/admin/sales/index.js
  app/controllers/admin/sales/invoices.js
  app/controllers/admin/sessions/list.js
  app/controllers/admin/users/list.js
  app/controllers/events/list.js
  app/controllers/events/view/sessions/list.js
  app/controllers/events/view/speakers/list.js
  app/templates/admin/sessions.hbs
  app/templates/components/event-card.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-session-state.hbs
  app/templates/events/view/sessions.hbs
Labels: fix

#5707 chore: Update translations
  app/components/widgets/forms/social-link-field.ts
  app/templates/admin/sales/revenue.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#5708 fix: Sort Events according to Dates by Default
  app/controllers/admin/events/list.js
  app/controllers/events/list.js
Labels: fix

#5700 fix: Make pricing page translatable
  app/styles/partials/overrides.scss
  app/templates/pricing.hbs
Labels: fix

#5710 fix: reduce number of events on front page
  app/routes/index.js
Labels: fix

#5713 fix: Remove order delete functionality
  app/controllers/events/view/tickets/orders/list.js
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-order-test.js
Labels: fix

#5714 fix: Add option to remove custom field in session speaker step
  app/components/forms/wizard/sessions-speakers-step.js
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: fix

#5611 fix: Change acknowledgement text and button
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#5716 chore: Update translations
  app/templates/pricing.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#5730 chore: Configure GitHub Actions
  .github/workflows/ci.yml
Labels: chore

#5731 chore: Separate gh actions jobs
  .github/workflows/ci.yml
Labels: chore

#5739 fix: show selected number of sponsor in sponsor-box
  app/routes/events/view/index.js
Labels: fix

#5503 fix: Handle side menu navigation correctly
  app/components/public/side-menu.js
  app/templates/components/public/side-menu.hbs
Labels: fix

#5740 chore: Add deployment action
  .github/workflows/ci.yml
Labels: chore

#5722 fix: position of logout icon in other languages
  app/templates/components/nav-bar.hbs
Labels: fix

#5737 fix: time-picker in mobile view in wizard session-step
  app/templates/components/widgets/forms/time-picker.hbs
Labels: fix

#5732 feat: Add download ticket option for each attendee
  app/components/forms/orders/attendee-list.js
  app/templates/components/forms/orders/attendee-list.hbs
Labels: feature

#5720 feat: Add Jitsi Integration
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/components/public/stream/video-stream.hbs
  app/components/public/stream/video-stream.ts
  app/controllers/events/list.js
  app/router.js
  app/routes/public/sessions.js
  app/routes/public/stream/view.ts
  app/templates/public/stream/view.hbs
  tests/unit/routes/public/stream/view-test.ts
Labels: feature

#5745 fix: Expand area below footer
  app/styles/partials/utils.scss
  app/templates/components/footer-main.hbs
Labels: fix

#5743 feat: Make rooms sortable
  app/components/forms/wizard/sessions-speakers-step.js
  app/controllers/events/view/scheduler.js
  app/models/microlocation.ts
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/events/view/scheduler.hbs
Labels: feature

#5753 feat: Enhance Video Stream UI
  app/components/public/session-item.hbs
  app/components/public/stream/video-stream.ts
  app/styles/libs/_helpers.scss
Labels: feature

#5755 fix: Reduce width of left side menu
  app/templates/explore.hbs
Labels: fix

#5742 fix: Reimplement session route to not reload page on filter
  app/controllers/public/sessions.js
  app/routes/public/sessions.js
  app/templates/public/sessions.hbs
Labels: fix

#5767 fix: Check video stream relation before loading
  app/components/public/session-item.hbs
  app/models/microlocation.ts
Labels: fix

#5775 feat: Add frontend cache query params
  app/adapters/application.js
  app/components/footer-main.js
  app/routes/application.js
  app/routes/index.js
  app/services/cache.ts
  app/services/settings.js
  config/environment.js
Labels: feature

#5747 fix: time standardization in two formats only
  app/components/public/add-to-calender.hbs
  app/components/public/session-item.hbs
  app/controllers/account/billing/invoices/list.js
  app/controllers/admin/sales/invoices.js
  app/controllers/admin/sessions/list.js
  app/controllers/admin/users/list.js
  app/controllers/events/list.js
  app/controllers/events/view/sessions/list.js
  app/controllers/events/view/tickets/orders/list.js
  app/templates/admin/sales/revenue.hbs
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/components/order-card.hbs
  app/templates/components/public/call-for-speakers.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/session-card.hbs
  app/templates/components/ui-table/cell/cell-event-date.hbs
  app/templates/components/ui-table/cell/cell-simple-date.hbs
  app/templates/components/ui-table/cell/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/event-invoice/review.hbs
  app/templates/explore.hbs
  app/templates/public.hbs
  app/templates/public/sessions.hbs
Labels: fix

#5772 feat: Schedule: Show date and time in left column
  app/styles/partials/utils.scss
  app/templates/public/sessions.hbs
Labels: feature

#5782 fix: Paid Donation ticket sale stats
  app/templates/events/view/tickets/index.hbs
Labels: fix

#5758 fix: Discount Codes: Simplify Form
  app/models/discount-code.js
  app/templates/components/forms/events/view/create-discount-code.hbs
Labels: fix

#5791 fix: Move session description display to "expanded area"
  app/components/public/session-item.hbs
Labels: fix

#5748 fix: Localize Date and Time translations using AM/PM
  app/controllers/admin/messages/list.js
  app/controllers/admin/sessions/list.js
  app/helpers/general-date.js
  app/helpers/header-date.js
  app/templates/admin/sales/revenue.hbs
  app/templates/components/event-invoice/event-info.hbs
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/components/footer-main.hbs
  app/templates/components/order-card.hbs
  app/templates/components/orders/event-info.hbs
  app/templates/components/session-card.hbs
  app/templates/components/ui-table/cell/cell-simple-date.hbs
  app/templates/components/ui-table/cell/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/explore.hbs
  app/templates/orders/expired.hbs
  app/templates/orders/new.hbs
  app/templates/orders/pending.hbs
  app/templates/orders/view.hbs
  app/templates/public/sessions.hbs
  tests/integration/helpers/header-date-test.js
Labels: fix

#5531 feat: Login Box: Show info message when page directs to login page
  app/components/public/call-for-speakers.js
  app/controllers/public/index.js
  app/routes/create.js
  app/templates/application.hbs
  app/templates/components/forms/login-form.hbs
  app/templates/components/modals/login-signup-modal.hbs
  package.json
  yarn.lock
Labels: feature

#5784 fix: Show 0.00 instead of 0 for Sales
  app/controllers/events/view/tickets/index.js
  app/templates/events/view/tickets/index.hbs
Labels: fix

#5799 chore: Change general-date helper timezone argument
  app/components/public/add-to-calender.hbs
  app/components/public/session-item.hbs
  app/components/ui-table/cell/cell-date.hbs
  app/helpers/general-date.js
  app/templates/admin/sales/revenue.hbs
  app/templates/components/event-card.hbs
  app/templates/components/event-invoice/event-info.hbs
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/components/footer-main.hbs
  app/templates/components/order-card.hbs
  app/templates/components/orders/event-info.hbs
  app/templates/components/public/call-for-speakers.hbs
  app/templates/components/public/speaker-item.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/public/track-item.hbs
  app/templates/components/session-card.hbs
  app/templates/components/ui-table/cell/cell-event-date.hbs
  app/templates/components/ui-table/cell/cell-simple-date.hbs
  app/templates/components/ui-table/cell/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/explore.hbs
  app/templates/orders/expired.hbs
  app/templates/orders/new.hbs
  app/templates/orders/pending.hbs
  app/templates/orders/view.hbs
  app/templates/public.hbs
  app/templates/public/sessions.hbs
  tests/integration/helpers/general-date-test.js
Labels: chore

#5803 feat: Make video URL more user friendly
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/components/public/stream/video-stream.ts
  app/controllers/events/view/videoroom/list.js
  app/models/video-stream.ts
  app/router.js
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs
  tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-title-test.ts
  tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-url-test.ts
Labels: feature

#5805 fix: Show sales amount with currency and remove symbol after text
  app/templates/events/view/tickets/index.hbs
Labels: fix

#5792 fix: Change "Apps" to "Website Generator" and other improvements
  app/templates/components/events/view/overview/event-apps.hbs
  app/templates/components/events/view/overview/event-sponsors.hbs
  tests/integration/components/events/view/overview/event-apps-test.js
Labels: fix

#5806 fix: Download ticket and invoice made available to ticket purchaser only
  app/templates/orders/view.hbs
Labels: fix

#5815 fix: Convert non-cached pages to array before sorting
  app/components/footer-main.js
Labels: fix

#5816 chore: Update translations
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#5830 fix: Show all sponsors on sponsors edit and public page
  app/routes/events/view/edit/sponsors.js
  app/routes/public/index.js
Labels: fix

#5819 feat: Enhance session item UI
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/models/speaker.js
Labels: feature

#5821 fix: increase height of language dropdown
  app/styles/partials/footer.scss
Labels: fix
