Repository fossasia/open-event-frontend, pull requests merged in 2020-01, with the labels that each got.

#3479 feat: PayPal env routing based on settings
  app/components/paypal-button.js
Labels: feature

#3583 fix: making table with ticket details compatible with phone
  app/templates/components/public/ticket-list.hbs
  app/templates/public/index.hbs
Labels: fix

#3588 fix: Renaming google plus entry to google groups in admin content social link page
  app/components/forms/admin/content/social-links-form.js
  app/templates/components/forms/admin/content/social-links-form.hbs
Labels: fix

#3753 fix: Stripe working on test & development mode
  app/components/forms/wizard/basic-details-step.js
  app/templates/public/index.hbs
  app/torii-providers/stripe.js
Labels: fix

#3759 fix: defining event hook in edit speaker/session route
  app/templates/events/view/sessions/edit.hbs
  app/templates/events/view/speakers/edit.hbs
Labels: fix

#3760 feat: Fallback to embedded iframe map
  app/routes/public/index.js
  app/styles/pages/public-event.scss
  app/templates/components/public/event-map.hbs
  app/templates/public/index.hbs
  config/environment.js
Labels: feature

#3765 fix: Use proper image sizes for session speaker avatar
  app/templates/components/public/session-item.hbs
Labels: fix

#3764 chore: Release v1.8.0
  app/adapters/application.js
  app/components/forms/admin/content/social-links-form.js
  app/components/forms/reset-password-form.js
  app/components/forms/wizard/basic-details-step.js
  app/components/paypal-button.js
  app/controllers/oauth/callback.js
  app/controllers/public/index.js
  app/controllers/register.js
  app/routes/public/index.js
  app/services/device.js
  app/services/loader.js
  app/styles/pages/public-event.scss
  app/templates/components/forms/admin/content/social-links-form.hbs
  app/templates/components/public/event-map.hbs
  app/templates/components/public/session-item.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/events/view/sessions/edit.hbs
  app/templates/events/view/speakers/edit.hbs
  app/templates/public/index.hbs
  app/torii-providers/stripe.js
  config/environment.js
  package.json
  scripts/replace-config.js
  yarn.lock
Labels: chore

#3770 fix: Updating file signatures for extended jpeg support
  app/utils/file.js
Labels: fix

#3779 fix: Defining computed countries property
  app/components/forms/orders/order-form.js
  app/components/widgets/forms/billing-info.js
Labels: fix

#3782 fix: Missing fields in session/speaker cluster
  app/routes/events/view/sessions/create.js
  app/routes/events/view/sessions/edit.js
  app/routes/events/view/speakers/create.js
  app/routes/events/view/speakers/edit.js
  app/routes/public/cfs/edit-session.js
  app/routes/public/cfs/edit-speaker.js
Labels: Priority: Urgent, fix

#3784 chore: Release 1.8.1
  app/components/forms/orders/order-form.js
  app/components/widgets/forms/billing-info.js
  app/routes/events/view/sessions/create.js
  app/routes/events/view/sessions/edit.js
  app/routes/events/view/speakers/create.js
  app/routes/events/view/speakers/edit.js
  app/routes/public/cfs/edit-session.js
  app/routes/public/cfs/edit-speaker.js
  app/utils/file.js
Labels: chore

#3793 fix: Sessions were restricted to limit 20
  app/routes/events/view/speakers/create.js
  app/templates/components/forms/session-speaker-form.hbs
Labels: fix

#3798 fix: URL Fields are segmented without protocol
  app/templates/components/forms/session-speaker-form.hbs
Labels: fix

#3801 fix: Introducing Instagram URL in speaker model
  app/models/custom-form.js
  app/models/speaker.js
Labels: fix

#3802 fix: validation working for gender and country
  app/templates/components/forms/session-speaker-form.hbs
Labels: fix

#3809 fix: make country as dropdown and add validation for gender
  app/components/forms/orders/order-form.js
  app/mixins/custom-form.js
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/forms/orders/order-form.hbs
Labels: DO-NOT-MERGE, fix

#3792 fix: Place unverified user message above the segment in account route
  app/templates/account.hbs
  app/templates/account/profile.hbs
Labels: enhancement, fix

#3791 fix: arrange unschedule session based on their event-time
  app/routes/my-sessions/list.js
Labels: fix

#3763 chore: Improve readme quality
  README.md
Labels: chore

#3814 fix: Editing a Speaker shows Linkedin link
  app/models/speaker.js
Labels: fix

#3803 feat: add ageGroup Field in attendee form
  app/components/forms/orders/order-form.js
  app/mixins/custom-form.js
  app/models/attendee.js
  app/models/custom-form.js
  app/templates/components/forms/orders/order-form.hbs
  app/utils/dictionary/age-groups.js
Labels: feature

#3786 feat: Changing current user loading method using async promises
  app/controllers/public/index.js
  app/routes/application.js
  app/services/auth-manager.js
  app/services/current-user.js
Labels: feature

#3829 chore: Ignore the OS-X Trash
  .gitignore
Labels: chore

#3830 fix: AccessURL generated is fixed
  app/components/forms/events/view/create-access-code.js
Labels: fix

#3820 feat: Show "promoted to front page" posts on front page before regular events
  app/controllers/admin/events/list.js
  app/controllers/index.js
  app/models/event.js
  app/templates/components/ui-table/cell/admin/events/event-is-featured.hbs
  app/templates/components/ui-table/cell/admin/events/event-is-promoted.hbs
  app/templates/index.hbs
Labels: feature

#3822 chore: Bump node/yarn version & removing obsolete script
  .travis.yml
  Dockerfile
  netlify.toml
  package.json
  scripts/pr_deploy.sh
Labels: chore

#3831 fix: add missing validations in wizard
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/sessions-speakers-step.js
  app/components/modals/tax-info-modal.js
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: fix

#3818 fix: don't able to call server when promotional code is empty
  app/templates/components/public/ticket-list.hbs
Labels: fix

#3835 fix: Send refreshModel after deletion of event
  app/controllers/admin/events/list.js
Labels: fix

#3813 chore: Release v1.9
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  app/components/forms/events/view/create-access-code.js
  app/components/forms/orders/order-form.js
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/sessions-speakers-step.js
  app/components/modals/tax-info-modal.js
  app/controllers/admin/events/list.js
  app/controllers/index.js
  app/controllers/public/index.js
  app/mixins/custom-form.js
  app/models/attendee.js
  app/models/custom-form.js
  app/models/event.js
  app/models/speaker.js
  app/routes/application.js
  app/routes/events/view/speakers/create.js
  app/routes/my-sessions/list.js
  app/services/auth-manager.js
  app/services/current-user.js
  app/templates/account.hbs
  app/templates/account/profile.hbs
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/ui-table/cell/admin/events/event-is-featured.hbs
  app/templates/components/ui-table/cell/admin/events/event-is-promoted.hbs
  app/templates/index.hbs
  app/utils/dictionary/age-groups.js
  netlify.toml
  package.json
  scripts/pr_deploy.sh
Labels: chore

#3825 chore: enhance docker config injection
  ember-cli-build.js
  scripts/fastboot-server.js
  scripts/replace-config.js
Labels: chore

#3841 fix: Removing secret from FE
  app/components/forms/admin/settings/system-form.js
  app/models/setting.js
  app/templates/components/forms/admin/settings/system-form.hbs
Labels: fix

#3844 fix: country rendering in attendee form
  app/components/forms/orders/order-form.js
Labels: fix

#3819 fix: introducing cropper in session speaker form for speaker
  app/styles/components/speaker-list.scss
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/public/speaker-item.hbs
Labels: fix

#3846 fix: Fetch only featured speakers on event public page
  app/controllers/public/index.js
  app/routes/public/index.js
  app/templates/public/index.hbs
Labels: fix

#3842 fix: Correcting the extravaluePaths
  app/controllers/events/view/tickets/attendees/list.js
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
Labels: fix

#3856 fix: Implement infinityLoader for event speakers
  app/routes/public/speakers.js
  app/templates/public/speakers.hbs
Labels: fix

#3857 chore: Remove ember-cli-geo
  package.json
  yarn.lock
Labels: chore

#3870 chore: Add fastboot server in package.json
  Dockerfile
  package.json
  yarn.lock
Labels: chore

#3881 chore: Update brower targets
  config/targets.js
Labels: chore

#3883 fix: remove dangling comma
  config/targets.js
Labels: chore

#3889 chore: Silence the jquery warnings
  config/deprecation-workflow.js
Labels: chore

#3871 chore: Remove ember jquery references
  app/components/modals/cropper-modal.js
  app/components/modals/modal-base.js
  app/components/modals/tax-info-modal.js
  app/components/notification-dropdown.js
  app/components/scheduler/unscheduled-session.js
  app/components/side-bar.js
  app/components/smart-overflow.js
  app/components/tabbed-navigation.js
  app/components/ui-table-select.js
  app/components/ui-table-server.js
  app/components/widgets/forms/color-picker.js
  app/components/widgets/forms/date-picker.js
  app/components/widgets/forms/file-upload.js
  app/components/widgets/forms/image-upload.js
  app/components/widgets/forms/places-autocomplete.js
  app/components/widgets/forms/radio-button.js
  app/components/widgets/forms/rich-text-editor.js
  app/components/widgets/forms/ticket-input.js
  app/components/widgets/forms/time-picker.js
  app/components/widgets/safe-image.js
  app/mixins/form.js
  package.json
Labels: chore

#3840 fix: Add omise cdn in CSP
  config/environment.js
Labels: fix

#3915 chore: Pin semantic-ui-ember to 3.0.3
  package.json
  yarn.lock
Labels: chore

#3929 chore: Fixing codacy issues and lint warning
  config/deprecation-workflow.js
Labels: chore
