Repository fossasia/open-event-frontend, pull requests merged in 2020-03, with the labels that each got.

#4173 chore: Capture and process order errors properly in Sentry
  app/controllers/public/index.js
  app/sentry.ts
  ember-cli-build.js
Labels: chore

#4177 fix: Expand unscheduled sessions criteria
  app/routes/events/view/scheduler.js
Labels: fix

#4182 chore: Add error reporting of caught exceptions
  .eslintrc.js
  app/components/account/danger-zone.js
  app/components/account/email-preferences-section.js
  app/components/events/view/export/api-response.js
  app/components/events/view/export/download-common.js
  app/components/events/view/export/download-zip.js
  app/components/events/view/overview/manage-roles.js
  app/components/forms/admin/settings/system/mail-settings/test-email-form.js
  app/components/forms/admin/settings/ticket-fees-form.js
  app/components/forms/login-form.js
  app/components/forms/reset-password-form.js
  app/components/forms/user-payment-info-form.js
  app/components/forms/user-profile-form.js
  app/components/forms/wizard/basic-details-step.js
  app/components/modals/change-image-modal.js
  app/components/modals/modal-base.js
  app/components/notification-dropdown.js
  app/components/public/ticket-list.js
  app/components/ui-table-server.js
  app/components/unverified-user-message.js
  app/components/widgets/forms/file-upload.js
  app/components/widgets/forms/image-upload.js
  app/controllers/account/password.js
  app/controllers/account/profile.js
  app/controllers/admin/content/events.js
  app/controllers/admin/content/index.js
  app/controllers/admin/content/pages.js
  app/controllers/admin/content/translations.js
  app/controllers/admin/events/list.js
  app/controllers/admin/messages.js
  app/controllers/admin/modules.js
  app/controllers/admin/permissions/event-roles.js
  app/controllers/admin/permissions/system-roles.js
  app/controllers/admin/sessions/list.js
  app/controllers/admin/settings/analytics.js
  app/controllers/admin/settings/billing.js
  app/controllers/admin/settings/images.js
  app/controllers/admin/settings/index.js
  app/controllers/admin/settings/microservices.js
  app/controllers/admin/settings/payment-gateway.js
  app/controllers/admin/settings/ticket-fees.js
  app/controllers/admin/users/list.js
  app/controllers/admin/users/view/account/contact-info.js
  app/controllers/admin/users/view/events/list.js
  app/controllers/event-invoice/paid.js
  app/controllers/events/import.js
  app/controllers/events/list.js
  app/controllers/events/view.js
  app/controllers/events/view/edit/attendee.js
Labels: chore

#4204 fix: Handle error on event save property null
  app/mixins/event-wizard.js
Labels: fix

#4205 fix: Organizer Heading in Ticketing Page
  app/templates/components/orders/organizer-info.hbs
  app/templates/components/public/side-menu.hbs
Labels: fix

#4207 chore: Complete french translation
  translations/fr.po
Labels: chore

#4209 chore: Release v1.13.0
  .eslintrc.js
  app/components/account/danger-zone.js
  app/components/account/email-preferences-section.js
  app/components/events/view/export/api-response.js
  app/components/events/view/export/download-common.js
  app/components/events/view/export/download-zip.js
  app/components/events/view/overview/manage-roles.js
  app/components/forms/admin/settings/system/mail-settings/test-email-form.js
  app/components/forms/admin/settings/ticket-fees-form.js
  app/components/forms/login-form.js
  app/components/forms/reset-password-form.js
  app/components/forms/user-payment-info-form.js
  app/components/forms/user-profile-form.js
  app/components/forms/wizard/basic-details-step.js
  app/components/modals/change-image-modal.js
  app/components/modals/modal-base.js
  app/components/notification-dropdown.js
  app/components/public/ticket-list.js
  app/components/ui-table-server.js
  app/components/unverified-user-message.js
  app/components/widgets/forms/file-upload.js
  app/components/widgets/forms/image-upload.js
  app/controllers/account/password.js
  app/controllers/account/profile.js
  app/controllers/admin/content/events.js
  app/controllers/admin/content/index.js
  app/controllers/admin/content/pages.js
  app/controllers/admin/content/translations.js
  app/controllers/admin/events/list.js
  app/controllers/admin/messages.js
  app/controllers/admin/modules.js
  app/controllers/admin/permissions/event-roles.js
  app/controllers/admin/permissions/system-roles.js
  app/controllers/admin/sessions/list.js
  app/controllers/admin/settings/analytics.js
  app/controllers/admin/settings/billing.js
  app/controllers/admin/settings/images.js
  app/controllers/admin/settings/index.js
  app/controllers/admin/settings/microservices.js
  app/controllers/admin/settings/payment-gateway.js
  app/controllers/admin/settings/ticket-fees.js
  app/controllers/admin/users/list.js
  app/controllers/admin/users/view/account/contact-info.js
  app/controllers/admin/users/view/events/list.js
  app/controllers/event-invoice/paid.js
  app/controllers/events/import.js
  app/controllers/events/list.js
  app/controllers/events/view.js
  app/controllers/events/view/edit/attendee.js
  app/templates/components/orders/organizer-info.hbs
  app/templates/components/public/side-menu.hbs
  package.json
  translations/fr.po
  yarn.lock
Labels: chore

#4154 feat: better reset-password-form
  app/components/forms/reset-password-form.js
  app/templates/components/forms/reset-password-form.hbs
Labels: feature

#4234 fix: Changed the semantic class for the image in attendee and organizer app
  app/templates/attendee-app.hbs
  app/templates/organizer-app.hbs
Labels: fix

#4257 chore: Replace croppie from bower to yarn
  app/components/modals/cropper-modal.js
  ember-cli-build.js
  package.json
  yarn.lock
Labels: chore

#4258 chore: Disable CSP
  config/environment.js
  package.json
  yarn.lock
Labels: chore

#4259 chore: Move tinyColorPicker from bower to npm
  ember-cli-build.js
  package.json
  yarn.lock
Labels: chore

#4284 chore: Remove ember-l10n/test-helpers
  tests/helpers/setup-integration-test.js
Labels: chore

#4285 chore: Remove ready event listener
  app/models/event.js
  app/models/user.js
Labels: chore

#4286 chore: Use defaultClass instead of classPrefix
  app/templates/application.hbs
Labels: chore

#4291 fix: added frontend checking
  app/components/forms/orders/order-form.js
  app/templates/components/widgets/forms/billing-info.hbs
Labels: fix

#4289 chore: setup pre-commit
  package.json
  yarn.lock
Labels: chore

#4290 chore: improve error reporting and fix typos
  app/controllers/events/view/tickets/access-codes/create.js
  app/controllers/events/view/tickets/access-codes/edit.js
  app/controllers/events/view/tickets/discount-codes/create.js
  app/controllers/events/view/tickets/discount-codes/edit.js
Labels: chore
