Repository fossasia/open-event-frontend, pull requests merged in 2020-02, with the labels that each got.

#3943 chore: removing template-inline-precompile
  package.json
Labels: chore

#3971 fix: Revert ember-l10n to 3.2.1
  app/services/l10n.js
  config/environment.js
  package.json
  yarn.lock
Labels: fix

#3970 chore: Add basic test for fastboot
  .travis.yml
  scripts/test_fastboot.sh
Labels: chore

#3977 chore: Pave way for octane
  app/components/event-invoice/billing-info.js
  app/components/event-invoice/event-info.js
  app/components/event-invoice/invoice-summary.js
  app/components/event-invoice/payee-info.js
  app/components/orders/organizer-info.js
  app/components/ui-table/cell/admin/events/event-is-featured.js
  app/components/ui-table/cell/admin/events/event-is-promoted.js
  app/components/ui-table/cell/admin/messages/cell-options.js
  app/components/ui-table/cell/cell-event-date.js
  app/components/ui-table/cell/cell-event-state.js
  app/components/ui-table/cell/cell-sessions-dashboard.js
  app/components/ui-table/cell/cell-speakers-dashboard.js
  app/components/ui-table/cell/cell-sponsor-image.js
  app/components/ui-table/cell/cell-sponsor-sanitize.js
  app/components/ui-table/cell/events/cell-action.js
  app/components/ui-table/cell/events/cell-amount.js
  app/components/ui-table/cell/events/cell-event-invoice.js
  app/components/ui-table/cell/events/view/speakers/cell-buttons.js
  app/components/ui-table/cell/events/view/speakers/cell-is-featured.js
  app/components/ui-table/cell/events/view/speakers/cell-simple-sessions.js
  app/components/ui-table/cell/events/view/speakers/speaker-logo.js
  app/components/ui-table/cell/events/view/speakers/speaker-mobile.js
  app/components/ui-table/cell/events/view/tickets/access-codes/cell-actions.js
  app/components/ui-table/cell/events/view/tickets/access-codes/cell-url.js
  app/components/ui-table/expand-row-cell.js
  app/components/ui-table/header-row-filtering.js
  app/components/ui-table/header-row-sorting.js
  app/components/ui-table/header-rows-grouped.js
  app/components/ui-table/header-sorting-icons.js
  config/optional-features.json
  package.json
  yarn.lock
Labels: chore

#3928 fix: FE check for user-role
  app/templates/components/modals/add-user-role-modal.hbs
Labels: fix

#3914 fix: change eventyay to {{settings.appname}} in footer
  app/templates/components/footer-main.hbs
Labels: fix

#3980 fix: Remove serialization of computed statistics
  app/controllers/admin/events/list.js
  app/controllers/admin/users/view/events/list.js
  app/controllers/events/list.js
  app/models/event.js
  app/routes/events/view/index.js
  app/serializers/event.js
Labels: fix

#3981 chore: Remove deprecated fetch adapter
  app/adapters/application.js
Labels: chore

#3868 fix: Improving the infinityLoader implemented
  app/routes/public/speakers.js
Labels: fix

#3988 chore: Merge master into dev
  package.json
  yarn.lock
Labels: chore

#3995 fix: center aligned infinity loader spinner on public speaker page
  app/templates/public/speakers.hbs
Labels: fix

#3849 fix: minOrder-maxOrder & minPrice-maxPrice validation in basic-details-step
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#4017 fix: Add crypto to fastboot dependencies
  package.json
Labels: fix

#4019 fix: Add crypto to fastboot dependencies (#4017)
  package.json
Labels: fix

#3852 fix: Removing ember-scroll-to addon
  app/components/public/side-menu.js
  app/templates/components/public/side-menu.hbs
  package.json
  yarn.lock
Labels: fix

#4008 fix: Choosing Ticket holder same as ticket buyer not makes the text light gray
  app/controllers/public/index.js
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#4025 test: Addition of paymentIcon Helpers Test
  tests/integration/helpers/payment-icon-test.js
Labels: tests

#4022 feat: Implementing infinityModel at public session route
  app/routes/public/sessions/list.js
  app/templates/public/sessions/list.hbs
Labels: feature

#4033 feat: Improving layout of Event Settings Page
  app/templates/events/view/settings.hbs
  app/templates/events/view/tickets/index.hbs
Labels: feature

#4036 fix: Event Identifier getting shown in Admin/User/Event
  app/controllers/admin/users/view/events/list.js
Labels: fix

#4038 fix: Disable role invite processing in fastboot mode
  app/routes/public/role-invites.js
Labels: fix

#4039 enh: improved danger-zone layout
  app/templates/components/account/danger-zone.hbs
Labels: enhancement

#4044 fix: adding tickets-type field in table
  app/templates/events/view/tickets/index.hbs
Labels: fix

#4051 fix: fixed create discount page
  app/templates/components/forms/events/view/create-access-code.hbs
  app/templates/components/forms/events/view/create-discount-code.hbs
Labels: fix

#4056 fix: Wrap read only relationships deletion in try catch
  app/serializers/event.js
Labels: fix

#4059 fix: remove location check from event-wizard mixin
  app/mixins/event-wizard.js
Labels: fix

#4057 chore: Release v1.11
  app/components/forms/wizard/basic-details-step.js
  app/components/public/side-menu.js
  app/controllers/admin/users/view/events/list.js
  app/controllers/events/view.js
  app/controllers/events/view/settings.js
  app/controllers/public/index.js
  app/mixins/event-wizard.js
  app/routes/public/role-invites.js
  app/routes/public/sessions/list.js
  app/serializers/event.js
  app/templates/components/account/danger-zone.hbs
  app/templates/components/forms/events/view/create-access-code.hbs
  app/templates/components/forms/events/view/create-discount-code.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/public/side-menu.hbs
  app/templates/events/view.hbs
  app/templates/events/view/settings.hbs
  app/templates/events/view/tickets/index.hbs
  app/templates/public/sessions/list.hbs
  app/templates/public/speakers.hbs
  package.json
  tests/integration/helpers/payment-icon-test.js
  yarn.lock
Labels: chore

#4063 Revert "chore(deps-dev): bump ember-source from 3.16.1 to 3.16.2"
  package.json
  yarn.lock
Labels: Priority: Urgent

#4065 chore: Merge master into dev
  package.json
  yarn.lock
Labels: chore

#4069 chore: Add typescript support
  app/config/environment.d.ts
  package.json
  tsconfig.json
  types/ember-data/types/registries/model.d.ts
  types/global.d.ts
  types/open-event-frontend/index.d.ts
  yarn.lock
Labels: chore

#4077 fix: Removing microlocation from speaker item
  app/templates/components/public/session-item.hbs
  app/templates/components/public/speaker-item.hbs
Labels: fix

#4076 feat: Restoring import events section
  app/controllers/events/import.js
  app/routes/events/import.js
  app/templates/components/events/imports-history-section.hbs
  app/templates/events/import.hbs
Labels: feature

#3621 fix: making side menu sticky
  app/styles/pages/public.scss
  app/templates/public.hbs
Labels: fix

#4073 chore: Convert some leaf nodes to TS
  app/utils/dictionary/age-groups.ts
  app/utils/dictionary/amazon-s3-regions.ts
  app/utils/dictionary/demography.ts
  app/utils/dictionary/event.ts
  app/utils/dictionary/filters.ts
  app/utils/dictionary/genders.ts
  app/utils/dictionary/languages.ts
  app/utils/dictionary/licenses.ts
  app/utils/dictionary/payment.ts
Labels: chore

#4085 fix: make event delete & transfer confirmation modal case sensitive
  app/components/modals/event-delete-modal.js
  app/components/modals/event-transfer-modal.js
Labels: fix

#4090 chore: remove filters.ts
  app/utils/dictionary/filters.ts
Labels: chore

#3979 fix: Remove awaits in loop
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/tickets/add-order.js
  app/controllers/events/view/tickets/order-form.js
  app/controllers/orders/new.js
  app/controllers/public/index.js
  app/mixins/event-wizard.js
Labels: fix

#4091 feat: Integrate sentry JS and remove raven
  app/app.js
  app/config/environment.d.ts
  app/helpers/currency-symbol.js
  app/sentry.ts
  app/services/auth-manager.js
  app/services/bug-tracker.ts
  app/services/raven.js
  config/environment.js
  ember-cli-build.js
  package.json
  tests/unit/services/bug-tracker-test.ts
  yarn.lock
Labels: feature

#4015 fix: remove duplicate import and no relative import
  app/initializers/extensions.js
  app/services/current-user.js
  app/services/device.js
  tests/app.js
  tests/test-helper.js
Labels: fix

#4093 feat: Parallelize application requests
  app/routes/application.js
Labels: feature

#4096 chore: fix relative import
  app/initializers/extensions.js
  app/services/current-user.js
  app/services/device.js
  tests/test-helper.js
Labels: chore

#4097 chore: .lock file conflicts
  yarn.lock
Labels: chore

#4105 chore: update netlify link in README
  README.md
Labels: chore

#4111 fix: added .vscode and .nvmrc in .gitignore
  .gitignore
Labels: fix

#4120 fix: Make app compatible with latest auto-prefixer
  ember-cli-build.js
Labels: fix

#4114 fix: increase table width to avoid overflow and collapse
  app/controllers/events/view/speakers/list.js
  app/controllers/events/view/tickets/access-codes/list.js
Labels: fix

#4132 chore: Silence the evented-api-usage warnings
  config/deprecation-workflow.js
Labels: chore

#4153 fix: order buttons alignment on small screens
  app/templates/orders/view.hbs
Labels: fix
