Repository fossasia/open-event-frontend, pull requests merged in 2020-05, with the labels that each got.

#4352 chore: Remove remaining bower packages
  ember-cli-build.js
  package.json
  yarn.lock
Labels: chore

#4356 docs(installation): fix typo
  docs/installation/local.md
Labels: documentation

#4370 fix: Add condition check on Clear Filter
  app/components/quick-filter.js
Labels: fix

#4371 fix: Update in local installation file
  docs/installation/local.md
Labels: fix

#4384 fix: url overflow in event export section
  app/templates/components/events/view/export/api-response.hbs
  app/templates/components/events/view/export/download-common.hbs
Labels: fix

#4390 chore: Replace html-sanitizer with dompurify
  app/services/sanitizer.js
  ember-cli-build.js
  package.json
  tests/unit/services/sanitizer-test.js
  yarn.lock
Labels: chore

#4392 fix: Change tracked condition to make computed work
  app/components/modals/event-delete-modal.js
  app/components/modals/user-delete-modal.js
Labels: fix

#4393 chore: Only enable sentry for non dummy DSN
  app/sentry.ts
Labels: chore

#4387 fix: Misc bugs with ES6 getters
  app/components/forms/wizard/basic-details-step.js
  app/components/modals/tax-info-modal.js
Labels: fix

#4395 feat(ui): Change to default rounded look
  app/styles/partials/utils.scss
  app/templates/components/event-card.hbs
  app/templates/components/forms/login-form.hbs
  app/templates/components/forms/register-form.hbs
  app/templates/components/quick-filter.hbs
  package.json
  yarn.lock
Labels: feature

#4400 feat: Parallelize event page fetch
  app/components/public/ticket-list.js
  app/routes/public/index.js
Labels: feature

#4404 fix: Move padding inside unverified user component
  app/components/unverified-user-message.hbs
  app/components/unverified-user-message.js
  app/styles/partials/utils.scss
  app/templates/account.hbs
  app/templates/components/unverified-user-message.hbs
  app/templates/create.hbs
  app/templates/events/view.hbs
  app/templates/public.hbs
  tests/integration/components/unverified-user-message-test.js
Labels: fix

#4406 feat: parallelize event overview api requests
  app/routes/events/view/index.js
Labels: feature

#4415 fix: Support adding tax to created events
  app/components/forms/wizard/basic-details-step.js
  app/mixins/event-wizard.js
Labels: fix

#4428 fix: Properly format money everywhere
  app/initializers/accounting.js
  app/templates/admin/sales/discounted-events.hbs
  app/templates/admin/sales/index.hbs
  app/templates/admin/sales/locations.hbs
  app/templates/admin/sales/marketer.hbs
  app/templates/admin/sales/organizers.hbs
  app/templates/admin/sales/revenue.hbs
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/components/events/view/overview/event-tickets.hbs
  app/templates/components/orders/order-summary.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/ui-table/cell/admin/sales/status/cell-amount.hbs
  app/templates/components/ui-table/cell/events/cell-amount.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-price.hbs
  app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-price.hbs
  app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-total.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs
  app/templates/event-invoice/review.hbs
Labels: fix
