Repository fossasia/open-event-frontend, pull requests merged in 2020-09, with the labels that each got.

#4905 feat: Adding a step two in wizard form
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/other-details-step.js
  app/controllers/events/view/edit/attendee.js
  app/controllers/events/view/edit/basic-details.js
  app/controllers/events/view/edit/other-details.js
  app/mixins/event-wizard.js
  app/router.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/events/view/edit/other-details.hbs
Labels: feature

#4933 fix: Redirect from /sessions to /schedule
  app/router.js
  app/routes/public/sessions-index.js
Labels: fix

#4924 feat: implement dropdown for social media in other-details step
  app/components/forms/wizard/other-details-step.js
  app/components/widgets/forms/link-input.js
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/widgets/forms/link-input.hbs
  app/utils/computed-helpers.js
Labels: feature

#4853 fix: Link sessions in speaker list to sessions page
  app/controllers/public/session/view.js
  app/templates/components/public/speaker-item.hbs
  app/templates/public/session/view.hbs
Labels: fix

#4932 fix: increase page size to 21 for speakers
  app/routes/public/speakers.js
Labels: fix

#4919 feat: Create a pricing page with info
  app/router.js
  app/templates/pricing.hbs
Labels: feature

#4938 feat: show addition information step in event checklist
  app/templates/components/events/view/overview/event-setup-checklist.hbs
Labels: feature

#4941 fix: addition info step description
  app/mixins/event-wizard.js
Labels: fix

#4943 feat: only request to fill username for social links in forms
  app/components/widgets/forms/link-input.js
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/widgets/forms/link-input.hbs
Labels: feature

#4904 feat: link event logo and name to event dashboard
  app/templates/components/ui-table/cell/cell-event-general.hbs
Labels: feature

#4946 chore: Correct local installation steps
  docs/installation/local.md
Labels: chore

#4930 feat: Edit Custom Form Fields
  app/components/forms/wizard/attendee-step.js
  app/components/forms/wizard/custom-form-input.hbs
  app/components/forms/wizard/custom-form-input.ts
  app/components/forms/wizard/custom-forms/table.hbs
  app/components/forms/wizard/custom-forms/table.ts
  app/routes/events/view/edit/attendee.js
  app/routes/events/view/edit/sessions-speakers.js
  app/styles/libs/_helpers.scss
  app/templates/components/forms/wizard/attendee-step.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  package.json
Labels: feature

#4948 fix: Check for address and link nullability in LinkInput
  app/components/widgets/forms/link-input.js
Labels: fix

#4953 feat: use LinkInput for url fields in order-form
  app/templates/components/forms/orders/order-form.hbs
Labels: feature

#4964 fix: Revert LinkInput changes
  app/components/forms/wizard/other-details-step.js
  app/components/widgets/forms/link-input.js
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/widgets/forms/link-input.hbs
  app/utils/computed-helpers.js
Labels: fix

#4969 fix: Links in Footer Column - Plan Events
  app/templates/components/footer-main.hbs
Labels: fix

#4970 fix: adding allowClear to make fields null again
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#4974 feat: add patreon social link
  app/components/forms/admin/content/social-links-form.js
  app/models/setting.js
  app/templates/components/footer-main.hbs
  app/templates/components/forms/admin/content/social-links-form.hbs
Labels: feature

#4973 fix: open internal footer links in same tab and change text
  app/templates/components/footer-main.hbs
Labels: fix

#4923 fix: Only show schedule and calendar on public page when published
  app/templates/components/public/side-menu.hbs
Labels: fix

#4883 fix: page scroll with URL hash redirection.
  app/components/public/side-menu.js
  app/templates/components/public/side-menu.hbs
  app/templates/public/index.hbs
Labels: fix

#4977 fix: Add more constraints for upcoming events
  app/adapters/event.js
  app/controllers/index.js
  app/routes/index.js
  app/templates/index.hbs
Labels: fix

#4979 fix: Remove map and autocomplete from explore
  app/routes/explore.js
  app/templates/components/explore/side-bar.hbs
Labels: fix

#4980 fix: License of Event Data & Content clear field
  app/components/forms/wizard/other-details-step.js
  app/templates/components/forms/wizard/other-details-step.hbs
Labels: fix

#4984 chore: Stripe authentication message in basic-details step
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: chore

#4991 fix: Rerender calendar on timezone change
  app/components/schedule.hbs
  app/components/schedule.ts
Labels: fix

#4997 chore: change event blog url
  app/templates/components/footer-main.hbs
Labels: chore

#4998 fix: adding line break for formating error
  app/components/widgets/forms/rich-text-editor.js
  app/templates/components/widgets/forms/rich-text-editor.hbs
Labels: fix

#4985 fix: complete remaining part of pricing page
  app/templates/components/nav-bar.hbs
  app/templates/pricing.hbs
  public/images/pricing-header.jpg
Labels: fix

#5002 feat: add verticle timeline
  app/styles/components/track-item.scss
  app/templates/public/sessions.hbs
Labels: feature

#5001 fix: change email verification message on success
  app/templates/verify.hbs
Labels: fix

#5021 fix: Admin Pages Content
  app/components/widgets/forms/rich-text-editor.js
  app/controllers/admin/content/pages.js
  app/routes/pages.js
Labels: fix

#5012 feat: Integrate online events
  app/components/forms/wizard/basic-details-step.js
  app/mixins/event-wizard.js
  app/models/event.js
  app/templates/components/forms/wizard/attendee-step.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/forms/wizard/sponsors-step.hbs
  app/templates/components/public/event-map.hbs
  app/templates/public/index.hbs
Labels: feature

#5024 feat: Pick local timezone for online events by default
  app/components/widgets/time-zone-picker.hbs
  app/components/widgets/time-zone-picker.ts
  app/templates/public/schedule.hbs
  app/templates/public/sessions.hbs
Labels: feature

#5029 feat: add refund policy section in other-details step
  app/models/event.js
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/public/ticket-list.hbs
Labels: feature

#5000 feat: handle social links with LinkInput widget
  app/components/forms/admin/content/social-links-form.js
  app/components/forms/session-speaker-form.js
  app/components/forms/wizard/other-details-step.js
  app/components/widgets/forms/link-input.js
  app/mixins/event-wizard.js
  app/templates/components/forms/admin/content/social-links-form.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/widgets/forms/link-input.hbs
  app/utils/computed-helpers.js
Labels: feature

#5027 feat: Create team and permissions page
  app/router.js
  app/routes/events/view/index.js
  app/routes/events/view/team.ts
  app/routes/events/view/team/index.ts
  app/routes/events/view/team/permissions.ts
  app/templates/components/events/view/overview/manage-roles.hbs
  app/templates/components/modals/add-user-role-modal.hbs
  app/templates/events/view.hbs
  app/templates/events/view/index.hbs
  app/templates/events/view/team.hbs
  app/templates/events/view/team/index.hbs
  app/templates/events/view/team/permissions.hbs
  tests/integration/components/events/view/overview/manage-roles-test.js
  tests/unit/routes/events/view/team-test.ts
  tests/unit/routes/events/view/team/index-test.ts
  tests/unit/routes/events/view/team/permissions-test.ts
Labels: feature

#4926 chore: Change "Microlocations" to "Microlocations or Virtual Online Rooms"
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: chore

#5023 fix: insert link in description field
  app/templates/components/widgets/forms/rich-text-editor.hbs
Labels: fix

#5039 fix: show refund policy button only if its present
  app/templates/components/public/ticket-list.hbs
Labels: fix

#5044 fix: Restore map hide toggle behaviour
  app/templates/components/public/event-map.hbs
Labels: fix

#5045 fix: Remove sponsor header from list
  app/templates/components/public/sponsor-list.hbs
  tests/integration/components/public/sponsor-list-test.js
Labels: fix

#5030 fix: Display card image correctly
  app/helpers/payment-icon.js
  tests/integration/helpers/payment-icon-test.js
Labels: fix

#5065 fix: pricing option added for anonymous users
  app/templates/components/side-bar.hbs
Labels: fix

#5011 feat: make publishing event clearer
  app/components/events/view/publish-bar.hbs
  app/components/events/view/publish-bar.ts
  app/components/forms/wizard/attendee-step.js
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/other-details-step.js
  app/components/forms/wizard/sessions-speakers-step.js
  app/components/forms/wizard/sponsors-step.js
  app/components/forms/wizard/wizard-footer.hbs
  app/controllers/events/view.js
  app/mixins/event-wizard.js
  app/templates/components/forms/wizard/attendee-step.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/forms/wizard/sponsors-step.hbs
  app/templates/events/view.hbs
  tests/integration/components/events/view/publish-bar-test.ts
  tests/integration/components/forms/wizard/wizard-footer-test.ts
Labels: feature

#5070 fix: Link and show session detail to guests
  app/components/public/session-item.hbs
  app/components/public/session-list.js
  app/controllers/public/session/view.js
  app/routes/public/session/view.js
  app/templates/components/public/session-list.hbs
  app/templates/public/session/view.hbs
  app/templates/public/sessions.hbs
  tests/integration/components/public/session-item-test.js
  tests/integration/components/public/session-list-test.js
Labels: fix

#5073 feat: Add cookie policy editor and fix hide behaviour
  app/controllers/application.js
  app/models/setting.js
  app/templates/application.hbs
  app/templates/components/forms/admin/settings/system-form.hbs
Labels: feature

#5075 fix: Redirect to session details after edit
  app/controllers/public/cfs/edit-session.js
Labels: fix

#5074 feat: Add video and slides to session
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/models/setting.js
  app/routes/public/session/view.js
  app/styles/components/track-item.scss
  app/utils/url.ts
  package.json
  tests/unit/utils/url-test.ts
  yarn.lock
Labels: feature

#5069 feat: add telegram & gitter social links
  app/models/setting.js
  app/templates/components/footer-main.hbs
  app/templates/components/forms/admin/content/social-links-form.hbs
Labels: feature

#5080 fix: Convert gitter and telegram links to normal input
  app/models/setting.js
  app/templates/components/forms/admin/content/social-links-form.hbs
Labels: fix

#5049 fix: Restructure Account Invoice Tab
  app/components/ui-table/cell/events/cell-download-invoice.js
  app/controllers/account/billing/invoices/list.js
  app/models/user.js
  app/routes/account/billing/invoices/list.js
  app/templates/account.hbs
  app/templates/account/billing/invoices.hbs
  app/templates/components/ui-table/cell/events/cell-action.hbs
  app/templates/components/ui-table/cell/events/cell-download-invoice.hbs
Labels: fix

#4939 fix: overlapping of the logo
  app/styles/pages/public-event.scss
Labels: fix

#5105 fix: Restore ticket clause for saving event
  app/mixins/event-wizard.js
Labels: fix

#5111 fix: Remove timeline day from calendar
  app/components/schedule.ts
Labels: fix

#5119 fix: Number of ticket calculation transpilation
  app/mixins/event-wizard.js
Labels: fix

#5114 fix: make some admin billing fields optional
  app/components/forms/admin/settings/billing.js
  app/templates/components/forms/admin/settings/billing.hbs
Labels: fix

#5118 fix: absorb fee required for donation ticket too
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: fix

#5066 fix: Seperate the admin/sales tab into 2 subtabs
  app/components/ui-table/cell/admin/sales/cell-action.js
  app/controllers/admin/sales/invoices.js
  app/templates/admin/sales.hbs
  app/templates/components/ui-table/cell/admin/sales/cell-action.hbs
Labels: fix

#5084 fix: removing ticket group, some extra line and adding a popup
  app/components/widgets/forms/ticket-input.js
  app/helpers/confirm.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: fix

#5124 fix: Delete Space before Commas to format date
  app/helpers/general-date.js
  app/templates/components/events/view/overview/general-info.hbs
Labels: fix

#5109 fix: basic details image display enhancement
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/widgets/forms/image-upload.hbs
Labels: fix

#5135 fix: Add split :// to link in component
  app/components/widgets/forms/link-input.js
Labels: fix

#5136 chore: Fix date format test
  tests/integration/helpers/general-date-test.js
Labels: chore

#5145 feat: Add paypal billing email in admin form
  app/components/forms/admin/settings/billing.js
  app/models/setting.js
  app/templates/components/forms/admin/settings/billing.hbs
Labels: feature

#5146 fix: Use correct billing info and PDF URL
  app/models/event-invoice.js
  app/models/user.js
  app/templates/components/event-invoice/billing-info.hbs
  app/templates/event-invoice/paid.hbs
  app/templates/event-invoice/review.hbs
Labels: fix

#5150 fix: Social link icon indentation
  app/templates/components/public/social-links.hbs
Labels: fix

#5167 fix: Add global ticket fees settings
  app/components/forms/admin/settings/ticket-fees-form.js
  app/controllers/admin/settings/ticket-fees.js
  app/templates/components/forms/admin/settings/ticket-fees-form.hbs
Labels: fix

#5144 fix: adding extra social link
  app/templates/components/widgets/forms/link-input.hbs
  app/utils/computed-helpers.js
Labels: fix

#5168 fix: start date in event wizard causing error
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#5152 fix: standarize all pages to same
  app/templates/attendee-app.hbs
  app/templates/organizer-app.hbs
  app/templates/pages.hbs
  app/templates/pricing.hbs
  public/images/app-landing-header.jpg
Labels: fix

#5148 fix: fixing error with the price of donation ticket
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: fix

#5171 fix: Show speakers menu only when speakers present
  app/components/public/side-menu.js
  app/templates/components/public/side-menu.hbs
Labels: fix

#5172 fix: Deleted ticket publish prevention logic
  app/mixins/event-wizard.js
Labels: fix

#5182 fix: Sentry event handle undefined
  app/sentry.ts
Labels: fix

#5183 fix: Handle undefined controller
  app/routes/index.js
Labels: fix

#5185 fix: Return false if no deleted ticket
  app/mixins/event-wizard.js
Labels: fix

#5186 fix: Use optional chaining in unverified user condition
  app/components/unverified-user-message.js
Labels: fix

#5189 fix: Check this.user before resetting avatar
  app/components/widgets/forms/image-upload.js
Labels: fix

#5191 chore: Reduce error to warning for unverified user order
  app/controllers/public/index.js
Labels: chore

#5192 chore: Improve password reset error message
  app/components/forms/reset-password-form.js
Labels: chore

#5193 fix: Allow newline in sanitized HTML
  app/services/sanitizer.js
Labels: fix

#5194 fix: Link Input for http links
  app/utils/computed-helpers.js
Labels: fix

#5190 fix: Add optional chaining to unverified user condition
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/other-details-step.js
  app/components/public/ticket-list.js
Labels: fix

#5196 fix: Show online or mixed location in event page header
  app/controllers/public.js
  app/templates/public.hbs
Labels: fix

#5199 fix: Use issued-at for event invoice
  app/controllers/account/billing/invoices/list.js
  app/models/event-invoice.js
  app/routes/account/billing/invoices/list.js
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/event-invoice/review.hbs
Labels: fix

#5204 fix: Use UTC timezone for invoice issue dates
  app/components/ui-table/cell/cell-date.hbs
  app/controllers/account/billing/invoices/list.js
  app/routes/event-invoice/review.js
  app/templates/event-invoice/review.hbs
Labels: fix

#5206 fix: Add invoice download button on review page
  app/templates/event-invoice/review.hbs
Labels: fix
