Repository fossasia/open-event-frontend, pull requests merged in 2020-08, with the labels that each got.

#4698 chore: Adds sentry APM
  app/config/environment.d.ts
  app/sentry.ts
  config/environment.js
  package.json
  yarn.lock
Labels: chore

#4703 fix: disable browser autofill for Country fields in forms
  app/templates/components/forms/admin/settings/billing.hbs
  app/templates/components/forms/admin/settings/ticket-fees-form.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/user-payment-info-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/tax-info-modal.hbs
  app/templates/components/widgets/forms/billing-info.hbs
Labels: fix

#4692 fix: Delete ticket only when saved
  app/components/forms/wizard/basic-details-step.js
  app/mixins/event-wizard.js
Labels: fix

#4699 fix: Change edit endpoints in router
  app/router.js
Labels: fix

#4707 fix: Handle exception while serialising session
  app/serializers/session.js
Labels: fix

#4708 chore: Deduplicate session lock/unlock code
  app/controllers/events/view/sessions/list.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-lock-session.hbs
Labels: chore

#4538 chore: Finally remove @open-event/theme
  ember-cli-build.js
  package.json
  yarn.lock
Labels: Work in Progress, chore

#4713 fix: orange color for unpublish button
  app/templates/events/view.hbs
Labels: fix

#4714 fix: Handle absence of deleted tickets in mixin
  app/mixins/event-wizard.js
Labels: fix

#4705 fix: Session times in public session list
  app/components/public/session-item.js
  app/templates/components/public/session-item.hbs
  tests/integration/components/public/session-item-test.js
Labels: fix

#4725 fix: remove Question Marks instead of Location Search Box
  app/templates/components/quick-filter.hbs
Labels: fix

#4722 fix: save wizard as draft on each step
  app/components/forms/wizard/sessions-speakers-step.js
  app/components/forms/wizard/sponsors-step.js
Labels: fix

#4737 fix: Revert open-event-theme with scroll fix
  ember-cli-build.js
  package.json
  yarn.lock
Labels: fix

#4733 feat: Add session notify dialog
  app/components/modals/session-notify-modal.hbs
  app/components/modals/session-notify-modal.js
  app/components/ui-table/cell/events/view/sessions/cell-notify.hbs
  app/components/ui-table/cell/events/view/sessions/cell-notify.js
  app/controllers/events/view/sessions/list.js
  tests/integration/components/ui-table/cell/events/view/sessions/cell-notify-test.js
Labels: feature

#4742 fix: Include track and session type in org sessions view
  app/routes/events/view/sessions/list.js
Labels: fix

#4743 fix: Session state dropdown with/out email removed
  app/controllers/events/view/sessions/list.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs
Labels: fix

#4744 chore: Add more console errors
  app/controllers/orders/new.js
  app/controllers/orders/view.js
  app/controllers/public/cfs/edit-session.js
  app/controllers/public/cfs/edit-speaker.js
  app/controllers/public/cfs/new-session.js
  app/controllers/public/cfs/new-speaker.js
  app/mixins/notifications.js
Labels: chore

#4758 chore: Try storing error JSON in sentry
  app/sentry.ts
Labels: chore

#4757 fix: Patch FullCalendar to show single day events
  app/routes/events/view/scheduler.js
Labels: fix

#4754 fix: Separate sessions and session route
  app/controllers/events/view/sessions/list.js
  app/controllers/public/session/view.js
  app/router.js
  app/routes/public/session/view.js
  app/routes/public/sessions/list.js
  app/templates/components/session-card.hbs
  app/templates/public/session/view.hbs
Labels: fix

#4756 fix: Scheduler track color and obsolete action
  app/components/scheduler/unscheduled-session.js
  app/templates/events/view/scheduler.hbs
  tests/integration/components/scheduler/unscheduled-session-test.js
Labels: fix

#4761 chore(docs): Correct grammatical mistake
  README.md
Labels: chore, documentation

#4762 chore: Add typescript linting
  .eslintrc.js
  app/components/events/view/export/api-response.js
  app/components/forms/wizard/custom-form-input.ts
  app/sentry.ts
  app/services/bug-tracker.ts
  app/services/loader.js
  app/utils/dictionary/sessions.ts
  app/utils/sort.ts
  app/utils/text.ts
  package.json
  tests/unit/services/bug-tracker-test.ts
  tests/unit/utils/sort-test.ts
  yarn.lock
Labels: chore

#4765 chore: Remove ember-cli-mirage
  config/environment.js
  mirage/config.js
  mirage/scenarios/default.js
  mirage/serializers/application.js
  package.json
  tsconfig.json
  yarn.lock
Labels: chore

#4766 feat: Add filtering option to unscheduled sessions
  app/controllers/events/view/scheduler.js
  app/templates/events/view/scheduler.hbs
  app/utils/text.ts
Labels: feature

#4772 fix: make featured and promoted events sortable in admin
  app/controllers/admin/events/list.js
Labels: fix

#4775 feat: New scheduler implementation
  app/components/schedule.hbs
  app/components/schedule.js
  app/controllers/events/view/scheduler.js
  app/routes/events/view/scheduler.js
  app/routes/public/schedule.js
  app/templates/events/view/scheduler.hbs
  app/templates/public/schedule.hbs
  app/utils/patches/fullcalendar.js
  tests/integration/components/schedule-test.ts
Labels: feature

#4779 fix: Add null check on name of social link
  app/models/social-link.js
Labels: fix

#4786 chore: Create docker-compose.yml
  .env.example
  docker-compose.yml
Labels: chore

#4789 feat: Limit scheduler start and end time correctly
  app/components/schedule.hbs
  app/components/schedule.js
  app/components/schedule.ts
  app/models/event.js
  app/models/microlocation.js
  app/models/session.js
  app/models/speaker.js
  types/global.d.ts
Labels: feature

#4790 feat: Change text color based on session color lightness
  app/components/schedule.ts
  app/components/scheduler/unscheduled-session.js
  app/utils/color.ts
Labels: feature

#4793 feat: Add scrollbar in unscheduled sessions
  app/templates/events/view/scheduler.hbs
Labels: feature

#4794 fix: Session list date format with timezone
  app/components/public/session-item.js
  app/helpers/general-date.js
  app/templates/components/public/session-item.hbs
Labels: fix

#4797 feat: Adjust scheduler resource column widths
  app/components/schedule.ts
  app/styles/partials/all.scss
  app/styles/partials/fullcalendar.scss
  types/global.d.ts
Labels: feature

#4799 fix: Show all sessions in public section
  app/routes/public/schedule.js
Labels: fix

#4809 fix: show globe icon for general web links
  app/models/social-link.js
Labels: fix

#4823 fix: show sponsors logo in same size
  app/styles/pages/public-event.scss
  app/templates/components/public/sponsor-item.hbs
Labels: fix

#4819 fix: Show error details on deleting event
  app/controllers/admin/events/list.js
Labels: fix

#4824 feat: improve speaker list page column organization
  app/controllers/events/view/speakers/list.js
  app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs
Labels: feature

#4830 fix: Filter deletion sessions from speaker list
  app/routes/public/speakers.js
  app/templates/components/public/speaker-item.hbs
Labels: fix

#4715 fix: Add margin around speaker name and make text selectable
  app/templates/components/public/session-item.hbs
  app/templates/components/public/speaker-item.hbs
Labels: fix

#4851 fix: Handle undefined text color
  app/helpers/text-color.ts
  app/routes/public/index.js
  app/templates/components/public/speaker-item.hbs
Labels: fix

#4833 fix: correct order of fields in payment-info form
  app/templates/components/forms/user-payment-info-form.hbs
Labels: fix

#4854 fix: make calender height auto
  app/components/schedule.hbs
  app/templates/public/schedule.hbs
Labels: fix

#4856 fix: Remove CFS transition from fastboot
  app/routes/public/cfs/index.js
Labels: fix

#4860 feat: Add timezone picker
  app/components/schedule.ts
  app/components/widgets/time-zone-picker.hbs
  app/components/widgets/time-zone-picker.ts
  app/controllers/public/sessions.js
  app/styles/partials/utils.scss
  app/templates/public/schedule.hbs
  app/templates/public/sessions.hbs
  app/utils/dictionary/date-time.ts
  package.json
  yarn.lock
Labels: feature

#4864 feat: Display event logo in public event page
  app/styles/pages/public-event.scss
  app/styles/partials/utils.scss
  app/templates/public.hbs
Labels: feature

#4878 fix: Schedule publish toggle crash
  app/controllers/events/view/scheduler.js
Labels: fix

#4880 fix: Prefill ticket fields in wizard
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#4879 feat: Add tracks and rooms filters on sessions page
  app/routes/public/sessions.js
  app/styles/components/all.scss
  app/styles/components/extras.scss
  app/styles/partials/utils.scss
  app/templates/public.hbs
Labels: feature

#4901 fix: Enhance filter opacity and color
  app/styles/components/extras.scss
  app/templates/public.hbs
Labels: fix

#4900 feat: Add menu tab Sponsors
  app/templates/components/public/side-menu.hbs
  app/templates/public/index.hbs
Labels: feature

#4912 fix: Revert ember-source to 3.20.3
  package.json
  yarn.lock
Labels: fix

#4916 feat: Separate required and optional attendee fields
  app/components/forms/wizard/attendee-step.js
  app/templates/components/forms/wizard/attendee-step.hbs
  app/templates/components/forms/wizard/custom-forms/table.hbs
Labels: feature

#4918 feat: change session to schedule & schedule to calendar in URL
  app/router.js
  app/templates/components/public/side-menu.hbs
Labels: feature
