Repository fossasia/open-event-frontend, pull requests merged in 2020-12, with the labels that each got.

#5859 fix: Preselect Ticket holder same as Ticket Buyer in Order Form
  app/components/forms/orders/order-form.js
Labels: fix

#5861 fix: Adding and removing field without error in wizard step 2
  app/mixins/event-wizard.js
Labels: fix

#5843 fix: loading of session form in wizard step 5
  app/routes/events/view/edit/sessions-speakers.js
  app/routes/public/index.js
Labels: fix

#5751 fix: without email speaker going to my-session
  app/controllers/events/view/sessions/create.js
  app/controllers/events/view/sessions/edit.js
Labels: fix

#5856 fix: Download Tickets -> All Tickets
  app/styles/partials/overrides.scss
  app/templates/orders/view.hbs
Labels: fix

#5866 fix: Go to Event link added in Expired event page
  app/templates/components/orders/event-info.hbs
Labels: fix

#5812 fix: Show social links as icon
  app/components/public/social-links.js
  app/controllers/public.js
  app/models/social-link.js
  app/styles/pages/public.scss
  app/styles/partials/utils.scss
  app/templates/components/public/social-links.hbs
  app/templates/public.hbs
  app/utils/dictionary/social-media.ts
Labels: fix

#5872 fix: Show order buttons to admins
  app/controllers/orders/view.js
  app/routes/events/view/tickets/orders/list.js
  app/templates/orders/view.hbs
Labels: fix

#5876 fix: Fetch pages before findBy
  app/routes/pages.js
Labels: fix

#5878 fix: Preserve scrolling position while filtering sessions
  app/controllers/public/sessions.js
  app/routes/public/sessions.js
Labels: fix

#5823 feat: add search feature in schedule page
  app/controllers/public/sessions.js
  app/routes/public/sessions.js
  app/templates/components/tables/utilities/search-box.hbs
  app/templates/public/sessions.hbs
Labels: feature

#5828 chore: Change general-date helper format argument
  app/components/public/add-to-calender.hbs
  app/components/public/session-item.hbs
  app/controllers/admin/messages/list.js
  app/controllers/admin/sessions/list.js
  app/controllers/admin/users/list.js
  app/controllers/events/view/sessions/list.js
  app/controllers/events/view/tickets/orders/list.js
  app/helpers/general-date.js
  app/templates/admin/sales/revenue.hbs
  app/templates/components/event-invoice/event-info.hbs
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/components/order-card.hbs
  app/templates/components/orders/event-info.hbs
  app/templates/components/public/call-for-speakers.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/session-card.hbs
  app/templates/components/ui-table/cell/cell-event-date.hbs
  app/templates/components/ui-table/cell/cell-simple-date.hbs
  app/templates/components/ui-table/cell/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-date.hbs
  app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
  app/templates/event-invoice/review.hbs
  app/templates/explore.hbs
  app/templates/orders/expired.hbs
  app/templates/orders/new.hbs
  app/templates/orders/pending.hbs
  app/templates/orders/view.hbs
  app/templates/public.hbs
  app/templates/public/sessions.hbs
Labels: chore

#5809 fix: enhance session card in schedule page
  app/components/public/session-item.hbs
  app/styles/libs/_helpers.scss
  app/styles/partials/overrides.scss
  app/styles/partials/speaker.scss
  app/styles/partials/utils.scss
Labels: fix

#5777 feat: Reduce front page queries and cache more
  app/components/notification-dropdown.js
  app/components/public/side-menu.js
  app/routes/application.js
  app/routes/public/index.js
  app/serializers/application.js
  app/services/auth-manager.js
  app/services/cache.ts
  app/templates/application.hbs
  app/templates/components/nav-bar.hbs
Labels: feature

#5903 fix: Frontpage Tags not directing to filtered search page
  app/templates/components/event-card.hbs
Labels: fix

#5923 feat: Add images filter in explore page
  app/components/explore/side-bar.js
  app/controllers/explore.js
  app/routes/explore.js
  app/templates/components/explore/side-bar.hbs
  app/templates/explore.hbs
Labels: feature

#5924 feat: Enhance Front Page Search
  app/components/quick-filter.js
  app/controllers/index.js
  app/routes/index.js
  app/templates/components/quick-filter.hbs
  app/templates/index.hbs
  tests/integration/components/quick-filter-test.js
Labels: feature

#5798 fix: Timezone Display shows numbers instead of timezone name
  app/components/public/add-to-calender.hbs
  app/components/public/add-to-calender.ts
  app/components/public/session-item.hbs
  app/helpers/general-date.js
  app/utils/dictionary/tzAbbr.ts
  tests/integration/helpers/general-date-test.js
Labels: fix

#5957 feat: Global event video stream
  .eslintrc.js
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/public/add-to-calender.hbs
  app/components/public/session-item.hbs
  app/components/public/stream/join-video.hbs
  app/components/public/stream/stream-info.hbs
  app/controllers/events/view/videoroom/list.js
  app/models/event.js
  app/models/social-link.js
  app/models/video-stream.ts
  app/routes/events/view/videoroom/create.js
  app/routes/events/view/videoroom/edit.js
  app/routes/index.js
  app/routes/public.js
  app/routes/public/index.js
  app/serializers/video-stream.ts
  app/templates/components/tables/default.hbs
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-title.hbs
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs
  app/templates/events/view/videoroom/list.hbs
  app/templates/public.hbs
  app/templates/public/index.hbs
Labels: Work in Progress, feature

#5970 fix: Public Event Sidebar Dates Scrumbled
  app/helpers/general-date.js
Labels: fix

#5971 fix: sort Organizer Event Ticket Order Overview by date
  app/controllers/events/view/tickets/orders/list.js
Labels: fix

#5882 feat: Organizer Event Dashboard: Add column "Tickets"
  app/controllers/events/list.js
  app/models/event.js
  app/templates/components/ui-table/cell/cell-tickets.hbs
Labels: feature

#5981 fix: Promotional code/ Cards displayed according to ticket type
  app/components/public/ticket-list.js
  app/templates/components/public/ticket-list.hbs
Labels: fix

#5980 feat: allow admin to add logo to invoice
  app/models/setting.js
  app/templates/components/forms/admin/settings/billing.hbs
Labels: feature

#5470 fix: making track optional
  app/mixins/custom-form.js
Labels: fix

#5995 fix: Organizer Video Page - Move add room button and enhance design
  app/extensions/ember-table/template.hbs
  app/styles/libs/_helpers.scss
  app/styles/partials/utils.scss
  app/templates/components/tables/default.hbs
  app/templates/events/view/videoroom/list.hbs
Labels: fix

#5976 feat: Add Past filter to Explore page
  app/components/explore/side-bar.js
  app/controllers/explore.js
  app/routes/explore.js
  app/templates/components/explore/side-bar.hbs
  app/templates/explore.hbs
Labels: feature

#6006 fix: Explore Page: Vertical event card height fixed
  app/styles/libs/_helpers.scss
  app/templates/components/event-card.hbs
Labels: fix

#6008 fix: Virtual Events: Further enhance design and video tab page
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/public/stream/stream-info.hbs
  app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js
  app/components/ui-table/cell/events/view/videoroom/cell-video-url.js
  app/controllers/events/view/videoroom/list.js
  app/extensions/ember-table/template.hbs
  app/styles/partials/text.scss
  app/styles/partials/utils.scss
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs
  app/templates/components/ui-table/cell/events/view/videoroom/cell-video-url.hbs
  app/templates/events/view/videoroom/list.hbs
  tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-url-test.ts
Labels: fix

#6016 fix: Event Dashboard: long date format added
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/components/ui-table/cell/cell-event-date.hbs
Labels: fix

#6012 fix: Zip export download link not working
  app/components/events/view/export/download-zip.js
Labels: fix

#6001 feat: Implement Dashboard Box "Sessions and Speakers"
  app/components/events/view/overview/speaker-session.js
  app/routes/events/view/index.js
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/components/events/view/overview/speaker-session.hbs
  app/templates/events/view/index.hbs
Labels: feature

#6007 feat: Front Page: Move Search Function to Top Bar
  app/components/nav-bar.js
  app/components/side-bar.js
  app/controllers/application.js
  app/styles/libs/_helpers.scss
  app/styles/pages/events.scss
  app/styles/partials/utils.scss
  app/templates/application.hbs
  app/templates/components/nav-bar.hbs
  app/templates/components/side-bar.hbs
  app/templates/index.hbs
  tests/integration/components/nav-bar-test.js
  tests/integration/components/side-bar-test.js
Labels: feature

#6035 fix: Event Dashboard: Only show Sessions and Speakers Box if options are active
  app/templates/events/view/index.hbs
Labels: fix

#6052 fix: non-saved speaker appear in speakers list
  app/controllers/events/view/speakers/create.js
  app/routes/events/view/speakers/create.js
Labels: fix

#6039 fix: Search term should not get added to event categories
  app/components/event-card.js
  app/components/explore/side-bar.js
  app/controllers/explore.js
  app/routes/explore.js
  app/templates/explore.hbs
Labels: fix

#5990 feat: Add video channel support
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/public/stream/video-stream.ts
  app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js
  app/components/widgets/forms/link-field.hbs
  app/controllers/events/view/videoroom/list.js
  app/helpers/confirm.js
  app/models/video-channel.ts
  app/models/video-stream.ts
  app/routes/events/view/videoroom/create.js
  app/routes/events/view/videoroom/edit.js
  app/routes/events/view/videoroom/list.js
  app/routes/public/stream/view.ts
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs
  app/templates/components/ui-table/cell/events/view/videoroom/cell-video-url.hbs
  app/templates/events/view/videoroom/create.hbs
  app/templates/events/view/videoroom/edit.hbs
  app/templates/events/view/videoroom/list.hbs
  tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-url-test.ts
  tests/unit/models/video-channel-test.ts
Labels: feature

#6002 fix: Style of events-app on Overview Page
  app/templates/components/events/view/overview/event-apps.hbs
Labels: fix

#6071 fix: Change between location, online options etc. moves to top of page
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#6076 chore: Make team area translatable
  app/routes/events/view/team/permissions.ts
Labels: chore

#6077 chore: Update translations
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#6054 fix: formatting localized currency
  app/components/currency-amount.js
  app/templates/components/currency-amount.hbs
  tests/integration/components/currency-amount-test.js
  tests/integration/components/orders/ticket-price-test.ts
Labels: fix

#6081 chore: Make team area translatable (add t-var)
  app/templates/events/view/team/permissions.hbs
Labels: chore

#6083 chore: Resolve scss lint issue
  app/styles/pages/events.scss
Labels: chore

#5988 feat: Schedule: Add Date above sessions of the same date
  app/controllers/public/sessions.js
  app/styles/partials/utils.scss
  app/templates/public/sessions.hbs
Labels: feature

#6089 chore: Make various pages translatable
  app/adapters/application.js
  app/components/events/view/export/download-common.js
  app/components/forms/wizard/custom-form-input.hbs
  app/components/modals/session-notify-modal.hbs
  app/components/public/ticket-list.js
  app/components/widgets/time-zone-picker.hbs
  app/controllers/events/view/scheduler.js
  app/controllers/public.js
  app/mixins/event-wizard.js
  app/templates/application.hbs
  app/templates/attendee-app.hbs
  app/templates/components/forms/events/view/create-access-code.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/modals/edit-user-modal.hbs
  app/templates/components/nav-bar.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/side-bar.hbs
  app/templates/components/tables/utilities/search-box.hbs
  app/templates/components/widgets/forms/color-picker.hbs
  app/templates/events/view/scheduler.hbs
  app/templates/organizer-app.hbs
  app/templates/pages.hbs
  app/templates/verify.hbs
Labels: chore

#6041 fix: changing light to dark gray
  app/styles/components/extras.scss
  app/styles/libs/_helpers.scss
  app/styles/partials/event-card.scss
  app/styles/partials/text.scss
Labels: fix

#6091 feat: Enable Organizer to resend invitation
  app/components/events/view/overview/manage-roles.js
  app/templates/components/events/view/overview/manage-roles.hbs
Labels: feature

#6032 fix: enhance location filter options at explore page
  app/components/explore/side-bar.js
  app/controllers/explore.js
  app/routes/explore.js
  app/templates/components/explore/side-bar.hbs
  app/templates/explore.hbs
Labels: fix

#6019 feat: Organizer Menu Bar: Simplified Settings and merged Export Page Areas
  app/controllers/events/view/settings/export.js
  app/controllers/events/view/settings/options.js
  app/router.js
  app/routes/events/view/settings.js
  app/routes/events/view/settings/export.js
  app/routes/events/view/settings/index.js
  app/routes/events/view/settings/options.js
  app/styles/components/all.scss
  app/styles/components/events/view/settings/export.scss
  app/templates/events/view.hbs
  app/templates/events/view/settings.hbs
  app/templates/events/view/settings/export.hbs
  app/templates/events/view/settings/options.hbs
Labels: feature

#6087 feat: add hcaptcha to register and forgot password
  .env.example
  app/components/forms/register-form.js
  app/components/forms/reset-password-form.js
  app/templates/components/forms/register-form.hbs
  app/templates/components/forms/reset-password-form.hbs
  config/environment.js
  package.json
  yarn.lock
Labels: feature

#6004 fix: time stamp error in session
  app/components/schedule.ts
Labels: fix

#6097 feat: Implement sorting on attendee overview page
  app/components/tables/headers/sort.js
  app/controllers/events/view/tickets/attendees/list.js
  app/mixins/ember-table-route.js
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs
  app/utils/text.ts
Labels: feature

#6107 feat: add hcaptcha when user clicks more than two times to to login
  app/components/forms/login-form.js
  app/templates/components/forms/login-form.hbs
Labels: feature

#5900 chore: error handler basic service
  app/controllers/events/view/sessions/create.js
  app/controllers/events/view/sessions/edit.js
  app/controllers/events/view/sessions/list.js
  app/controllers/events/view/speakers/create.js
  app/controllers/events/view/speakers/edit.js
  app/controllers/events/view/speakers/list.js
  app/services/error-handler.js
Labels: chore

#6099 fix: Show Roles in capitalise form at team page
  app/routes/events/view/index.js
  app/routes/events/view/team/index.ts
  app/styles/partials/event-card.scss
  app/templates/components/events/view/overview/manage-roles.hbs
Labels: fix

#5998 fix: Public Schedule Mobile View: change in page menu
  app/components/public/side-menu-outer.js
  app/components/public/side-menu.js
  app/controllers/public.js
  app/templates/components/public/side-menu-outer.hbs
  app/templates/components/public/side-menu.hbs
  app/templates/public.hbs
Labels: fix

#6014 feat: Schedule and After-Event Video: Add video button to schedule
  app/components/public/session-item.hbs
  app/components/public/session-item.js
Labels: feature

#6078 fix: roles section overlapping with ticket section
  app/templates/components/ui-table/cell/cell-roles.hbs
Labels: fix

#6120 fix: Public Event Sidebar: Hide icons in side menu dekstop
  app/styles/partials/utils.scss
  app/templates/components/public/side-menu.hbs
Labels: fix

#6127 fix: Prevent "Private Events" from being searched
  app/routes/explore.js
Labels: fix

#6126 fix: sort attendee orders according to date and time
  app/controllers/events/view/tickets/attendees/list.js
Labels: fix

#6116 feat: Add side panel to video room
  app/components/event-card.js
  app/components/public/add-to-calender.hbs
  app/components/public/add-to-calender.ts
  app/components/public/event-date-time.hbs
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/components/public/stream/video-stream.hbs
  app/components/public/stream/video-stream.ts
  app/helpers/random.ts
  app/models/event.js
  app/routes/public/stream/view.ts
  app/styles/components/all.scss
  app/styles/components/stream.scss
  app/styles/libs/_helpers.scss
  app/styles/partials/utils.scss
  app/templates/components/event-card.hbs
  app/templates/public/stream/view.hbs
Labels: feature

#6105 fix: ticket cancellation by user
  app/components/order-card.js
  app/styles/partials/event-card.scss
  app/templates/components/order-card.hbs
Labels: fix

#6130 fix: Order expire page redirection out of no where
  app/components/forms/orders/order-form.js
Labels: fix

#6136 fix: Disable Role edit in Teams Page
  app/components/events/view/overview/manage-roles.js
  app/components/modals/add-user-role-modal.js
  app/templates/components/events/view/overview/manage-roles.hbs
Labels: fix

#6142 fix: enhance my ticket page
  app/components/public/event-date-time.hbs
  app/components/public/event-venue.hbs
  app/templates/components/event-card.hbs
  app/templates/components/order-card.hbs
Labels: fix

#6123 fix: Show Twitter Area as Collapsible/Extendable Area
  app/styles/partials/utils.scss
  app/templates/components/public/social-links.hbs
  app/templates/public.hbs
Labels: fix

#6112 feat: show email address and add CC in session notify modal
  app/components/modals/session-notify-modal.hbs
  app/components/modals/session-notify-modal.js
Labels: feature

#6147 fix: logo overlapping fixed
  app/styles/pages/public-event.scss
Labels: fix

#6149 chore: Make areas translatable
  app/components/public/side-menu-outer.js
  app/controllers/public.js
Labels: chore

#6152 fix: Improve responsiveness of event wizard
  app/components/forms/wizard/wizard-footer.hbs
Labels: fix

#6156 feat: Add bbb iframe integration
  app/components/public/stream/jitsi-stream.hbs
  app/components/public/stream/jitsi-stream.ts
  app/components/public/stream/video-stream.hbs
  app/components/public/stream/video-stream.ts
Labels: feature

#6158 fix: Tickets: mobile ticket view
  app/templates/components/public/ticket-list.hbs
Labels: fix

#6166 feat: Add stream side panel to public event page
  .sass-lint.yml
  app/components/public/session-item.js
  app/components/public/side-menu.js
  app/components/public/stream/join-video.hbs
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/controllers/public.js
  app/controllers/public/sessions.js
  app/services/loader.ts
  app/styles/components/stream.scss
  app/templates/public.hbs
  app/templates/public/sessions.hbs
  app/utils/event.ts
  tsconfig.json
Labels: feature

#5973 fix: Dashboard: session/speaker page button overflow fixed
  app/templates/events/view/sessions.hbs
  app/templates/events/view/speakers.hbs
Labels: fix

#6176 fix: Set side_panel null on controller reset
  app/routes/public.js
Labels: fix

#6058 fix: Adjust URLs on Video Tab Overview Page
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs
  app/templates/components/ui-table/cell/events/view/videoroom/cell-video-url.hbs
Labels: fix

#6096 fix: Add helper information on page
  app/components/forms/events/view/videoroom-form.hbs
  app/controllers/events/view/videoroom/list.js
  app/templates/components/tables/default.hbs
Labels: fix

#5960 fix: Company fields replaced with Organisation
  app/components/forms/admin/settings/billing.js
  app/components/forms/orders/order-form.js
  app/components/forms/user-payment-info-form.js
  app/components/modals/tax-info-modal.js
  app/models/custom-form.js
  app/templates/components/event-invoice/billing-info.hbs
  app/templates/components/forms/admin/settings/billing.hbs
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/forms/user-payment-info-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/tax-info-modal.hbs
  app/templates/components/widgets/forms/billing-info.hbs
Labels: fix

#6189 fix: footer overlaps with virtual event side panel
  app/styles/components/stream.scss
Labels: fix

#6180 fix: Virtual Events: Open "Join video" in same tab for "in-house" streams
  app/components/public/session-item.js
  app/components/public/stream/join-video.hbs
  app/components/public/stream/stream-info.hbs
  app/models/video-channel.ts
Labels: fix

#6184 feat: Push and highlight active video stream
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/styles/components/stream.scss
Labels: feature

#6164 fix: Standardize My Tickets page
  app/routes/my-tickets/past.js
  app/routes/my-tickets/upcoming/list.js
  app/templates/components/order-card.hbs
  tests/integration/components/order-card-test.js
Labels: fix

#5997 fix: set min time in calendar
  app/components/schedule.ts
  app/templates/public/schedule.hbs
Labels: fix
