Repository fossasia/open-event-frontend, pull requests merged in 2020-10, with the labels that each got.

#5215 fix: listing privacy shows error in wizard
  app/components/forms/wizard/sessions-speakers-step.js
Labels: fix

#5205 chore: Replace getWithDefault with nullish coalescing
  app/components/modals/cropper-modal.js
  app/components/orders/order-summary.js
  app/controllers/events/view/tickets/add-order.js
  app/router.js
Labels: chore

#5220 fix: change print invoice to download invoice
  app/templates/event-invoice/paid.hbs
  app/templates/event-invoice/review.hbs
Labels: fix

#5223 fix: Invoice UI enhancements
  app/components/ui-table/cell/events/cell-download-invoice.js
  app/components/ui-table/cell/events/cell-event-invoice.js
  app/controllers/account/billing/invoices/list.js
  app/models/event-invoice.js
  app/routes/account/billing/index.js
  app/routes/account/billing/invoices/list.js
  app/templates/account/billing.hbs
  app/templates/account/billing/invoices.hbs
  app/templates/components/ui-table/cell/events/cell-download-invoice.hbs
  app/templates/components/ui-table/cell/events/cell-event-invoice.hbs
  app/templates/event-invoice/review.hbs
  tests/acceptance/invoices-test.js
Labels: fix

#5226 fix: Redirect to login from invoice detail
  app/routes/event-invoice/paid.js
  app/routes/event-invoice/review.js
Labels: fix

#5225 fix: don't jump to main page or step 3 in wizard
  app/controllers/create.js
  app/routes/events/view/edit.js
Labels: fix

#5237 fix: Change event times according to timezone change
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#5241 fix: Revert to ember 3.20.3
  package.json
  yarn.lock
Labels: fix

#5244 chore: Bundle nginx in docker for disabled fastboot
  .dockerignore
  Dockerfile
  config/environment.js
  config/nginx.conf
  scripts/container_start.sh
  scripts/fastboot-server.js
Labels: chore

#5245 fix: Change default API based on environment
  config/environment.js
Labels: fix

#5243 fix: adding table for admin-sales-by-event
  app/controllers/admin/sales/index.js
  app/routes/admin/sales/index.js
  app/templates/admin/sales/index.hbs
  app/templates/components/tables/headers/sort.hbs
  app/templates/components/ui-table/cell/admin/sales/cell-amount.hbs
Labels: fix

#5246 feat: Allow admin to search users by lastName and email
  app/controllers/admin/users/list.js
  app/mixins/ember-table-route.js
  app/routes/admin/users/list.js
  app/templates/components/ui-table/cell/admin/users/cell-created-at.hbs
  app/templates/components/ui-table/cell/admin/users/cell-first-name.hbs
Labels: feature

#5247 feat: Allow admin to see any user's invoice
  app/components/ui-table/cell/admin/sales/invoice-user.hbs
  app/controllers/account/billing/invoices/list.js
  app/controllers/admin/sales/invoices.js
  app/routes/account/billing/invoices/list.js
Labels: feature

#5252 fix: bug with maximum and minimum tickets per order
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#5259 fix: search via user email in order table
  app/routes/events/view/tickets/orders/list.js
Labels: fix

#5265 chore: Configure sentry release and trace sample rate
  app/sentry.ts
  config/environment.js
  package.json
  yarn.lock
Labels: chore

#5266 chore: Disable fastboot test in Travis
  .travis.yml
Labels: chore

#5267 chore: Configure eslint on config folder
  app/models/event-invoice.js
  config/deploy.js
  config/deprecation-workflow.js
  config/environment.js
  package.json
Labels: chore

#5274 chore: Preserve version in docker build
  config/environment.js
  scripts/replace-config.js
Labels: chore

#5275 fix: time error fix in wizard step 5
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: fix

#5285 fix: CFS date field validation working in wizard step 5
  app/components/forms/wizard/sessions-speakers-step.js
Labels: fix

#5287 fix: need to connect to your stripe account error
  app/components/events/view/publish-bar.ts
  app/mixins/event-wizard.js
  app/models/event.js
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#5288 chore: Enable eslint cache
  .gitignore
  .template-lintrc.js
  app/templates/components/ui-table/header-row-filtering.hbs
  config/environment.js
  package.json
Labels: chore

#5286 fix: Disable auto-filling of country name in tax popup
  app/templates/components/modals/tax-info-modal.hbs
Labels: fix

#5292 fix: stripe validation condition fix
  app/models/event.js
Labels: fix

#5294 fix: can send more than one invite
  app/templates/components/modals/add-user-role-modal.hbs
Labels: fix

#5304 fix: Don't check authCode for stripe connection
  app/models/event.js
Labels: fix

#5289 fix: add bottom margin overflow in hastags of event-cards
  app/styles/partials/event-card.scss
  app/templates/components/event-card.hbs
Labels: fix

#5293 fix: Organizer Session Page Table
  app/controllers/events/view/sessions/list.js
  app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs
Labels: fix

#5302 fix: make CFS optional like adding org info wizard step 1
  app/components/forms/wizard/sessions-speakers-step.js
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: fix

#5320 fix: size of state button in sessions table in overview of events
  app/controllers/events/view/sessions/list.js
Labels: fix

#5328 chore: Pin node version to 12.x
  package.json
Labels: chore

#4577 fix: Update email validation
  app/controllers/register.js
Labels: fix

#5333 chore: Use local fonts and no analytics
  app/styles/app.scss
  app/styles/font.scss
  config/environment.js
  public/fonts/lato-v17-latin-100.woff
  public/fonts/lato-v17-latin-100.woff2
  public/fonts/lato-v17-latin-300.woff
  public/fonts/lato-v17-latin-300.woff2
  public/fonts/lato-v17-latin-700.woff
  public/fonts/lato-v17-latin-700.woff2
  public/fonts/lato-v17-latin-900.woff
  public/fonts/lato-v17-latin-900.woff2
  public/fonts/lato-v17-latin-regular.woff
  public/fonts/lato-v17-latin-regular.woff2
Labels: chore

#5346 feat: allow scheduler slot duration of 5 min
  app/components/schedule.hbs
Labels: feature

#5353 fix: show language names in original language
  app/services/l10n.js
Labels: fix

#5356 chore: Deduplicate translations and remove obsolete
  app/adapters/application.js
  app/components/account/contact-info-section.js
  app/components/account/email-preferences-section.js
  app/components/events/view/export/download-common.js
  app/components/forms/admin/settings/system/mail-settings/test-email-form.js
  app/components/forms/login-form.js
  app/components/forms/orders/guest-order-form.js
  app/components/forms/orders/order-form.js
  app/components/forms/reset-password-form.js
  app/components/forms/session-speaker-form.js
  app/components/forms/user-profile-form.js
  app/components/forms/wizard/basic-details-step.js
  app/components/notification-dropdown.js
  app/components/widgets/forms/image-upload.js
  app/controllers/admin/content/translations.js
  app/controllers/event-invoice/paid.js
  app/controllers/events/view/export.js
  app/controllers/events/view/tickets/attendees/list.js
  app/controllers/notifications.js
  app/controllers/oauth/callback.js
  app/controllers/public/index.js
  app/controllers/register.js
  app/mixins/event-wizard.js
  app/mixins/notifications.js
  app/services/auth-manager.js
  app/services/l10n.js
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#5305 fix: Speaker Name Shown in Overview Mode
  app/components/public/session-item.hbs
Labels: fix

#5358 chore: Translated using Weblate (Hindi)
  translations/hi.po
Labels: chore

#5357 fix: Remove divider to resolve UI jumping in session overview card
  app/components/public/session-item.hbs
Labels: fix

#5367 fix: Issues with Modal and Image Cropper position
  app/components/modals/modal-base.js
  app/components/modals/tax-info-modal.js
  app/styles/partials/overrides.scss
  app/templates/components/modals/tax-info-modal.hbs
Labels: fix

#5319 fix: add overflow to notify-modal
  app/components/modals/session-notify-modal.hbs
Labels: fix

#5378 fix: Set valid CFS time range
  app/models/speakers-call.js
Labels: fix

#5291 fix: Add order component for organizers
  app/components/events/events-table.js
  app/components/public/ticket-list.js
  app/controllers/events/view/tickets/add-order.js
  app/templates/components/public/ticket-list.hbs
  app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-price.hbs
  app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-quantity.hbs
  app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-total.hbs
  app/templates/events/view/tickets/add-order.hbs
Labels: fix

#5379 chore: Remove ember-models-table
  app/components/ui-table-select.js
  app/components/ui-table-server.js
  app/components/ui-table.js
  app/components/ui-table/all-columns-hidden.js
  app/components/ui-table/columns-dropdown.js
  app/components/ui-table/component-footer.js
  app/components/ui-table/global-filter.js
  app/components/ui-table/header-filtering-row.js
  app/components/ui-table/header-grouped-row.js
  app/components/ui-table/header-row-filtering.js
  app/components/ui-table/header-row-sorting.js
  app/components/ui-table/header-sorting-row.js
  app/components/ui-table/no-data.js
  app/components/ui-table/numeric-pagination.js
  app/components/ui-table/page-size.js
  app/components/ui-table/row.js
  app/components/ui-table/simple-pagination.js
  app/components/ui-table/table-footer.js
  app/templates/components/ui-table-select.hbs
  app/templates/components/ui-table.hbs
  app/templates/components/ui-table/all-columns-hidden.hbs
  app/templates/components/ui-table/columns-dropdown.hbs
  app/templates/components/ui-table/component-footer.hbs
  app/templates/components/ui-table/global-filter.hbs
  app/templates/components/ui-table/header-row-filtering.hbs
  app/templates/components/ui-table/header-row-sorting.hbs
  app/templates/components/ui-table/no-data.hbs
  app/templates/components/ui-table/numeric-pagination.hbs
  app/templates/components/ui-table/page-size.hbs
  app/templates/components/ui-table/row.hbs
  app/templates/components/ui-table/simple-pagination.hbs
  app/templates/components/ui-table/table-footer.hbs
  app/themes/icon-pack.js
  app/themes/semantic.js
  package.json
  tests/integration/components/events/events-table-test.js
  tests/integration/components/ui-table-select-test.js
  tests/integration/components/ui-table-server-test.js
  tests/integration/components/ui-table-test.js
  tests/integration/components/ui-table/all-columns-hidden-test.js
  tests/integration/components/ui-table/cell/events/view/tickets/cell-add-order-price-test.js
  tests/integration/components/ui-table/columns-dropdown-test.js
  tests/integration/components/ui-table/component-footer-test.js
  tests/integration/components/ui-table/global-filter-test.js
  tests/integration/components/ui-table/header-row-filtering-test.js
  tests/integration/components/ui-table/header-row-sorting-test.js
  tests/integration/components/ui-table/no-data-test.js
  tests/integration/components/ui-table/numeric-pagination-test.js
  tests/integration/components/ui-table/page-size-test.js
  tests/integration/components/ui-table/row-test.js
  tests/integration/components/ui-table/simple-pagination-test.js
  tests/integration/components/ui-table/table-footer-test.js
  yarn.lock
Labels: chore

#5359 fix: Allow organizer to add speaker without email
  app/controllers/events/view/speakers/create.js
  app/controllers/events/view/speakers/edit.js
Labels: fix

#5383 fix: take out search box from sponsor table
  app/templates/components/events/view/overview/event-sponsors.hbs
  app/templates/components/tables/default.hbs
Labels: fix

#5384 chore: Translated using Weblate (German)
  translations/de.po
Labels: chore

#5386 chore: Misc maintainence fixes
  app/components/modals/tax-info-modal.js
  app/controllers/events/view/tickets/add-order.js
  app/styles/partials/overrides.scss
  package.json
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
  yarn.lock
Labels: chore

#5389 chore: Translated using Weblate (German)
  translations/de.po
Labels: chore

#5391 fix: spelling and sort languages in alphabetical order
  app/services/l10n.js
Labels: fix

#5390 feat: View Action for Speaker
  app/controllers/events/view/speakers/list.js
  app/controllers/public/speaker/view.js
  app/router.js
  app/routes/public/speaker/view.js
  app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs
  app/templates/public/speaker/view.hbs
  tests/unit/routes/public/speaker/view-test.js
Labels: feature

#5394 chore: add few hindi messages translations
  translations/hi.po
Labels: chore

#5402 chore: Translated using Weblate (German)
  translations/de.po
Labels: chore

#5403 chore: Translated using Weblate (Hindi)
  translations/hi.po
Labels: chore

#5404 chore: Allow l10n of footer dynamic items
  app/routes/pages.js
  app/templates/components/footer-main.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#5405 fix: Add extra value paths for view speaker handler
  app/controllers/events/view/speakers/list.js
Labels: fix

#5411 fix: Recursively look for route params for private CFS
  app/routes/public/cfs/index.js
Labels: fix

#5414 fix: Set moment locale according to chosen language
  app/services/l10n.js
  app/utils/loader.ts
  config/environment.js
  ember-cli-build.js
Labels: fix

#5392 feat: Add to Google Calendar
  app/components/public/add-to-calender.hbs
  app/components/public/add-to-calender.ts
  app/components/public/social-links.js
  app/styles/partials/utils.scss
  app/templates/public.hbs
Labels: feature

#5432 fix: Only prevent fulfilled or pending order users from deletion
  app/routes/account/danger-zone.js
Labels: fix

#5431 feat: Allow users to set password while registering for order
  app/components/forms/orders/guest-order-form.js
  app/controllers/public/index.js
  app/templates/components/forms/orders/guest-order-form.hbs
Labels: feature
