Repository fossasia/open-event-frontend, pull requests merged in 2021-09, with the labels that each got.

#7728 fix: alignment of followers table
  app/styles/partials/utils.scss
  app/templates/components/tables/default.hbs
  app/templates/groups/edit/followers.hbs
Labels: fix

#7749 fix: view group button
  app/templates/components/group-nav.hbs
Labels: fix

#7752 fix: adding new videoroom
  app/components/forms/events/view/videoroom-form.js
Labels: fix

#7756 fix: remove view button from create group page
  app/templates/components/group-nav.hbs
Labels: fix

#7755 chore: add alpha stage banner in group
  app/templates/components/group-header.hbs
Labels: chore

#7714 feat: Groups Team page: add sub page for permissions
  app/router.js
  app/routes/groups/team/permissions.ts
  app/templates/groups/team.hbs
  app/templates/groups/team/permissions.hbs
  tests/unit/routes/groups/team/permissions-test.ts
Labels: feature

#7772 fix: group edit tabs
  app/templates/groups/edit/followers.hbs
Labels: fix

#7794 fix: empty error box during oneclicksignup
  app/controllers/public/index.js
Labels: fix

#7791 fix: modified translations for some areas
  app/components/forms/events/view/videoroom-form.hbs
  app/controllers/events/view/videoroom/list.js
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/components/forms/orders/cancel-order.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#7781 fix: Fix and Improve Registration Box Design
  app/styles/libs/_helpers.scss
  app/styles/pages/events.scss
  app/templates/public/index.hbs
Labels: fix

#7808 fix: Tax on registration ticket
  app/templates/public/index.hbs
Labels: fix

#7818 fix: Change color of "Order" button on registration events
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#7821 fix: Box to enter amount for donation registration missing
  app/controllers/public/index.js
  app/templates/public/index.hbs
Labels: fix

#7819 fix: Update Ticket and Registration Section on Event Public Page
  app/controllers/public/index.js
  app/models/ticket.js
  app/templates/components/public/ticket-list.hbs
  app/templates/public/index.hbs
Labels: bug, enhancement, fix

#7770 fix:workaround for user not able to upload slides on old sessions
  app/templates/components/forms/session-section.hbs
Labels: fix

#7823 fix: Ticket Deletion only when they don't have orders
  app/helpers/confirm.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/confirm-modal.hbs
Labels: bug, enhancement, fix

#7717 chore: gitpod config
  .gitpod.dockerfile
  .gitpod.yml
Labels: chore

#7834 fix: Only Show Registration tickets which are active
  app/templates/public/index.hbs
Labels: bug, fix

#7843 fix: Calculate Tax properly
  app/models/order.js
  app/templates/components/orders/order-summary.hbs
Labels: fix

#7847 fix: Calculate Tax Properly
  app/models/order.js
Labels: bug, fix

#7854 fix: public url under admin groups list
  app/models/group.js
Labels: fix

#7853 fix: Tax Issue Completed
  app/models/order.js
Labels: bug, fix

#7857 fix: change api host to test server
  .env.example
Labels: fix

#7730 fix: Add option to resend invitation and to delete team member and show group owner in team table list
  app/controllers/groups/team.js
  app/templates/groups/team.hbs
Labels: fix

#7845 fix: add group widget button
  app/templates/public.hbs
Labels: fix

#7849 fix: user not able to delete other followers
  app/components/forms/group/group-view.js
  app/controllers/group-public.js
  app/models/user.js
  app/routes/group-public.js
  app/serializers/groups.js
  app/templates/components/forms/group/group-view.hbs
  app/templates/group-public.hbs
Labels: fix

#7859 fix: group name not showing in admin group table
  app/templates/components/ui-table/cell/admin/groups/cell-group-name.hbs
Labels: fix

#7863 fix: Organizer Ticket Overview Page: Missing Currency for Sales
  app/controllers/events/view/tickets/index.js
Labels: bug, fix

#7798 feat: Add option "Purchase on invoice" to Offline Purchase Methods.
  app/components/forms/wizard/basic-details-step.js
  app/controllers/orders/new.js
  app/models/event.js
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/orders/ticket-holder.hbs
Labels: feature

#7872 fix: preselect ticket if only one ticket in ocs event
  app/routes/public/index.js
Labels: fix

#7864 fix: standardize follow/unfollow button in groups
  app/styles/pages/public-event.scss
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/group-card.hbs
Labels: fix
