Repository fossasia/open-event-frontend, pull requests merged in 2021-08, with the labels that each got.

#7623 fix: allow attendee multiple day checkin
  app/components/ui-table/cell/events/view/tickets/attendees/cell-action.js
  app/controllers/events/view/tickets/attendees/list.js
  app/models/attendee.js
  app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-action.hbs
Labels: fix

#7577 feat: error while adding moderator.
  app/components/forms/events/view/videoroom-form.js
  app/components/forms/session-speaker-form.js
Labels: feature, needs-review

#7646 fix: assert.ok to specifics
  tests/integration/components/create-session-message-test.js
  tests/integration/components/notification-dropdown-test.js
  tests/integration/components/order-card-test.js
  tests/integration/components/side-bar-test.js
  tests/integration/components/tabbed-navigation-test.js
  tests/integration/components/unverified-user-message-test.js
  tests/integration/components/welcome-header-test.js
Labels: fix

#7637 feat: add followers user profile
  app/routes/groups/view.js
  app/templates/components/forms/group/group-view.hbs
Labels: feature

#7621 feat: Add groups filter in explore page.
  app/components/explore/side-bar.js
  app/controllers/application.js
  app/controllers/explore/events.js
  app/controllers/explore/groups.js
  app/router.js
  app/routes/explore.js
  app/routes/explore/events.js
  app/routes/explore/groups.js
  app/templates/components/explore/side-bar.hbs
  app/templates/explore/events.hbs
  app/templates/explore/groups.hbs
Labels: needs-review

#7604 feat: Announcement of event and fix bugs in groups
  app/components/event-card.js
  app/components/forms/group/group-events-form.js
  app/models/event.js
  app/routes/groups/edit/events.js
  app/templates/components/event-card.hbs
  app/templates/components/forms/group/group-events-form.hbs
  app/templates/groups/edit/events.hbs
Labels: feature, needs-review, WIP

#7656 fix: Group edit page: add teams tab
  app/components/group-nav.js
  app/templates/components/group-nav.hbs
  app/templates/groups/edit/followers.hbs
  app/templates/groups/team.hbs
Labels: fix

#7667 fix: change text to "Search" on search bar
  app/templates/components/nav-bar.hbs
  app/templates/components/side-bar.hbs
  tests/integration/components/nav-bar-test.js
Labels: fix

#7678 fix: search box at followers page
  app/routes/groups/edit/followers.js
  app/templates/groups/edit/followers.hbs
Labels: fix

#7680 fix: make areas translatable
  app/components/forms/events/view/videoroom-form.hbs
  app/controllers/events/view/videoroom/list.js
  app/templates/events/view/videoroom/list.hbs
Labels: fix

#7662 fix: formatting localized currency
  app/templates/components/modals/paytm-otp.hbs
  app/templates/components/modals/paytm-payment-options.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-value.hbs
Labels: fix

#7685 fix: change default ticket sales time to event end time
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#7668 fix: Navbar consistent throughout group pages
  app/components/nav-bar.js
  app/templates/components/events/imports-history-section.hbs
  app/templates/components/forms/group/group-events-form.hbs
  app/templates/components/forms/group/group-settings-form.hbs
  app/templates/components/group-card.hbs
  app/templates/groups/edit/followers.hbs
  app/templates/groups/team.hbs
Labels: fix

#7507 fix: adding one click signup
  app/components/forms/wizard/basic-details-step.js
  app/controllers/orders/new.js
  app/controllers/public/index.js
  app/models/event.js
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
  app/templates/public/index.hbs
Labels: fix

#7625 feat: Admin Sales Page Export table as CSV
  app/controllers/admin/sales/index.js
  app/controllers/events/view/sessions.js
  app/templates/admin/sales/index.hbs
Labels: feature

#7679 feat: followers table export as csv
  app/controllers/groups/edit/followers.js
  app/templates/groups/edit/followers.hbs
Labels: feature

#7596 feat: Multiple documents for Session Speakers
  app/components/forms/session-section.js
  app/components/forms/session-speaker-form.js
  app/components/public/session-documents.hbs
  app/components/public/session-documents.js
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/mixins/custom-form.js
  app/models/custom-form.js
  app/models/session.js
  app/templates/components/events/view/overview/session-view.hbs
  app/templates/components/forms/events/view/edit-session.hbs
  app/templates/components/forms/session-section.hbs
  app/templates/public/session/view.hbs
  app/utils/color.ts
Labels: feature

#7703 fix: add popup msg on "hide in scheduler" checkbox
  app/components/forms/wizard/sessions-speakers-step.js
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: fix

#7700 fix: ticket layout in my ticket
  app/styles/libs/_helpers.scss
  app/templates/components/order-card.hbs
Labels: fix

#7708 chore: fix translatable areas
  app/components/public/stream/chat-panel.ts
  app/controllers/register.js
  app/templates/components/ui-table/cell/admin/groups/cell-group-name.hbs
Labels: chore

#7704 fix: adding paid payment option, and registration instead of ticket
  app/components/forms/wizard/basic-details-step.js
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/orders/order-summary.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: fix

#7642 feat: apply sorting by amount by sales in admin.sales page
  app/controllers/admin/sales/index.js
  app/models/admin-sales-by-event.js
Labels: feature, blocked-by-server

#7734 fix: Schedule list view duplicated, empty sessions
  app/templates/public/sessions.hbs
Labels: fix

#7729 fix: one click signup enhancement
  app/controllers/public/index.js
  app/templates/public/index.hbs
Labels: fix
