Repository fossasia/open-event-frontend, pull requests merged in 2021-05, with the labels that each got.

#7231 fix: Show more readable error msg on duplicate role invite
  app/controllers/events/view/settings/options.js
Labels: fix

#7226 fix: Show event link if event is online event in "Location Field" in calenders(other than ical)
  app/controllers/public.js
Labels: fix

#7188 fix: take out https from video source URL
  app/components/ui-table/cell/events/view/videoroom/cell-video-url.js
  app/templates/components/ui-table/cell/events/view/videoroom/cell-video-url.hbs
Labels: fix

#7254 fix: Admin: Renamed video-channels to video
  app/templates/admin.hbs
Labels: fix

#7253 fix: Show event link if event is online event in "Location Field"
  app/components/public/add-to-calender.ts
Labels: fix

#7268 fix: Apply Code Ui Changes
  app/templates/components/public/ticket-list.hbs
Labels: fix

#6784 fix: preselect ticket buyer as holder for existing buyers
  app/components/forms/orders/order-form.js
Labels: fix

#7142 fix: increase width of room password column in event video room table
  app/controllers/events/view/videoroom/list.js
Labels: fix

#7298 fix: remove \n, \r from rich text editor and remove "line feed" character.
  app/components/widgets/forms/rich-text-editor.js
Labels: fix

#7304 fix: order issue regarding billing info
  app/controllers/orders/new.js
Labels: fix

#7305 fix: paypal version downgrade
  package.json
  yarn.lock
Labels: fix

#7313 chore: Add t-var for translations
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/forms/speaker-section.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/widgets/forms/billing-info.hbs
Labels: chore

#7320 fix: linkify button ui for mobile
  app/templates/components/widgets/forms/rich-text-editor.hbs
Labels: fix

#7284 fix: Password input box width greater than login and register form.
  app/styles/libs/_helpers.scss
  app/templates/components/forms/login-form.hbs
  app/templates/components/forms/register-form.hbs
Labels: fix

#7314 fix: refresh google iframe
  app/components/public/exhibition-view.js
  app/templates/components/public/exhibition-view.hbs
Labels: fix

#7338 fix: clear html tags from organizer exhibitor description
  app/controllers/events/view/exhibitors/list.js
Labels: fix

#7336 fix: add translations in order form
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#7337 fix: After "clearing filter" previous filter option should not be displayed as active
  app/controllers/public.js
  app/controllers/public/sessions.js
  app/templates/public.hbs
  app/templates/public/sessions.hbs
Labels: fix

#7332 fix: Text changes from record to enable recording.
  app/components/forms/events/view/videoroom-form.hbs
Labels: fix

#7154 fix: remove edit video page error
  app/components/forms/events/view/videoroom-form.js
  app/components/ui-table/cell/cell-duration.hbs
  app/components/ui-table/cell/cell-duration.js
  app/models/video-recording.ts
  app/models/video-stream.ts
Labels: blocked-by-server, fix

#7329 fix: event video room creation
  app/controllers/events/view/videoroom/list.js
Labels: fix

#7350 fix: Ratings: Re-add rating columns to all session tables
  app/controllers/admin/sessions/list.js
  app/controllers/events/view/sessions/list.js
  app/routes/admin/sessions/list.js
  app/templates/admin/sessions/list.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-rating.hbs
Labels: fix

#7359 fix:Message when trying to create an event with a non verified account is not helpful.
  app/components/events/view/publish-bar.ts
Labels: fix
