Repository fossasia/open-event-frontend, pull requests merged in 2021-02, with the labels that each got.

#6506 feat: Add exhibitor management pages
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/components/forms/events/view/exhibitors/exhibitor-form.ts
  app/components/forms/form.hbs
  app/components/forms/form.ts
  app/components/ui-table/cell/cell-image.js
  app/components/widgets/forms/link-field.hbs
  app/controllers/events/view/exhibitors/list.js
  app/models/event.js
  app/models/exhibitor.ts
  app/router.js
  app/routes/events/view/exhibitors/create.js
  app/routes/events/view/exhibitors/edit.js
  app/routes/events/view/exhibitors/index.ts
  app/routes/events/view/exhibitors/list.js
  app/styles/libs/stripe_connect.scss
  app/templates/components/ui-table/cell/cell-actions.hbs
  app/templates/components/ui-table/cell/cell-image.hbs
  app/templates/components/ui-table/cell/cell-url.hbs
  app/templates/components/widgets/forms/image-upload.hbs
  app/templates/events/view.hbs
  app/templates/events/view/exhibitors/create.hbs
  app/templates/events/view/exhibitors/edit.hbs
  app/templates/events/view/exhibitors/index.hbs
  app/templates/events/view/exhibitors/list.hbs
  app/templates/orders/pending.hbs
  tests/integration/components/ui-table/cell/cell-image-test.js
  tests/unit/controllers/events/view/exhibitors/list-test.ts
  tests/unit/models/exhibitor-test.ts
  tests/unit/routes/events/view/exhibitors/create-test.ts
  tests/unit/routes/events/view/exhibitors/edit-test.ts
  tests/unit/routes/events/view/exhibitors/list-test.ts
Labels: feature

#6567 fix: adding Without session filter to speaker
  app/models/event-statistics-general.js
  app/routes/events/view/speakers/list.js
  app/templates/components/events/view/overview/speaker-session.hbs
  app/templates/events/view/speakers.hbs
Labels: fix

#6575 chore: Hide groups nav item
  app/templates/components/nav-bar.hbs
Labels: chore

#6576 chore: Hide map on search page
  app/templates/components/explore/side-bar.hbs
Labels: chore

#6577 fix: Sort sessions by submitted date
  app/controllers/events/view/sessions/list.js
Labels: fix

#6556 fix: don't show links if field was empty
  app/components/widgets/forms/link-field.ts
  tests/integration/components/widgets/forms/link-field-test.ts
Labels: fix

#6578 fix: Gender value set to random string
  app/templates/components/forms/speaker-section.hbs
Labels: fix

#6580 fix: Show groups nav items to admin
  app/templates/components/nav-bar.hbs
Labels: fix

#6581 fix: Improve speaker form error handling
  app/controllers/public/cfs/edit-speaker.js
  app/services/error-handler.js
  app/templates/components/forms/session-speaker-form.hbs
Labels: fix

#6590 fix: Pass event as prop to speaker item to make link
  app/templates/components/public/speaker-item.hbs
  app/templates/public/speakers.hbs
Labels: fix

#6583 feat: Reorder Speakers
  app/controllers/events/view/speakers/reorder.ts
  app/models/speaker.js
  app/router.js
  app/routes/events/view/speakers/list.js
  app/routes/events/view/speakers/reorder.js
  app/routes/public/index.js
  app/routes/public/speakers.js
  app/styles/partials/utils.scss
  app/templates/components/public/speaker-item.hbs
  app/templates/events/view/speakers.hbs
  app/templates/events/view/speakers/reorder.hbs
  tests/unit/controllers/events/view/speakers/reorder-test.ts
  tests/unit/routes/events/view/speakers/reorder-test.ts
Labels: feature

#6582 fix: Left Sidebar Not moving down
  app/styles/pages/public-event.scss
  app/styles/pages/public.scss
  app/styles/partials/footer.scss
  app/templates/public.hbs
Labels: fix

#6602 feat: enhance cfs mail
  app/controllers/public/cfs/new-session.js
  app/routes/public/cfs/new-session.js
Labels: feature

#6283 fix: all date filter
  app/components/explore/side-bar.js
  app/routes/explore.js
  app/templates/explore.hbs
Labels: fix

#6492 feat: add ticket cancellation box
  app/controllers/orders/view.js
  app/templates/components/forms/orders/cancel-order.hbs
  app/templates/orders/view.hbs
Labels: feature

#6592 fix: add proper margin to buttons
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#6585 fix: move social media to other tab in admin section
  app/controllers/admin/settings/social-media.js
  app/router.js
  app/routes/admin/settings/social-media.js
  app/templates/admin/settings.hbs
  app/templates/admin/settings/social-media.hbs
  app/templates/components/forms/admin/settings/system-form.hbs
Labels: fix

#6591 fix: order card aligned in mobile view
  app/templates/components/order-card.hbs
Labels: fix

#6619 fix: removing extra line breaks at the end of para on public page
  app/components/widgets/forms/rich-text-editor.js
Labels: fix

#6637 fix: session/speaker form section
  app/templates/components/forms/session-section.hbs
  app/templates/components/forms/speaker-section.hbs
Labels: fix

#6635 fix: Spacing above date widget area too large
  app/components/public/add-to-calender.hbs
  app/templates/public.hbs
Labels: fix

#6638 feat: Add exhibitor status and social link
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/components/forms/events/view/exhibitors/exhibitor-form.ts
  app/controllers/events/view/exhibitors/list.js
  app/models/exhibitor.ts
Labels: feature

#6618 fix: Hide sessions from speaker item when schedule is not published
  app/routes/public/session/view.js
  app/templates/components/public/speaker-item.hbs
Labels: fix

#6650 fix: Store frozen date array for sessions page
  app/controllers/public/sessions.js
Labels: fix

#6620 feat: Add "Reply-to" to organizers in session notify
  app/components/modals/session-notify-modal.hbs
  app/components/modals/session-notify-modal.js
Labels: feature

#6652 feat: Session Form: Add options for social links
  app/components/public/session-item.hbs
  app/mixins/custom-form.js
  app/models/custom-form.js
  app/models/session.js
Labels: feature

#6666 fix: make reply-to readable in session notify modal
  app/components/modals/session-notify-modal.hbs
Labels: fix

#6669 fix: Add block display to Join Video Channel
  app/components/public/stream/stream-info.hbs
Labels: fix

#6657 feat: adding youtube & vimeo
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/public/stream/video-stream.hbs
  app/components/public/stream/video-stream.ts
  app/models/video-channel.ts
Labels: feature

#6670 fix: organizer search by track, speaker, session
  app/routes/events/view/sessions/list.js
Labels: fix

#6568 feat: Add public page of exhibitors and view page of exhibitor
  app/components/public/exhibitor-item.js
  app/components/public/side-menu.js
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/controllers/public/exhibition/view.js
  app/router.js
  app/routes/public/exhibition/index.js
  app/routes/public/exhibition/view.js
  app/templates/components/public/exhibitor-item.hbs
  app/templates/components/public/side-menu.hbs
  app/templates/public.hbs
  app/templates/public/exhibition/index.hbs
  app/templates/public/exhibition/view.hbs
  app/utils/event.ts
  public/images/placeholders/Other.jpg
Labels: feature

#6664 feat: Add user favourite session
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/models/session.js
  app/models/user-favourite-session.ts
  app/models/user.js
  app/routes/public/sessions.js
  tests/unit/models/user-favourite-session-test.ts
Labels: feature

#6088 feat: Schedule: Implement "Add to calendar" for a complete schedule
  app/components/public/add-to-calender.hbs
  app/components/public/add-to-calender.ts
Labels: feature

#6665 feat: Organizer Msg: Add Sanitization
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/orders/after-order-message.hbs
Labels: feature

#6676 feat: Allow sorting of fields for Attendee, Speaker & Session Form
  app/components/forms/orders/order-form.js
  app/components/forms/session-speaker-form.js
  app/components/forms/wizard/attendee-step.js
  app/components/forms/wizard/custom-forms/table.hbs
  app/components/forms/wizard/custom-forms/table.ts
  app/components/forms/wizard/sessions-speakers-step.js
  app/controllers/events/view/speakers/list.js
  app/mixins/custom-form.js
  app/models/custom-form.js
  app/styles/libs/_helpers.scss
  app/templates/components/forms/wizard/attendee-step.hbs
Labels: feature

#6692 feat: my schedule filter
  app/components/public/stream/video-stream.ts
  app/controllers/public/sessions.js
  app/routes/public/sessions.js
  app/templates/public.hbs
  app/templates/public/sessions.hbs
Labels: feature

#6696 fix: Only allow one email address of "event owner" in the Reply-to email
  app/components/modals/session-notify-modal.hbs
  app/components/modals/session-notify-modal.js
Labels: fix

#6719 fix: CfS: "Edit Speaker Details" button not available after CfS is closed
  app/templates/components/public/call-for-speakers.hbs
Labels: fix

#6723 feat: Exhibitor Page: Add Twitter Widget
  app/styles/partials/utils.scss
  app/templates/components/widgets/twitter-timeline.hbs
  app/templates/public/exhibition/view.hbs
Labels: feature

#6724 feat: Reorder exhibitors
  app/controllers/events/view/exhibitors/reorder.ts
  app/models/exhibitor.ts
  app/router.js
  app/routes/events/view/exhibitors/reorder.js
  app/routes/public/exhibition/index.js
  app/templates/events/view/exhibitors/list.hbs
  app/templates/events/view/exhibitors/reorder.hbs
  tests/unit/controllers/events/view/exhibitors/reorder-test.ts
  tests/unit/routes/events/view/exhibitors/reorder-test.ts
Labels: feature

#6690 feat: Add contact exhibitor & Improve Exhibitor Page
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/components/forms/events/view/exhibitors/exhibitor-form.ts
  app/controllers/events/view/exhibitors/list.js
  app/controllers/public/exhibition/view.js
  app/models/exhibitor.ts
  app/templates/public/exhibition/view.hbs
Labels: feature

#6730 fix: Prevent session accordion expansion on icon click
  app/components/public/session-item.hbs
  app/helpers/prevent-bubbling.js
Labels: fix

#6726 feat: Add single "add to calendar" button.
  app/components/modals/add-to-calendar.js
  app/components/public/add-to-calender.hbs
  app/components/public/add-to-calender.ts
  app/templates/components/modals/add-to-calendar.hbs
Labels: feature

#6671 feat: Add My Speaker Session filter
  app/routes/public/sessions.js
  app/templates/public/sessions.hbs
Labels: feature

#6728 fix: Add top margin to footer
  app/components/footer-main.js
  app/styles/partials/utils.scss
Labels: fix

#6727 fix: Allow CFS access to linked speaker
  app/components/public/add-to-calender.ts
  app/models/event.js
  app/routes/public/cfs/edit-session.js
  app/routes/public/cfs/index.js
  app/routes/public/cfs/view-session.js
  app/routes/public/cfs/view-speaker.js
Labels: fix

#6739 fix: ticket quantity numbers
  app/helpers/ticket-attendees.js
  app/templates/components/orders/order-summary.hbs
  tests/integration/helpers/ticket-attendees-test.js
Labels: fix

#6743 feat: Exhibitor: Add extra social links
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/components/forms/events/view/exhibitors/exhibitor-form.ts
  app/controllers/public/exhibition/view.js
  app/models/exhibitor.ts
  app/templates/components/public/social-links.hbs
  app/templates/public/exhibition/view.hbs
Labels: feature

#6746 fix: Add checkbox in session card
  app/components/public/session-item.hbs
  app/components/public/session-item.js
Labels: fix

#6769 fix: exhibitor page search
  app/routes/events/view/exhibitors/list.js
Labels: fix

#6748 fix: Prevent resetting of timezone choice while using any filter.
  app/components/widgets/time-zone-picker.hbs
  app/components/widgets/time-zone-picker.ts
Labels: fix

#6775 fix: invalid date to not yet scheduled
  app/templates/public/sessions.hbs
Labels: fix

#6778 fix: Mobile Event Pages: Spacing and icon for event pages
  app/templates/components/public/side-menu.hbs
  app/templates/public/exhibition/index.hbs
  app/templates/public/speakers.hbs
Labels: fix

#6751 feat: Enable user to get personal schedule added to calendar
  app/components/modals/add-to-calendar.js
  app/components/public/add-to-calender.hbs
  app/components/public/add-to-calender.ts
Labels: feature

#6777 fix: Exhibitors Pages thumbnail image
  app/models/exhibitor.ts
  app/templates/components/public/exhibitor-item.hbs
Labels: fix

#6791 fix: Schedule: Add list and calendar button to schedule page
  app/styles/partials/utils.scss
  app/templates/public/schedule.hbs
  app/templates/public/sessions.hbs
Labels: fix

#6797 feat: Add user profile name and public to user
  app/models/user.js
  app/templates/components/forms/user-profile-form.hbs
Labels: feature

#6810 feat: Add user favourite avatars on session page
  app/models/exhibitor.ts
  app/models/session.js
  app/routes/public/session/view.js
  app/templates/public/session/view.hbs
Labels: feature

#6815 chore: Update translations
  app/components/public/add-to-calender.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#6793 fix: Join event panel opening
  app/components/public/stream/join-video.ts
  app/controllers/public.js
  app/templates/public.hbs
Labels: fix

#6806 fix: Public Event Page: Right hand side
  app/components/public/add-to-calender.hbs
  app/components/public/social-links.js
  app/styles/partials/utils.scss
  app/templates/components/public/social-links.hbs
  app/templates/public.hbs
Labels: fix

#6795 fix: join event button should open side_panel on same page.
  app/components/public/stream/join-video.ts
Labels: fix

#6824 feat: Add clear all filters icon next to sort order and change minus icon to clear filter icon
  app/components/icons/clear-filter.hbs
  app/templates/public.hbs
  app/templates/public/sessions.hbs
Labels: feature

#6828 fix: selecting/unselecing favourite sessions
  app/models/session.js
Labels: fix

#6849 fix: move exhibitor slides down to video
  app/templates/public/exhibition/view.hbs
Labels: fix

#6827 fix: Cannot progress without adding form fields in "switched off" sponsor step "Field may not be null"
  app/components/forms/wizard/sponsors-step.js
  app/templates/components/forms/wizard/sponsors-step.hbs
Labels: fix

#6822 feat: Add user schedule page
  app/components/public/session-item.hbs
  app/models/event.js
  app/models/session.js
  app/models/user.js
  app/router.js
  app/routes/public/sessions/user/view.ts
  app/templates/public/session/view.hbs
  app/templates/public/session/view/user/view.hbs
  app/templates/public/sessions.hbs
Labels: feature

#6785 feat: Public Schedule: Add dropdown filter for session typ
  app/controllers/public.js
  app/routes/public/sessions.js
  app/templates/public.hbs
  app/templates/public/sessions.hbs
Labels: feature

#6854 chore: Make root font size 16px
  app/styles/app.scss
Labels: chore

#6853 fix: Public Schedule: Date filters text not in middle, get rid of empty space
  app/styles/app.scss
  app/styles/libs/_helpers.scss
  app/templates/public/sessions.hbs
Labels: fix

#6860 fix: Show filters on sessions page
  app/templates/public.hbs
Labels: fix

#6759 feat: Exhibitor: Jitsi Integration
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/components/public/stream/join-video.ts
  app/controllers/public/exhibition/view.js
  app/models/exhibitor.ts
  app/router.js
  app/routes/public/exhibition/video.js
  app/routes/public/exhibition/view.js
  app/services/event.ts
  app/templates/public/exhibition/video.hbs
  app/templates/public/exhibition/view.hbs
  tests/unit/services/event-test.ts
Labels: Priority: Very High, feature

#6809 fix: Renaming room does not rename it on the video edit page
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
Labels: fix

#6805 fix: add autoplay for youtube and vimeo
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/public/stream/video-stream.hbs
  app/models/video-stream.ts
Labels: fix
