Repository fossasia/open-event-frontend, pull requests merged in 2021-03, with the labels that each got.

#6868 fix: full screen for calendar view
  app/controllers/public/schedule.js
  app/templates/public/schedule.hbs
Labels: fix

#6881 fix: Public Speaker Page/Schedule Website links of speaker missing
  app/components/public/session-item.hbs
  app/components/public/speaker-item.js
  app/templates/components/public/speaker-item.hbs
Labels: fix

#6875 feat: Public Speakers Page: Add search box to search for a speaker name
  app/controllers/public/speakers.js
  app/routes/public/speakers.js
  app/templates/public/speakers.hbs
Labels: feature

#6886 fix: Youtube: Always implement modest branding
  app/components/public/session-item.hbs
  app/components/public/stream/video-stream.hbs
  app/templates/public/exhibition/view.hbs
Labels: fix

#6894 fix: Make order form email readonly
  app/controllers/orders/new.js
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#6890 fix: overlapping of minimise button of side_panel
  app/components/public/stream/side-panel.hbs
Labels: fix

#6820 fix: "Join Event" button experience for users without a ticket
  app/components/public/stream/join-video.hbs
  app/components/public/stream/join-video.ts
  app/controllers/public.js
  app/controllers/public/schedule.js
Labels: fix

#6897 fix: default calendar view on public page
  app/components/schedule.hbs
  app/components/schedule.ts
Labels: fix

#6899 feat: Youtube and Vimeo: allow looping videos
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/public/stream/video-stream.hbs
  app/models/video-stream.ts
Labels: feature

#6851 fix: session view page error on clicking join event
  app/components/public/stream/join-video.ts
Labels: fix

#6876 feat: Add favourite count and sort by popularity
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/controllers/public/sessions.js
  app/models/session.js
  app/styles/app.scss
  app/templates/public/sessions.hbs
Labels: Work in Progress, feature

#6807 fix: Side Navbar made equal to calendar
  app/styles/components/scheduler.scss
  app/templates/events/view/scheduler.hbs
Labels: fix

#6905 fix: make fields translatable on attendee wizard
  app/models/custom-form.js
  app/templates/components/public/ticket-list.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: fix

#6742 fix: Standardize headings, add spacing and add button to view more speakers
  app/components/public/featured-speaker-list.js
  app/components/public/side-menu.js
  app/components/public/sponsor-list.hbs
  app/components/public/stream/side-panel.ts
  app/services/event.ts
  app/templates/components/public/event-map.hbs
  app/templates/components/public/featured-speaker-list.hbs
  app/templates/public/index.hbs
  app/utils/event.ts
  tests/integration/components/public/featured-speaker-list-test.js
Labels: fix

#6911 fix: Make speaker email matching case insensitive
  app/routes/public/cfs/view-session.js
  app/routes/public/cfs/view-speaker.js
Labels: fix

#6912 fix: Match speaker email after lower casing
  app/templates/public/cfs/view-session.hbs
Labels: fix

#6920 fix: Public Event Page: Improve ticket box
  app/templates/components/public/ticket-list.hbs
Labels: fix

#6919 fix: Public Schedule & Speakers: Reset filters on navigation
  app/templates/components/public/side-menu.hbs
Labels: fix

#6915 fix: unload microlocation video-room
  app/routes/events/view/videoroom/create.js
  app/routes/events/view/videoroom/edit.js
Labels: fix

#6940 fix: Schedule: Always show heading "Session Types" on top of filter
  app/templates/public.hbs
Labels: fix

#6945 fix: Session invalidation logic
  app/services/auth-manager.js
Labels: fix

#6949 fix: Public Schedule Add a pop-up message to the central Filter
  app/templates/public/sessions.hbs
Labels: fix

#6928 fix: add option "Add Related Session"
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/controllers/public/exhibition/view.js
  app/models/exhibitor.ts
  app/models/session.js
  app/routes/events/view/exhibitors/create.js
  app/routes/events/view/exhibitors/edit.js
  app/routes/public/exhibition/view.js
  app/templates/events/view/exhibitors/create.hbs
  app/templates/events/view/exhibitors/edit.hbs
  app/templates/public/exhibition/view.hbs
Labels: fix

#6953 fix: change position exhibition video & add heading above contact
  app/templates/public/exhibition/view.hbs
Labels: fix

#6957 fix: Show featured events till they end
  app/routes/index.js
Labels: fix

#6958 feat: Add Rocket Chat Settings
  app/models/setting.js
  app/templates/components/forms/admin/settings/system-form.hbs
Labels: feature

#6887 fix: change sidepanel style
  app/components/public/stream/side-panel.hbs
  app/styles/components/stream.scss
  app/templates/public.hbs
Labels: fix

#6961 fix: "Get in touch" heading should only show up if there is actually a button "contact" or "email"
  app/controllers/public/exhibition/view.js
Labels: fix

#6964 fix: allow editing of event video room name
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/controllers/events/view/videoroom/list.js
Labels: fix

#6966 fix: add hidden in scheduler for rooms
  app/components/modals/add-room-modal.hbs
  app/controllers/events/view/scheduler.js
  app/models/microlocation.ts
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/public.hbs
Labels: fix

#6891 feat: Virtual Exhibition: Add a "< previous | next >" option
  app/controllers/public/exhibition/view.js
  app/routes/public/exhibition/view.js
  app/templates/public/exhibition/view.hbs
Labels: feature

#6973 fix: Show all video streams in side panel
  app/components/public/stream/side-panel.ts
Labels: fix

#6972 fix: remove overlapping in order card in my tickets.
  app/components/public/event-venue.hbs
  app/styles/partials/event-card.scss
  app/templates/components/order-card.hbs
Labels: fix

#6965 fix: Email and Contact button not in one line and heading not standardized
  app/templates/public/exhibition/view.hbs
Labels: fix

#6939 feat: Session Item: Make track, session room and date to direct to respected filter
  app/components/public/session-item.hbs
  app/styles/libs/_helpers.scss
Labels: feature

#6977 fix: Remove user detail before saving in cookie
  app/services/auth-manager.js
Labels: fix

#6771 feat: Add or Remove Video Moderator
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/ui-table/cell/events/view/videoroom/cell-email.hbs
  app/controllers/events/view/videoroom/list.js
  app/models/video-stream-moderator.ts
  app/models/video-stream.ts
  app/routes/events/view/videoroom/edit.js
  app/routes/events/view/videoroom/list.js
  tests/unit/models/video-stream-moderator-test.ts
Labels: feature

#6980 fix: scroll video stream side panel
  app/components/public/stream/side-panel.hbs
  app/styles/components/stream.scss
Labels: fix

#6990 fix: Public Schedule Calendar View still showing hidden rooms
  app/controllers/public/schedule.js
  app/templates/public/schedule.hbs
Labels: fix

#6991 fix: Virtual Event Chat: Accessing page when not logged in shows error
  app/routes/public/chat.ts
Labels: fix

#6981 feat: Add Confirmation Modal before Chat page
  app/models/user.js
  app/routes/public/chat.ts
  app/templates/components/modals/confirm-modal.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: feature

#6996 fix: Put exhibitor logo above Name and make it larger.
  app/templates/components/public/exhibition-view.hbs
Labels: fix

#6817 feat: Show current day schedule in schedule page if event is running.
  app/routes/public/sessions.js
Labels: feature

#7010 fix: Increase file limit to 30 MB in session speaker form
  app/templates/components/forms/session-section.hbs
Labels: fix

#7027 feat: show BBB recordings
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
Labels: feature

#7004 feat: Social Link: Add mastodon in Sessions, Speaker, Events
  app/components/icons/mastodon.hbs
  app/components/public/session-item.hbs
  app/mixins/custom-form.js
  app/models/custom-form.js
  app/models/session.js
  app/models/speaker.js
  app/templates/components/public/social-links.hbs
  app/utils/dictionary/social-media.ts
Labels: feature

#7050 fix: Align copy button in event share modal.
  app/templates/components/modals/event-share-modal.hbs
Labels: fix

#7052 feat: Allow Chat Toggle
  app/components/public/stream/side-panel.ts
  app/controllers/events/view/chat.js
  app/models/event.js
  app/router.js
  app/routes/events/view/chat.js
  app/templates/events/view.hbs
  app/templates/events/view/chat.hbs
Labels: feature

#7017 feat: add record, autoStartMeeting, muteOnStart parameters to bbb
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/models/video-stream.ts
Labels: feature

#7085 fix: hiding import section, and export is in alpha stage
  app/templates/events.hbs
  app/templates/events/view/settings/export.hbs
Labels: fix
