Repository fossasia/open-event-frontend, pull requests merged in 2021-07, with the labels that each got.

#7481 feat: Create BBB recordings overview for admins and enhance admin video area
  app/components/forms/admin/video-channel-form.ts
  app/controllers/admin/video/channels/index.js
  app/controllers/admin/video/recordings.js
  app/router.js
  app/routes/admin/video/channels/create.js
  app/routes/admin/video/channels/edit.js
  app/routes/admin/video/channels/index.js
  app/routes/admin/video/index.js
  app/routes/admin/video/recordings.js
  app/templates/admin.hbs
  app/templates/admin/video.hbs
  app/templates/admin/video/channels/create.hbs
  app/templates/admin/video/channels/edit.hbs
  app/templates/admin/video/channels/index.hbs
  app/templates/admin/video/index.hbs
  app/templates/admin/video/recordings.hbs
Labels: feature

#7506 fix: simplyfing schedule page
  app/styles/libs/_helpers.scss
  app/templates/public/sessions.hbs
Labels: fix

#7499 fix: Event Transfer: add message to void previous owner invites
  app/templates/components/modals/confirm-event-transfer-modal.hbs
Labels: fix

#7501 feat: video recording delete option for admin
  app/controllers/admin/video/recordings.js
  app/templates/components/ui-table/cell/admin/cell-recording-action.hbs
Labels: feature

#7502 fix: follow group button overlapping on event page.
  app/templates/public.hbs
Labels: fix

#7522 fix: Increase docs/slides upload size to 20 MB
  app/components/forms/document-upload.hbs
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/templates/components/forms/events/view/edit-session.hbs
Labels: fix

#7428 feat: Implement video tab on/off switch similar to wizard switches and show pop-up
  app/components/public/stream/join-video.hbs
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/controllers/events/view/videoroom/list.js
  app/models/event.js
  app/templates/events/view/videoroom/list.hbs
Labels: feature

#7533 fix: add owner downgrade to organzier popup message
  app/templates/components/modals/confirm-event-transfer-modal.hbs
  app/templates/components/modals/event-transfer-modal.hbs
Labels: fix

#7537 feat: Make upload size dynamic.
  app/components/forms/document-upload.hbs
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/models/setting.js
  app/templates/components/forms/admin/settings/billing.hbs
  app/templates/components/forms/admin/settings/system-form.hbs
  app/templates/components/forms/events/view/edit-session.hbs
  app/templates/components/forms/session-section.hbs
  app/templates/components/forms/speaker-section.hbs
  app/templates/components/forms/user-profile-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/forms/wizard/sponsors-step.hbs
  app/templates/components/modals/change-image-modal.hbs
Labels: feature

#7356 feat: Ask user to end current BBB running meeting after updating video stream
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/models/video-stream.ts
Labels: blocked-by-server, feature

#7544 fix: Implement check before update bbb video
  app/components/forms/events/view/videoroom-form.js
Labels: fix

#7534 fix: requirements of eventSeparate Upcoming and Past events on View and Edit page of group
  app/components/forms/group/group-events-form.js
  app/components/forms/group/group-view.js
  app/templates/components/forms/group/group-events-form.hbs
  app/templates/components/forms/group/group-view.hbs
Labels: fix

#7557 feat: enhance admin group table
  app/controllers/admin/groups/list.js
  app/models/group.js
  app/routes/admin/groups/list.js
Labels: feature

#7545 feat: Groups box on admin start page
  app/adapters/admin-statistics-group.js
  app/models/admin-statistics-group.js
  app/routes/admin/index.js
  app/templates/admin/index.hbs
Labels: feature

#7555 feat: Add group banner and logo
  app/models/group.js
  app/templates/components/forms/group/group-settings-form.hbs
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/group-card.hbs
  app/templates/groups/view.hbs
Labels: feature

#7535 fix: add group about
  app/templates/components/forms/group/group-settings-form.hbs
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/group-card.hbs
Labels: feature, fix

#7556 fix: simplify admin sales page
  app/components/ui-table/cell/admin/sales/cell-first-name.js
  app/controllers/admin/sales/index.js
  app/models/admin-sales-by-event.js
  app/templates/admin/sales.hbs
  app/templates/components/ui-table/cell/admin/sales/cell-first-name.hbs
Labels: fix

#7560 chore: fix sass warning & future deprecation
  app/styles/pages/public-event.scss
Labels: chore

#7563 fix: Group Card: Slice long about text
  app/components/group-card.js
  app/templates/components/group-card.hbs
Labels: fix

#7565 fix: remove live stream and webinar link
  app/components/forms/wizard/basic-details-step.js
  app/models/event.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/public/index.hbs
Labels: fix

#7566 fix: Enhance group view page
  app/components/forms/group/group-events-form.js
  app/components/forms/group/group-view.js
  app/templates/components/forms/group/group-events-form.hbs
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/group-card.hbs
  public/images/group.png
Labels: fix

#7578 feat: Add a View button for groups on the "My Groups" tab
  app/templates/components/group-card.hbs
Labels: feature

#7567 fix: arrange sales in arranging order
  app/controllers/admin/sales/index.js
Labels: fix

#7579 fix: admin section cursor
  app/styles/libs/_helpers.scss
  app/templates/components/forms/admin/settings/analytics-form.hbs
  app/templates/components/forms/admin/settings/images-form.hbs
  app/templates/components/forms/admin/settings/microservices-form.hbs
  app/templates/components/forms/admin/settings/system-form.hbs
  app/templates/components/forms/admin/settings/system/social-media-token.hbs
  app/templates/components/forms/admin/settings/ticket-fees-form.hbs
Labels: fix

#7561 feat: update payment status
  app/components/ui-table/cell/admin/sales/cell-status-action.hbs
  app/controllers/admin/sales/invoices.js
  app/routes/account/billing/invoices/list.js
  app/templates/account/billing/invoices.hbs
  app/templates/components/event-invoice/invoice-summary.hbs
Labels: feature

#7592 fix: adding view button in grop edit page
  app/templates/components/group-nav.hbs
Labels: fix

#7574 fix: Group: create page and edit page alike
  app/components/forms/group/group-events-form.js
  app/components/forms/group/group-settings-form.js
  app/templates/components/forms/group/group-events-form.hbs
  app/templates/components/forms/group/group-settings-form.hbs
  app/templates/components/group-header.hbs
  app/templates/components/group-nav.hbs
  app/templates/components/ui-table/cell/admin/groups/cell-group-name.hbs
  app/templates/groups/create.hbs
  app/templates/groups/following.hbs
  app/templates/groups/list.hbs
Labels: fix

#7580 feat: add contact options for group
  app/components/modals/contact-organizer.js
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/modals/contact-organizer.hbs
Labels: feature

#7559 feat: add isCfsEnabled field and save announcement
  app/components/forms/wizard/sessions-speakers-step.js
  app/components/public/side-menu.js
  app/models/event.js
  app/routes/public/cfs/index.js
  app/templates/components/events/view/overview/event-setup-checklist.hbs
Labels: blocked-by-server, feature

#7607 fix: null social link error
  app/components/forms/group/group-settings-form.js
Labels: fix

#7608 fix: mobile view: add group tab in sidebar
  app/templates/components/side-bar.hbs
Labels: fix

#7591 fix: admin section cursor
  app/controllers/groups/team.js
  app/templates/components/tabbed-navigation.hbs
Labels: fix

#7581 fix: don't redirect on standard start page on clicking back button
  app/controllers/application.js
  app/templates/components/nav-bar.hbs
Labels: fix

#7611 fix: show frontend and server version on admin index page
  app/controllers/admin/index.js
  app/templates/admin/index.hbs
Labels: fix

#7618 feat: Group Follow: add popup when group is followed
  app/controllers/public.js
Labels: feature

#7622 fix: center contact button on group page
  app/templates/components/forms/group/group-view.hbs
Labels: fix

#7521 fix: Group Following Tab: add group follow/unfollow buttons
  app/components/forms/group/group-view.js
  app/components/group-card.js
  app/routes/groups/following.js
  app/routes/groups/list.js
  app/routes/groups/view.js
  app/styles/libs/_helpers.scss
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/group-card.hbs
Labels: fix

#7617 fix: redirect to /create after login
  app/routes/create.js
Labels: fix

#7620 feat: Groups: Add "Followers" page for Owners/Organizers
  app/controllers/groups/edit/followers.js
  app/models/user-follow-group.ts
  app/router.js
  app/routes/groups/edit/followers.js
  app/templates/components/group-card.hbs
  app/templates/components/group-nav.hbs
  app/templates/components/ui-table/cell/cell-user-image.hbs
  app/templates/groups/edit/followers.hbs
Labels: feature

#7628 fix: changed contact button color in group to blue
  app/templates/components/forms/group/group-view.hbs
Labels: fix

#7632 feat: show testing deployment version on admin page
  app/controllers/admin/index.js
  app/templates/admin/index.hbs
Labels: feature

#7631 feat: Group: add followers count
  app/models/group.js
  app/styles/partials/text.scss
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/group-card.hbs
  app/templates/public.hbs
Labels: feature
