Repository fossasia/open-event-frontend, pull requests merged in 2021-11, with the labels that each got.

#8012 fix: allow admin to restore deleted group
  app/adapters/group.js
  app/controllers/admin/groups/list.js
  app/templates/components/ui-table/cell/admin/groups/cell-group-name.hbs
Labels: fix

#8020 chore: updated and added tranlatable strings
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#8028 fix: make strings translatable
  app/controllers/account/billing/invoices/list.js
  app/templates/components/events/view/overview/general-info.hbs
  app/templates/components/forms/group/group-settings-form.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/events/view/chat.hbs
  app/templates/events/view/documents.hbs
  app/templates/events/view/videoroom/list.hbs
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: fix

#8040 feat: adding speaker sorting
  app/components/forms/session-speaker-form.js
  app/components/public/session-item.hbs
  app/components/public/session-item.js
  app/models/speaker.js
Labels: feature

#8045 fix: handled edge case in sorted speaker show
  app/components/public/session-item.js
Labels: fix

#8046 fix: speaker section responsiveness
  app/templates/components/public/featured-speaker-list.hbs
Labels: fix

#8051 fix: make role translatable & capitalize
  app/templates/components/modals/add-user-role-modal.hbs
Labels: fix

#7948 feat: make ticket holder info editable
  app/components/forms/orders/attendee-list.js
  app/templates/components/forms/orders/attendee-list.hbs
Labels: feature

#8035 chore: add more strings for translation
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/group/group-events-form.js
  app/components/public/stream/chat-panel.ts
  app/controllers/events/view/videoroom/list.js
  app/routes/public/chat.ts
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#7999 feat: Upgrade stripe checkout to latest version
  app/controllers/orders/pending.js
  app/routes/orders/view.js
  app/templates/orders/pending.hbs
  package.json
  yarn.lock
Labels: feature

#8078 fix: explore groups now shows all groups as expected
  app/templates/components/group-card.hbs
Labels: fix

#8079 chore: make strings translatable
  app/controllers/events/view/exhibitors/list.js
  app/controllers/events/view/sessions/list.js
  app/templates/components/event-invoice/payee-info.hbs
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/order-card.hbs
  app/templates/components/orders/ticket-holder.hbs
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#8019 chore: Fix and enhance tax and invoice information in wizard step 1
  app/components/modals/tax-info-modal.js
  app/mixins/event-wizard.js
  app/models/tax.js
  app/styles/components/extras.scss
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/tax-info-modal.hbs
  app/templates/components/orders/company-info.hbs
Labels: chore

#8083 chore: make strings translatable
  app/controllers/events/view/tickets/access-codes/list.js
  app/controllers/events/view/tickets/discount-codes/list.js
  app/templates/components/events/view/overview/manage-roles.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/tables/default.hbs
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#8098 chore: make strings translatable
  app/helpers/convert-to-normal-string.js
  app/templates/components/event-invoice/invoice-summary.hbs
  app/templates/components/ui-table/cell/cell-event-date.hbs
  app/templates/components/ui-table/cell/cell-tickets.hbs
  tests/integration/helpers/convert-to-normal-string-test.js
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#8101 fix: improve spelling & punctuation quality
  app/components/forms/events/view/create-discount-code.js
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/orders/order-form.js
  app/controllers/admin/users/view/events/list.js
  app/controllers/public/speaker-invite/view-session.js
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/group-header.hbs
  app/templates/components/modals/event-transfer-modal.hbs
  app/templates/components/modals/user-delete-modal.hbs
  app/templates/events/view/settings/export.hbs
  app/templates/groups/list.hbs
  app/templates/my-groups/list.hbs
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: fix

#8104 fix: missing punctuations
  app/components/forms/orders/order-form.js
  app/templates/components/forms/group/group-view.hbs
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: fix

#8105 fix: more punctuations
  app/components/events/view/overview/manage-roles.js
  app/components/forms/admin/video-channel-form.ts
  app/components/forms/events/view/exhibitors/exhibitor-form.ts
  app/components/forms/group/group-events-form.js
  app/components/forms/group/group-settings-form.js
  app/components/forms/orders/attendee-list.js
  app/components/forms/user-payment-info-form.js
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/sessions-speakers-step.js
  app/components/modals/contact-organizer.js
  app/components/modals/session-notify-modal.hbs
  app/components/modals/tax-info-modal.js
  app/controllers/admin/users/list.js
  app/controllers/events/view/exhibitors/list.js
  app/controllers/events/view/speakers/create.js
  app/controllers/events/view/speakers/reorder.ts
  app/controllers/events/view/tickets/discount-codes/list.js
  app/controllers/groups/team.js
  app/controllers/register.js
  app/mixins/event-wizard.js
  app/templates/application.hbs
  app/templates/components/event-card.hbs
  app/templates/components/forms/admin/settings/ticket-fees-form.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/contact-organizer.hbs
  app/templates/components/public/call-for-speakers.hbs
  app/templates/components/public/exhibition-view.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
  app/templates/events/view/session/view.hbs
  app/templates/public/cfs/view-session.hbs
  app/templates/public/speaker-invite/view-session.hbs
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: fix

#8114 chore: enhance sentences
  app/components/forms/admin/settings/billing.js
  app/components/forms/orders/order-form.js
  app/components/forms/user-payment-info-form.js
  app/components/forms/user-profile-form.js
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/sessions-speakers-step.js
  app/components/modals/tax-info-modal.js
  app/controllers/admin/users/view/account/contact-info.js
  app/controllers/events/view/speakers/create.js
  app/controllers/orders/view.js
  app/templates/components/event-card.hbs
  app/templates/components/event-invoice/billing-info.hbs
  app/templates/components/events/view/export/download-zip.hbs
  app/templates/components/events/view/overview/event-apps.hbs
  app/templates/components/forms/admin/settings/billing.hbs
  app/templates/components/forms/user-payment-info-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/modals/tax-info-modal.hbs
  app/templates/components/widgets/forms/billing-info.hbs
  app/templates/components/widgets/forms/location-input.hbs
  translations/bn.po
  translations/de.po
  translations/de_DIVEO.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/sv.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#8119 feat: Added node js check below 15 in package.json
  package.json
Labels: feature

#8123 fix: show correct start/end time & duration in recordings column of v…
  app/components/ui-table/cell/events/view/videoroom/cell-recording.js
  app/templates/components/ui-table/cell/events/view/videoroom/cell-recording.hbs
Labels: fix

#8115 feat: Show prompt to login when follow group clicked on promoted group
  app/components/forms/group/group-view.js
  app/components/promoted-group-card.js
  app/styles/partials/welcome.scss
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/promoted-group-card.hbs
Labels: feature

#8121 fix: show timezone of ticket buyer on order page
  app/templates/components/orders/event-info.hbs
  app/templates/orders/view.hbs
Labels: fix

#8126 fix: promoted groups now visible on frontpage as expected
  app/routes/index.js
Labels: fix

#8112 fix: able to follow group on event page
  app/controllers/public.js
  app/routes/public.js
  app/templates/public.hbs
Labels: fix

#8144 fix: event cards now show up everytime as expected with correct information on group public page
  app/routes/group-public.js
Labels: fix

#8084 fix: show promotional code only on paid tickets & registration
  app/components/public/ticket-list.js
  app/controllers/public/index.js
  app/templates/public/index.hbs
Labels: fix
