Repository fossasia/open-event-frontend, pull requests merged in 2021-06, with the labels that each got.

#7371 chore: run tests for testing branch
  .github/workflows/ci.yml
  .github/workflows/scripts.yml
  .travis.yml
Labels: chore

#7139 fix: Change selected video room text to previous state on cancel
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
Labels: fix

#7376 fix: enable recording of BBB video stream by default
  app/components/forms/events/view/videoroom-form.js
Labels: fix

#7370 fix: ask moderators to order a ticket for the event.
  app/components/forms/events/view/videoroom-form.hbs
Labels: fix

#7187 feat: add group tab in admin section
  app/controllers/admin/groups/list.js
  app/models/group.js
  app/router.js
  app/routes/admin/groups.js
  app/routes/admin/groups/index.js
  app/routes/admin/groups/list.js
  app/templates/admin.hbs
  app/templates/admin/groups.hbs
  app/templates/admin/groups/list.hbs
  app/templates/components/ui-table/cell/admin/groups/cell-group-name.hbs
Labels: blocked-by-server, feature

#7368 fix: ticket input in wizard closing issue on hiding ticket
  app/components/widgets/forms/ticket-input.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/widgets/forms/ticket-input.hbs
Labels: fix

#7375 fix: error "Could not fetch from the server"
  app/components/events/view/export/api-response.js
  app/templates/events/view/settings/export.hbs
Labels: fix

#7225 fix: Explore Page: Event card alignment
  app/styles/partials/event-card.scss
  app/styles/partials/utils.scss
  app/templates/components/event-card.hbs
Labels: fix

#7378 feat: add infinity loader for events at edit group page
  app/routes/groups/edit.js
  app/templates/groups/edit.hbs
Labels: feature

#7387 fix: Dropdown icon to the event creation steps to make it more user friendly.
  app/templates/components/tabbed-navigation.hbs
  app/templates/events/view/team.hbs
Labels: fix

#7185 feat: Session Forms: Provide dropdown field for levels
  app/components/forms/session-section.js
  app/components/forms/session-speaker-form.js
  app/controllers/public.js
  app/controllers/public/sessions.js
  app/mixins/custom-form.js
  app/routes/public/sessions.js
  app/templates/components/forms/session-section.hbs
  app/templates/public.hbs
  app/utils/dictionary/levels.ts
Labels: blocked-by-server, feature

#7396 fix: Microlocation Video Rooms Uipop changed to text.
  app/templates/events/view/videoroom/list.hbs
Labels: fix

#7321 fix: Session and Exhibitor Form Simplify Slide Form Element
  app/templates/components/widgets/forms/file-upload.hbs
Labels: fix

#7355 feat: add VideoRecording model
  app/components/forms/events/view/videoroom-form.js
  app/components/ui-table/cell/cell-duration.hbs
  app/components/ui-table/cell/cell-duration.js
  app/models/video-recording.ts
  app/models/video-stream.ts
Labels: blocked-by-server, feature

#7400 fix: Session and Exhibitor Form Simplify Slide Form Element
  app/components/forms/events/view/exhibitors/exhibitor-form.hbs
  app/templates/components/forms/session-section.hbs
  app/templates/components/widgets/forms/file-upload.hbs
Labels: LGTM, fix

#7402 fix: Social Link Fields Overlapping of name and url boxes in wizard 2
  app/components/widgets/forms/social-link-field.hbs
Labels: LGTM, fix

#7343 feat: Speaker/Session CSV/PDF Export should adhere to filters
  app/controllers/events/view/sessions.js
  app/controllers/events/view/speakers.js
  app/templates/events/view/sessions.hbs
  app/templates/events/view/speakers.hbs
Labels: LGTM, blocked-by-server, feature

#7430 feature: send reset mail and resend verification via admin section
  app/components/ui-table/cell/admin/users/cell-user-actions.hbs
  app/controllers/admin/users/list.js
Labels: feature

#7418 chore: Remove all sequentially awaited code to make site respond faster
  app/routes/admin/content/events.js
  app/routes/admin/index.js
  app/routes/admin/permissions/event-roles.js
  app/routes/admin/permissions/system-roles.js
  app/routes/admin/settings/images.js
  app/routes/create.js
  app/routes/events/view/edit.js
  app/routes/events/view/session/edit.js
  app/routes/events/view/sessions/create.js
  app/routes/events/view/settings/options.js
  app/routes/events/view/speaker/edit.js
  app/routes/events/view/speakers/create.js
  app/routes/events/view/tickets/discount-codes/edit.js
  app/routes/events/view/tickets/index.js
  app/routes/explore.js
  app/routes/public/cfs/new-session.js
  app/routes/public/cfs/new-speaker.js
Labels: LGTM, chore

#7432 fix: Substitute text with "eventyay" to use appName from admin section
  app/components/forms/events/view/videoroom-form.hbs
  app/components/public/stream/chat-panel.ts
  app/controllers/events/view/videoroom/list.js
  app/controllers/register.js
  app/routes/public/chat.ts
  app/templates/components/forms/wizard/other-details-step.hbs
Labels: fix

#7452 fix: CFS: Not able to turn ON cfs for my event
  app/components/forms/wizard/sessions-speakers-step.js
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: fix

#7450 fix: only show session level filter on schedule if session form have level enabled
  app/controllers/public.js
  app/routes/public.js
  app/templates/public.hbs
Labels: fix

#7442 feat: Enable admin to set specific event as start page instead of standard page
  app/controllers/application.js
  app/models/setting.js
  app/templates/application.hbs
  app/templates/components/forms/admin/settings/system-form.hbs
  app/templates/components/forms/admin/settings/system/start-page.hbs
Labels: blocked-by-server, feature

#7443 fix: Do not show icon and notifications anymore.
  app/router.js
  app/templates/components/nav-bar.hbs
  tests/acceptance/notifications-test.js
  tests/integration/components/notification-dropdown-test.js
Labels: fix

#7457 feat: Role Invite: Allow users to resend invitations of event transfer from the settings page itself.
  app/controllers/events/view/settings/options.js
  app/routes/events/view/settings/options.js
Labels: feature

#7456 fix: dropdown menu stays on top
  app/components/side-bar.js
  app/styles/libs/_helpers.scss
  app/templates/public.hbs
Labels: fix

#7467 fix: schedule page cut off in mobile view
  app/components/side-bar.js
  app/styles/libs/_helpers.scss
  app/templates/public/sessions.hbs
Labels: fix

#7342 feat: Order steps are missing tax information.
  app/templates/components/orders/order-summary.hbs
Labels: feature

#7344 fix: order paid ticket with unverified account
  app/components/public/ticket-list.js
  app/templates/components/public/ticket-list.hbs
Labels: fix

#7466 feat: Add Multiple Event "Documents" to the system
  app/components/forms/document-upload.hbs
  app/components/forms/document-upload.js
  app/controllers/events/view/documents.js
  app/models/event.js
  app/router.js
  app/routes/events/view/documents.js
  app/templates/components/orders/document-info.hbs
  app/templates/events/view.hbs
  app/templates/events/view/documents.hbs
  app/templates/orders/view.hbs
Labels: feature

#7477 feat: Add Followed Group View Page
  app/components/forms/group/group-view.js
  app/components/side-bar.js
  app/controllers/groups/team.js
  app/controllers/groups/view.js
  app/router.js
  app/routes/group-invites.js
  app/routes/groups/team.js
  app/routes/groups/view.js
  app/styles/libs/_helpers.scss
  app/templates/components/event-card.hbs
  app/templates/components/forms/group/group-view.hbs
  app/templates/components/group-card.hbs
  app/templates/components/group-header.hbs
  app/templates/groups/following.hbs
  app/templates/groups/list.hbs
  app/templates/groups/team.hbs
  app/templates/groups/view.hbs
Labels: feature
