Repository fossasia/open-event-frontend, pull requests merged in 2021-01, with the labels that each got.

#6197 chore: Change videoroom URL to video
  app/router.js
Labels: chore

#6198 fix: disable caching for user
  app/services/auth-manager.js
Labels: fix

#6178 fix: Change light gray font to dark gray
  app/styles/partials/colors.scss
  app/styles/partials/form.scss
  app/styles/partials/text.scss
Labels: fix

#6212 feat: Redirect logged out or non attendee video stream to event page
  app/components/modals/simple-modal.hbs
  app/components/modals/simple-modal.js
  app/components/public/stream/side-panel.ts
  app/controllers/public.js
  app/routes/public/stream/view.ts
  app/templates/public.hbs
Labels: feature

#6200 fix: overflow of the data elements from the container
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/orders/ticket-holder.hbs
Labels: fix

#6094 feat: introduce is_public in session-speaker wizard
  app/components/forms/wizard/custom-forms/table.hbs
  app/mixins/custom-form.js
  app/models/custom-form.js
Labels: feature

#6223 fix: Hide search box on wizard pages
  app/components/nav-bar.js
  app/templates/components/nav-bar.hbs
Labels: fix

#6228 fix: hide "create event" on wizard pages for mobile view
  app/templates/components/nav-bar.hbs
Labels: fix

#6144 fix: creating events with same starting and ending time
  app/components/forms/wizard/basic-details-step.js
  app/components/widgets/forms/time-picker.js
  app/templates/components/widgets/forms/time-picker.hbs
Labels: fix

#6134 fix: Changed slide in/out button
  app/components/public/stream/side-panel.hbs
  app/styles/components/stream.scss
Labels: fix

#6195 fix: Implement abstraction layer in add session-speaker form
  app/components/forms/session-section.js
  app/components/forms/speaker-section.js
  app/templates/components/forms/session-section.hbs
  app/templates/components/forms/session-speaker-form.hbs
  app/templates/components/forms/speaker-section.hbs
Labels: fix

#6201 fix: Video Tab: Icons aligned when event or video room has a long name
  app/styles/libs/_helpers.scss
  app/styles/partials/utils.scss
  app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-title.hbs
Labels: fix

#6153 fix: mobile view: need adjustment in elements
  app/components/forms/wizard/wizard-footer.hbs
  app/templates/components/forms/wizard/attendee-step.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
  app/templates/components/forms/wizard/sponsors-step.hbs
Labels: fix

#6229 fix: Session table styling
  app/controllers/events/view/sessions/list.js
  app/styles/partials/buttons.scss
  app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-lock-session.hbs
Labels: fix

#6239 fix: Use stream hash to show same color in side panel
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/models/video-stream.ts
  app/utils/text.ts
Labels: fix

#6240 fix: read custom prop of undefined attendee step
  app/controllers/events/view/edit/attendee.js
Labels: fix

#6238 fix: Different day time check mistake of #6144
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#6243 fix: Missing info where Captcha is used in admin section
  app/templates/components/forms/admin/settings/system/captcha-form.hbs
Labels: fix

#6251 chore: Switch dev API host to dokku
  .env.example
  .github/workflows/ci.yml
  README.md
  config/environment.js
  docs/Integrate-local-deployment.md
  docs/installation/local.md
  netlify.toml
Labels: chore

#6219 fix: reduced space below speaker
  app/components/public/session-item.hbs
Labels: fix

#6264 feat: Only show rooms with published sessions in side panel
  app/components/public/side-menu.js
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/controllers/events/view/scheduler.js
  app/controllers/public/schedule.js
  app/models/event.js
  app/templates/components/public/side-menu.hbs
  app/templates/events/view/scheduler.hbs
  app/templates/public/schedule.hbs
Labels: feature

#6268 chore: Update translations
  docs/installation/local.md
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#6271 fix: scroll in video meeting
  app/components/public/stream/video-stream.hbs
  app/styles/components/stream.scss
Labels: fix

#6241 fix: Simplify Access code
  app/models/access-code.js
  app/routes/events/view/tickets/access-codes/list.js
  app/templates/components/forms/events/view/create-access-code.hbs
  app/templates/events/view/tickets/access-codes/create.hbs
Labels: fix

#6254 fix: pagination page size in message list
  app/controllers/admin/messages.js
  app/controllers/admin/messages/list.js
  app/router.js
  app/routes/admin/messages.js
  app/routes/admin/messages/index.js
  app/routes/admin/messages/list.js
  app/templates/admin/messages.hbs
Labels: fix

#6280 fix: Organizer Menu Tab: Change Order
  app/templates/events/view.hbs
Labels: fix

#6247 fix: Show only scheduled days
  app/controllers/public/sessions.js
Labels: fix

#6285 feat: Admin Provide Option "Not to show on Frontpage"
  app/controllers/admin/events/list.js
  app/models/event.js
  app/templates/components/ui-table/cell/admin/events/event-no-front.hbs
Labels: feature

#6290 fix: price validation logic of donation ticket
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#6289 fix: Standardize Microlocations or Virtual Online Rooms Requirement
  app/templates/components/forms/wizard/sessions-speakers-step.hbs
Labels: fix

#6291 fix: Prevent snackbar from blocking touches on mobile
  app/styles/partials/snackbar.scss
Labels: fix

#6297 fix: "Click here to add" for social links directs to the wrong wizard step
  app/templates/components/events/view/overview/general-info.hbs
Labels: fix

#6299 fix: Sort social links alphabetically
  app/utils/dictionary/social-media.ts
Labels: fix

#6082 fix: extra links shown in boxes
  app/styles/libs/_helpers.scss
  app/templates/components/public/social-links.hbs
Labels: fix

#6282 feat: Add Join Event button
  app/components/public/stream/join-video.hbs
  app/components/public/stream/join-video.ts
  app/components/public/stream/stream-info.hbs
  app/templates/components/modals/confirm-modal.hbs
  app/templates/public.hbs
  app/templates/public/index.hbs
Labels: feature

#6309 fix: Wizard Step 1 Tax information country field opens
  app/templates/components/country-dropdown.hbs
Labels: fix

#6308 fix: Billing Info checkbox
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#6311 fix: isDemoted cfs fix for admin
  app/routes/index.js
Labels: fix

#6307 fix: alignment of ticket-list columns
  app/styles/components/ticket-list.scss
Labels: fix

#6314 fix: Public Event Pages: Link event logo and text to event start page top
  app/styles/libs/_helpers.scss
  app/templates/public.hbs
Labels: fix

#6315 fix: Allow speaker to be created without session
  app/controllers/events/view/speakers/create.js
Labels: fix

#6316 fix: Don't override evenr ID if undefined
  app/mixins/event-relation.js
Labels: fix

#6317 fix: Use event identifier in role invite page
  app/routes/public/role-invites.js
Labels: fix

#6236 fix: enhance design of video-panel button
  app/components/public/stream/side-panel.hbs
  app/styles/components/stream.scss
  app/styles/partials/nav-bar.scss
  app/styles/partials/utils.scss
  app/templates/components/nav-bar.hbs
Labels: fix

#6329 fix: updated tagline
  app/templates/components/welcome-header.hbs
Labels: fix

#6332 fix: admin not able to delete events
  app/components/modals/event-delete-modal.js
  app/controllers/admin/events/list.js
  app/templates/admin/events/list.hbs
  app/templates/components/ui-table/cell/cell-event.hbs
Labels: fix

#6244 fix: Video Room Need further enhancement
  app/components/forms/events/view/videoroom-form.hbs
Labels: fix

#6334 fix: add url box and width distribution
  app/controllers/events/list.js
  app/templates/components/ui-table/cell/cell-link.hbs
  app/templates/components/url-box.hbs
Labels: fix

#6351 chore: Update translations
  app/templates/components/public/social-links.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#6362 fix: Limit Time of Event Duration to Maximum 20 days to limit spam events
  app/components/forms/wizard/basic-details-step.js
Labels: fix

#6368 feat: Switch locale by lang query
  app/services/l10n.js
Labels: feature

#6372 fix: Team Member: Fix button text and enable translation
  app/templates/components/events/view/overview/manage-roles.hbs
  app/templates/components/modals/add-system-role-modal.hbs
  app/templates/components/modals/add-user-role-modal.hbs
Labels: fix

#6234 feat: Separate Private and Public Speaker and Session Info
  app/components/public/speaker-item.js
  app/controllers/events/view/session/edit.js
  app/controllers/events/view/session/view.js
  app/controllers/events/view/sessions/list.js
  app/controllers/events/view/speaker/edit.js
  app/controllers/events/view/speaker/view.js
  app/controllers/events/view/speakers/list.js
  app/router.js
  app/routes/events/view/session/edit.js
  app/routes/events/view/session/view.js
  app/routes/events/view/speaker/edit.js
  app/routes/events/view/speaker/view.js
  app/templates/components/events/view/overview/session-view.hbs
  app/templates/components/events/view/overview/speaker-view.hbs
  app/templates/components/public/speaker-item.hbs
  app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs
  app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs
  app/templates/events/view/session/edit.hbs
  app/templates/events/view/session/view.hbs
  app/templates/events/view/speaker/edit.hbs
  app/templates/events/view/speaker/view.hbs
Labels: feature

#6386 fix: changed In-Person Event and Online Event -> Online and In-Person Event at
  app/controllers/public.js
Labels: fix

#6312 fix: added company info block on the tickets view page
  app/routes/orders/new.js
  app/routes/orders/view.js
  app/styles/components/all.scss
  app/styles/components/company-info.scss
  app/templates/components/orders/company-info.hbs
  app/templates/components/orders/event-info.hbs
  app/templates/orders/new.hbs
  app/templates/orders/view.hbs
  tests/integration/components/orders/company-info-test.js
Labels: fix

#6359 fix: made tagline text and button little up
  app/styles/partials/welcome.scss
Labels: fix

#6388 feat: Add afterOrderMessage field in event
  app/models/event.js
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/orders/after-order-message.hbs
  app/templates/orders/pending.hbs
  app/templates/orders/view.hbs
Labels: feature

#6395 fix: changed mixed to hybrid event
  app/components/forms/wizard/basic-details-step.js
  app/mixins/event-wizard.js
  app/templates/components/explore/side-bar.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#6389 fix: same dialog design for join event and join video
  app/components/modals/simple-modal.hbs
  app/components/modals/simple-modal.js
  app/components/public/stream/join-video.ts
  app/controllers/public.js
  app/templates/public.hbs
Labels: fix

#6275 fix: Ticket Sales: Sold out tickets are not bookable
  app/components/public/ticket-list.js
  app/templates/components/public/ticket-list.hbs
Labels: fix

#6343 feat: allow deletion of roles
  app/components/events/view/overview/manage-roles.js
  app/models/event.js
  app/models/users-events-role.js
  app/routes/events/view/index.js
  app/routes/events/view/team/index.ts
  app/templates/components/events/view/overview/manage-roles.hbs
Labels: feature

#6355 feat: Enable admins to change users from "Unverified" to "Verified"
  app/controllers/admin/users/list.js
  app/models/user.js
  app/templates/components/ui-table/cell/admin/users/cell-user-verify.hbs
Labels: feature

#6276 chore: remove sendAction()
  app/components/account/password-section.js
  app/components/modals/add-system-role-modal.js
  app/components/modals/add-user-role-modal.js
  app/components/modals/admin/content/new-event-sub-topic-modal.js
  app/components/modals/admin/content/new-event-topic-modal.js
  app/components/modals/admin/content/new-event-type-modal.js
  app/components/modals/confirm-event-transfer-modal.js
  app/components/nav-bar.js
  app/components/side-bar.js
  app/components/widgets/forms/date-picker.js
  app/components/widgets/forms/time-picker.js
Labels: chore

#6281 fix: Access Code Functionality
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#6417 fix: reset of ticket buying form & scrolling error
  app/components/forms/orders/order-form.js
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#6425 chore: Add ability to translate via no-op function
  app/components/forms/orders/order-form.js
  app/components/forms/wizard/basic-details-step.js
  app/routes/public/stream/view.ts
  app/services/loader.ts
  app/services/tn.ts
  app/templates/components/country-dropdown.hbs
  app/templates/components/forms/admin/settings/ticket-fees-form.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
  app/templates/components/forms/wizard/other-details-step.hbs
  app/utils/dictionary/demography.ts
  app/utils/dictionary/licenses.ts
  app/utils/dictionary/payment.ts
  app/utils/text.ts
  tests/unit/services/tn-test.ts
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#6432 fix: Revert preselecting same as buyer
  app/components/forms/orders/order-form.js
Labels: fix

#6421 fix: allow admin to mark account as spam
  app/controllers/admin/users/list.js
  app/models/user.js
  app/templates/components/ui-table/cell/admin/users/cell-mark-spam.hbs
Labels: fix

#6438 fix: Copy all time components
  app/utils/computed-helpers.js
Labels: fix

#6411 fix: Order Form Stripe Payment: Increase button size
  app/styles/libs/stripe_connect.scss
  app/templates/orders/pending.hbs
Labels: fix

#6414 fix: Attendee Form: Added Instagram and Linkedin
  app/components/forms/orders/order-form.js
  app/mixins/custom-form.js
  app/models/attendee.js
  app/models/custom-form.js
  app/utils/validators.js
Labels: fix

#6409 fix: wrong download option, billing icon and text
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/forms/orders/order-form.hbs
  app/templates/components/orders/order-summary.hbs
Labels: fix

#6447 feat: Add "view-speaker" page for cfs
  app/controllers/public.js
  app/controllers/public/cfs/edit-speaker.js
  app/controllers/public/cfs/new-speaker.js
  app/controllers/public/cfs/view-speaker.js
  app/router.js
  app/routes/public/cfs/view-speaker.js
  app/templates/components/events/view/overview/speaker-view.hbs
  app/templates/public.hbs
  app/templates/public/cfs/view-speaker.hbs
Labels: feature

#6451 fix: Move role-invites out from event nesting
  app/router.js
  app/routes/role-invites.js
  app/templates/role-invites.hbs
Labels: fix

#6452 fix: error in regex for instagram profile url
  app/utils/validators.js
Labels: fix

#6455 fix: Show after order message with whitespace preserved
  app/components/public/stream/stream-info.hbs
  app/styles/libs/_helpers.scss
  app/templates/components/orders/after-order-message.hbs
Labels: fix

#6426 feat: Add "view-session" page for cfs speaker
  app/controllers/public.js
  app/controllers/public/cfs/edit-session.js
  app/controllers/public/cfs/new-session.js
  app/controllers/public/cfs/view-session.js
  app/router.js
  app/routes/public/cfs/view-session.js
  app/templates/components/events/view/overview/session-view.hbs
  app/templates/components/public/call-for-speakers.hbs
  app/templates/components/session-card.hbs
  app/templates/public/cfs/view-session.hbs
Labels: feature

#6449 feat: added url box on public event pages
  app/styles/components/all.scss
  app/styles/components/events/view/overview/general-info.scss
  app/templates/components/events/view/overview/general-info.hbs
Labels: feature

#6435 feat: Attendee Form: Add user content for various options
  app/components/forms/orders/order-form.js
  app/mixins/custom-form.js
  app/models/attendee.js
  app/models/custom-form.js
  app/templates/components/forms/orders/attendee-list.hbs
  app/templates/components/forms/orders/order-form.hbs
Labels: feature

#6401 fix: search bar enhancement and working
  app/components/nav-bar.js
  app/styles/pages/events.scss
  app/templates/components/nav-bar.hbs
Labels: fix

#6465 fix: Sort events by descending in admin
  app/controllers/admin/events/list.js
Labels: fix

#6466 fix: Ticket sorting logic in event wizard
  app/components/forms/wizard/basic-details-step.js
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#6337 fix: Virtual Events: Moved Big Blue Button minimize button to avoid overlap
  app/styles/components/stream.scss
  app/styles/partials/nav-bar.scss
  app/templates/components/nav-bar.hbs
Labels: fix

#6467 fix: Sorting logic
  app/controllers/admin/events/list.js
  app/controllers/admin/reports/system-logs/activity-logs.js
  app/controllers/admin/reports/system-logs/mail-logs.js
  app/controllers/admin/reports/system-logs/notification-logs.js
  app/controllers/admin/users/list.js
  app/controllers/events/view/tickets/attendees/list.js
  app/controllers/events/view/tickets/orders/list.js
  app/mixins/ember-table-route.js
Labels: fix

#6470 fix: Error on submitting order form while consent options are ticked
  app/components/forms/orders/order-form.js
  app/templates/components/forms/orders/order-form.hbs
Labels: fix

#6474 fix: Loading mechanism of events list
  app/components/ui-table/cell/cell-roles.js
  app/controllers/admin/events/list.js
  app/controllers/events/list.js
  app/controllers/public/cfs/view-speaker.js
  app/models/event-statistics-general.js
  app/routes/admin/events/list.js
  app/routes/events/list.js
  app/routes/public/cfs/view-speaker.js
  app/serializers/event-statistics-general.js
  app/templates/components/events/view/overview/speaker-session.hbs
  app/templates/components/ui-table/cell/cell-roles.hbs
  app/templates/components/ui-table/cell/cell-speakers-dashboard.hbs
Labels: fix

#6477 feat: Add event link, event description and organizer message
  app/components/public/add-to-calender.ts
Labels: feature

#6369 fix: Virtual Events: Enhance "Join Event" functionality and side panel style
  app/components/public/stream/join-video.hbs
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/stream-info.hbs
  app/styles/libs/_helpers.scss
  app/templates/public.hbs
Labels: fix

#6442 feat: group feature implementation
  app/components/forms/group/group-form.js
  app/controllers/groups/create.js
  app/controllers/groups/edit.js
  app/controllers/groups/list.js
  app/models/group.js
  app/models/user.js
  app/router.js
  app/routes/groups.js
  app/routes/groups/create.js
  app/routes/groups/edit.js
  app/routes/groups/list.js
  app/templates/components/event-card.hbs
  app/templates/components/forms/group/group-form.hbs
  app/templates/components/group-card.hbs
  app/templates/components/nav-bar.hbs
  app/templates/groups.hbs
  app/templates/groups/create.hbs
  app/templates/groups/edit.hbs
  app/templates/groups/list.hbs
Labels: feature

#6464 feat: Add Contact organizer feature
  app/components/modals/contact-organizer.js
  app/controllers/public/index.js
  app/templates/components/modals/contact-organizer.hbs
  app/templates/components/public/ticket-list.hbs
  app/templates/public/index.hbs
Labels: feature

#6488 chore: Update and fix translations
  .github/workflows/ci.yml
  app/templates/application.hbs
  app/templates/components/footer-main.hbs
  app/templates/public/cfs/view-session.hbs
  app/templates/public/cfs/view-speaker.hbs
  translations/bn.po
  translations/de.po
  translations/en.po
  translations/es.po
  translations/fr.po
  translations/hi.po
  translations/id.po
  translations/ja.po
  translations/ko.po
  translations/messages.pot
  translations/nb_NO.po
  translations/pl.po
  translations/ru.po
  translations/th.po
  translations/vi.po
  translations/zh_Hans.po
  translations/zh_Hant.po
Labels: chore

#6468 fix: CfS: Add private/public badge into edit form
  app/templates/components/forms/session-section.hbs
  app/templates/components/forms/speaker-section.hbs
Labels: fix

#6502 feat: added url box to access and discount coupons
  app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-actions.hbs
  app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-url.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions.hbs
  app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-url.hbs
Labels: feature

#6503 fix: Sort ticket list by event date
  app/routes/my-tickets/upcoming/list.js
Labels: fix

#6511 fix: Display number of speakers in event overview page
  app/templates/components/events/view/overview/speaker-session.hbs
Labels: fix

#6427 fix: Make spacing between social buttons equal in all dimensions
  app/components/public/add-to-calender.hbs
  app/styles/libs/_helpers.scss
  app/templates/components/public/social-links.hbs
  app/templates/public.hbs
Labels: fix

#6496 fix: Removed embed meeting option from toolbar
  app/components/public/stream/jitsi-stream.ts
Labels: fix

#6519 fix: Public Session Page: Do not show edit, withdraw and status
  app/controllers/public/session/view.js
  app/templates/public/session/view.hbs
Labels: fix

#6501 fix: don't cancel ticket in past
  app/routes/account/danger-zone.js
  app/templates/components/order-card.hbs
  app/templates/my-tickets/past.hbs
Labels: fix

#6026 feat: Mapbox and osm implementation
  .env.example
  app/components/explore/side-bar.js
  app/components/public/event-map.js
  app/components/widgets/forms/location-input.js
  app/components/widgets/forms/places-autocomplete.js
  app/routes/explore.js
  app/templates/components/explore/side-bar.hbs
  app/templates/components/public/event-map.hbs
  app/templates/components/widgets/forms/location-input.hbs
  config/environment.js
  package.json
  tests/integration/components/widgets/forms/places-autocomplete-test.js
  yarn.lock
Labels: Priority: High, Priority: Urgent, feature

#6536 fix: Loads availability of ticket and remove error from console at add order page
  app/components/public/ticket-list.js
Labels: fix

#6524 fix: Timezone issue in cfs
  app/utils/computed-helpers.js
Labels: fix

#6545 fix: added url to the speaker image and action buttons
  app/controllers/events/view/speakers/list.js
  app/styles/partials/text.scss
  app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs
  app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs
  app/templates/components/ui-table/cell/events/view/speakers/speaker-logo.hbs
Labels: fix

#6550 fix: added <> around emails
  app/components/modals/session-notify-modal.js
Labels: fix

#6522 fix: Online Event Sidebar Align text and buttons
  app/components/public/stream/side-panel.hbs
  app/styles/components/stream.scss
  app/styles/partials/utils.scss
Labels: fix

#6553 fix: Exit from restoreUser if user ID is null
  app/services/auth-manager.js
Labels: fix

#6562 fix: Speaker event_id crash and moment warning
  app/controllers/public.js
  app/templates/components/public/speaker-item.hbs
Labels: fix

#6564 fix: Load less speakers in one go
  app/routes/public/speakers.js
Labels: fix

#6560 fix: Speaker Images now using content area fully
  app/components/public/speaker-item.js
  app/templates/components/public/featured-speaker-list.hbs
  app/templates/components/public/speaker-list.hbs
  app/templates/public/speakers.hbs
Labels: fix
