Repository fossasia/open-event-frontend, pull requests merged in 2021-04, with the labels that each got.

#7086 fix: handle error on duplicate invite
  app/components/events/view/overview/manage-roles.js
Labels: fix

#7093 fix: schedules are showing twice when sorting by popularity
  app/controllers/public/sessions.js
Labels: fix

#7096 fix: show import section to admin in event list
  app/templates/events.hbs
Labels: fix

#6790 fix: Hcaptcha not loading causing block from signup/reset-password
  app/components/forms/register-form.js
  app/components/forms/reset-password-form.js
  app/templates/components/forms/register-form.hbs
  app/templates/components/forms/reset-password-form.hbs
Labels: fix

#7099 feat: Display session language in session item
  app/components/public/session-item.hbs
Labels: feature

#7108 fix: Additional info for chat on/off
  app/templates/events/view/chat.hbs
Labels: fix

#7071 feat: Create private chat room per event
  app/components/public/stream/chat.ts
  app/models/event.js
  app/templates/public/chat.hbs
Labels: feature

#7095 feat: dropdown filter for live, past, all events in admin-sales
  app/router.js
  app/routes/admin/sales/index.js
  app/templates/admin.hbs
  app/templates/admin/sales.hbs
  app/templates/admin/sales/index.hbs
  tests/acceptance/admin-sales-accessibility-test.js
Labels: feature

#7115 feat: Restructure email settings
  app/controllers/admin/messages.js
  app/models/message-setting.js
  app/templates/components/ui-table/cell/admin/messages/cell-options.hbs
  app/templates/components/ui-table/cell/cell-title-message.hbs
Labels: feature

#7132 fix: Sort notifications by created_at
  app/components/notification-dropdown.js
Labels: fix

#7090 feat: adding rocket chat in right side panel in video room
  app/components/public/stream/chat-panel.hbs
  app/components/public/stream/chat-panel.ts
  app/components/public/stream/chat.ts
  app/components/public/stream/join-video.hbs
  app/components/public/stream/join-video.ts
  app/components/public/stream/stream-info.hbs
  app/components/public/stream/video-stream.hbs
  app/components/public/stream/video-stream.ts
  app/controllers/public.js
  app/styles/components/stream.scss
  app/templates/public.hbs
Labels: feature

#7144 fix: Side panel not opening
  app/components/forms/events/view/videoroom-form.js
  app/templates/public.hbs
Labels: fix

#7145 chore: Add gender fields
  app/utils/dictionary/genders.ts
Labels: chore

#7131 feat: add bbb recording table in video edit page
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/templates/components/ui-table/cell/events/view/videoroom/cell-video-recording.hbs
Labels: feature

#7149 fix: Remove notification-action model and fix notifications test
  app/models/notification-action.js
  app/models/notification.js
  app/routes/notifications/all.js
Labels: fix

#7143 fix: Add message for slide upload in CFS form
  app/templates/components/widgets/forms/file-upload.hbs
Labels: fix

#7147 feat: Add 3cx as video channel
  app/components/forms/events/view/videoroom-form.js
  app/components/public/stream/video-stream.hbs
  app/components/public/stream/video-stream.ts
  app/models/video-channel.ts
Labels: feature

#7140 feat: add video channel tab in admin section.
  app/components/forms/admin/video-channel-form.hbs
  app/components/forms/admin/video-channel-form.ts
  app/controllers/admin/video-channels/index.js
  app/models/video-channel.ts
  app/router.js
  app/routes/admin/video-channels/create.js
  app/routes/admin/video-channels/edit.js
  app/routes/admin/video-channels/index.js
  app/templates/admin.hbs
  app/templates/admin/video-channels.hbs
  app/templates/admin/video-channels/create.hbs
  app/templates/admin/video-channels/edit.hbs
  app/templates/admin/video-channels/index.hbs
  app/templates/components/ui-table/cell/cell-channel-action.hbs
Labels: feature

#7134 feat: adding team section for groups for managing roles
  app/controllers/groups/view.js
  app/models/group.js
  app/models/users-groups-role.js
  app/router.js
  app/routes/group-invites.js
  app/routes/groups/view.js
  app/templates/components/group-card.hbs
  app/templates/groups/view.hbs
Labels: feature
