Repository fossasia/open-event-frontend, pull requests merged in 2022-02, with the labels that each got.

#8321 fix: make url fields in attendee forms clickable
  app/helpers/is-url-field.js
  app/templates/components/forms/orders/attendee-list.hbs
Labels: fix

#8306 fix: Prevent organizer from saving event with paid tickets if no paym…
  app/components/events/view/publish-bar.ts
  app/components/forms/wizard/basic-details-step.js
  app/components/forms/wizard/wizard-footer.hbs
  app/templates/components/forms/wizard/basic-details-step.hbs
Labels: fix

#8281 feat: make ateendee info editable
  app/components/forms/orders/attendee-list.js
  app/helpers/is-url-field.js
  app/templates/components/forms/orders/attendee-list.hbs
Labels: feature

#8292 feat: redirect users to login if already registered during role invite
  app/components/forms/login-form.js
  app/routes/role-invites.js
Labels: feature

#8333 fix: chat button points to side chat panel
  app/components/public/stream/chat-panel.hbs
  app/components/public/stream/chat-panel.ts
  app/components/public/stream/side-panel.hbs
  app/components/public/stream/side-panel.ts
  app/controllers/public.js
  app/templates/public.hbs
Labels: fix

#8314 feat: add chatmosphere to video forms
  app/components/forms/events/view/videoroom-form.hbs
  app/components/forms/events/view/videoroom-form.js
  app/components/public/stream/video-stream.hbs
  app/models/video-channel.ts
  app/models/video-stream.ts
Labels: feature, DO-NOT-MERGE

#8363 fix: remove group permissions from frontend
  app/routes/groups/edit/events.js
  app/routes/groups/edit/followers.js
  app/routes/groups/edit/settings.js
  app/routes/groups/team.js
Labels: fix
